ampproject/amp.dev

- content/docs/reference/_blueprint.yaml
- content/docs/support/_blueprint.yaml
- podspec.yaml
- views/partials/lang_switcher.html
- views/partials/nav.html
- Fix localized links in nav menu by verifying Reference and Support sections are localized.
- Use new Grow feature to switch sourcecode Markdown blocks to use classes instead of inline styles.
- Improve the durability of the locale switcher by using Grow APIs for localizing documents.
- Bump Grow version to 0.0.65 (not released yet).
> Continue work on megamerge (localization and source highlighting)

- README.md
- views/base.html
- views/partials/nav.html
Hi @pbakaus, this fixes the build time issue. :) I was doing something very stupid and expensive when generating the nav menu (notice the removal of the `O(n)` check). The whole site (all locales) builds in about five minutes on my machine now, and I'm pretty happy with that time.
Next week I'll look into some additional caching or optimizations that can be done on the Grow side, but I think a five minute build for 3000 Markdown files is hopefully reasonable enough for now! [Still would like to make it faster though. ;)]
This PR also contains two minor other things
- Use `doc.locale.is_rtl` instead of checking a hardcoded `ar` locale.
- Update the README to remove `grow deploy` since it's not used in this workflow, nor does that command actually work without a destination anyway.
If you …
> Fix build time issue and two other tiny cleanups

- assets/sass/_config.scss
- assets/sass/_global.scss
- assets/sass/_mixins.scss
- assets/sass/_syntax_highlighting.scss
For pages such as
https://www.ampproject.org/docs/guides/validate.html and
https://www.ampproject.org/docs/reference/amp-img.html,
the reader encounteres a fair amount of text. This is currently
configured to be displayed with $color-grey-600, also
known as $color-black-54, which is #757575. On less than optimal
screens and for people with less than optimal eyes, this is tiring
to read. I think my corrected vision is quite good and I wear
fancy computer glasses in front of a great 30" screen,
but even I notice it. So I'd like to crank this up a bit, to $424242
($color-grey-800).
Detailed changes:
- _config.css, can remove color-black-54, since I'm removing the
last usage.
- _global.scss, set the color for code snippets (typically the things
tagged with `single backtick`) to this new …
> Darken the text in reference pages a bit.

- firebase.json
We plan to remove the duplicated README files for amp-ad. This is a prerequisite.
See https://github.com/ampproject/amphtml/pull/4761
> Add 301 redirect for amp-ad.md

- assets/sass/_sidebar.scss
When opening the sidebar in mobile viewport then making viewport wider, sidebar styles are removed. This PR removes the media query that restricts the sidebar styles to only "mobile", allowing for a consistent mobile experience (think switching from portrait to landscape with sidebar open on devices with unusually large screens). Compare the before and after images below.
> Fix sidebar responsiveness

- assets/sass/_global.scss
I found that I can't scroll the script box below on [this pages](https://www.ampproject.org/learn/how-amp-works/#dont-let-extension-mechanisms-block-rendering).
> ```<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-youtube-0.1.js"></script>```
I'm using Chrome 54. 
The ```::before``` components block scrolling. When I delete that, Anything changed but I could scroll.
What actually do ```h(n):before``` styles for?
> Remove hx:before tag blocking scroll

- content/docs/guides/analytics_amp.md
- content/docs/guides/analytics_amp/deep_dive_analytics.md
- content/docs/guides/analytics_amp@ar.md
- content/docs/guides/analytics_amp@es.md
- content/docs/guides/analytics_amp@fr.md
- content/docs/guides/analytics_amp@id.md
- content/docs/guides/analytics_amp@it.md
- content/docs/guides/analytics_amp@ja.md
- content/docs/guides/analytics_amp@ko.md
- content/docs/guides/analytics_amp@nl.md
- content/docs/guides/analytics_amp@pl.md
- content/docs/guides/analytics_amp@pt_BR.md
- content/docs/guides/analytics_amp@ru.md
- content/docs/guides/analytics_amp@th.md
- content/docs/guides/analytics_amp@tr.md
- content/docs/guides/analytics_amp@zh_CN.md
* brower -> browser
* substition -> substitution (also affects navigation)
Fix navigation from the translations as well.
Signed-off-by: Dan Scott <dan@coffeecode.net>
> Typos in analytics guides: browser substitution

- scripts/update_platforms_page.js
New entry 'Ghost' for supported platform, as well as links to all the other platforms.
> Add Ghost as supported content platform

- scripts/import_docs.js
Added requisite of whitespace before mustache code elements so that mustache syntax code in codeblocks will render correctly. Tested and diff'd results.
Fixes issue #272 
to/ @pbakaus
> Fix mustache syntax rendering - issue 272

- content/docs/reference/common_attributes.md
A doc that will be linked/referred from amp component docs that describe the common attributes for AMP components.
to: @pbakaus 
cc: @cramforce 
In a different PR, I'll show how an amp component's doc "attributes" section will refer to this doc. Example - https://github.com/ampproject/amphtml/pull/6772
> Create doc for common attributes to most/all AMP components

- assets/sass/_header.scss
Hi! 😸 
Since there is together alphabet font and Japanese characters(`ドキュメント`, `サポート`) font,  these height are not aligned.
Here is a screenshot: on the top is current situation, on the bottom is with `vertical-align: top;`.
> fix vertical-align on header navigation

- assets/sass/_syntax_highlighting.scss
Red highlighting is distracting in code syntax (for example, using ellipses or the lightning bolt are considered errors).
> Turn off red highlighting for error syntax (e.g. amp-form)

- content/docs/guides/login-paywalls.md
The link[1] on the guide to login-paywalls is 404ing
[1] https://www.ampproject.org/docs/reference/content/docs/get_started/login_requiring.html
> Fix url so that login-requiring does not 404

- assets/sass/_global.scss
this causes the "learn more" link on the global note to be
unclickable.
> remove margin from h*:before pseudo classes

- assets/sass/_global.scss
Reverts ampproject/docs#296. Broke anchor based navigation. Better fix is to do a z-index on the banner for now.
> Revert "remove margin from h*:before pseudo classes"

- content/docs/guides/responsive_amp/art_direction.md
These snippets wouldn't validate without having width and height.  
to: @pbakaus
> Add height + width to examples for amp-img

- content/docs/guides/responsive_amp/style_pages.md
The link to "Add styles to a page" at https://www.ampproject.org/docs/guides/responsive/style_pages is broken - it points to a page about validation.
BTW, why do we have both "responsive" and "responsive_amp" as a URL path element?
https://www.ampproject.org/docs/guides/responsive_amp
vs.
https://www.ampproject.org/docs/guides/responsive/style_pages
> Fix broken link to add styles to a page

- content/pages/how-it-works.html
- pwa/pwa.html
It was decided these weren't needed in AMP some time ago, see
https://github.com/ampproject/amphtml/issues/592, and prevent
zooming in to read the text on the How It Works page.
> Remove maximum-scale etc from how-it-works.

- content/contribute/contribute.md
Adds additional context to the "How to Contribute" page to expand on the AMP Project's appreciation of contributions and provide additional options for helping out.
This PR only contains the English version.
> Expand the "How to Contribute" page to encourage more contributions

- content/docs/guides/responsive_amp/style_pages.md
Some minor nitpicks:
* `<link rel="icon">` is sufficient to specify a favicon in every modern browser. More info: https://mathiasbynens.be/notes/rel-shortcut-icon (It would be even better to not use any HTML at all and to place the favicon at `/favicon.ico` — even if it’s a PNG.)
* `type="text/css"` is implied for stylesheets. More info: https://mathiasbynens.be/notes/html5-levels#type-attributes
> Simplify HTML example

- content/docs/get_started/create/prepare_for_discovery.md
Using the keyword "paired" gives us a helpful way to reference one of the main AMP publishing models. This incorporates that terminology into our getting started guide.
> Update discovery guidance to establish "paired" terminology

- scripts/import_docs.js
Fixes https://github.com/ampproject/amphtml/issues/7449
The [amp-mustache](https://github.com/ampproject/amphtml/blob/master/extensions/amp-mustache/amp-mustache.md#restrictions) doc utilizes triple braces like so: "The triple-mustache `{{{var}}}`has to be used for these cases."  However, when the doc is imported to ampproject/docs, the first brace is dropped and renders like so: "The triple-mustache `{{var}}}` ...".
- Updated script to account for additional brace.
- Ran parallel test, comparing output, only amp-mustache affected and differences are as expected.
> Fix script for triple braces in mustache

- content/docs/contribute/contribute.md
Fixes issue #339.
- Remove the link to DEVELOPING since it's not the main entry point any more anyway.
- Add a specific callout for new open source contributors.
- Fix the link for editing the page they are reading.
cc @adelinamart @pbakaus
> Fix links from the How to Contribute page

- assets/sass/_syntax_highlighting.scss
- content/docs/contribute/file-a-bug.md
- content/docs/contribute/github.md
- content/docs/guides/author_develop.md
- content/docs/guides/debug.md
- content/docs/guides/deploy.md
- content/latest/list-event.html
- content/latest/list-past-event.html
- content/learn/who-uses-amp.yaml
- content/learn/who/ad-tech-platforms.yaml
- content/learn/who/advertisers.yaml
- content/learn/who/amp-ads.yaml
- content/learn/who/publishers.yaml
- content/support/developer/documentation-bug.md
- content/support/developer/platform-bug.md
- content/support/developer/slack.md
- content/support/developer/stack-overflow.md
1.  Corrected elements in markdown and yaml files to make certain elements (mostly titles) pulled out for translation (add `@`).
1.  Fix CSS so that red highlighting doesn't display for syntax highlighting (like we had before in [PR 286](https://github.com/ampproject/docs/pull/286))
> Make variables translatable + minor css

- content/learn/amp-design-principles@ko.yaml
- translations/ko/LC_MESSAGES/messages.po
Docs build broken.  Fixed translations:
1) Removed variables (not needed in translated files)
2) Fixed indentations and extra quotes
3) Fixed msgstr
> Fix KO translations to fix broken build

- scripts/update_platforms_page.js
The list of analytics vendors is now in [guides/deploy/analytics_amp/analytics-vendors.md](https://github.com/ampproject/docs/blob/master/content/docs/guides/deploy/analytics_amp/analytics-vendors.md).
Tested locally and passed.
> Amend location for list of analytics vendors

- content/docs/build.md
- content/includes/menu.yaml
- views/grid_docs_page.html
- views/partials/grid-card-docs.html
Created landing page to orient readers to various parts of docs and other valuable locations.
Fixes #390 
Looks like:
> Add landing page for Docs section

- assets/sass/_content.scss
IMHO the border on top of the headings in the docs is unnecessary. The visual separation between blocks is already achieved with the top margin, and the border simply makes it seem more busy. Compare:
WDYT @bpaduch @leeee ?
> Remove <h2> border to give the text room to breathe

- content/pages/home.html
It looks like GA discards any `ev=<empty string>` events. We'd like to debug why, but in meantime we want to see the numbers.
> Debugging visibility time=0

- content/docs/reference/components.md
- scripts/component_categories.json
- Including reference docs for: amp-gist, amp-facebook-comments, amp-nexxtv-player.
- Updating links and components page
- Removing amp-share-tracking - still in development and no docs
Fixes: #427, #426 , #425
> Include docs for new components

- content/docs/guides/responsive_amp.md
- content/docs/guides/responsive_amp/art_direction.md
- content/docs/guides/responsive_amp/custom_fonts.md
- content/docs/guides/responsive_amp/responsive_design.md
I also extended the paragraph in the top section to point to the new Responsive guide. I still would like to highlight it a little better. Right now, we have mixed stuff in these things we call Guides:
1. Actual documentation/specs (e.g. docs on the layout attribute)
2. Explainers / Guides
Would like to address that issue at some point.
> Reorder style section guides and slightly reword some

- content/docs/build.md
- content/includes/home.yaml
- translations/ar/LC_MESSAGES/messages.po
- translations/de/LC_MESSAGES/messages.po
- translations/es/LC_MESSAGES/messages.po
- translations/fr/LC_MESSAGES/messages.po
- translations/id/LC_MESSAGES/messages.po
- translations/it/LC_MESSAGES/messages.po
- translations/ja/LC_MESSAGES/messages.po
- translations/ko/LC_MESSAGES/messages.po
- translations/messages.pot
- translations/pl/LC_MESSAGES/messages.po
- translations/pt_BR/LC_MESSAGES/messages.po
- translations/ru/LC_MESSAGES/messages.po
- translations/th/LC_MESSAGES/messages.po
- translations/tr/LC_MESSAGES/messages.po
- translations/zh_CN/LC_MESSAGES/messages.po
Just removing variables for URLs so they are not included in .po files for translations.  Also, ran `grow extract` to extract translations.
> Remove translation variables for urls; re-extracted translations

- views/doc_grid.html
- views/partials/grid-card.html
@SidVal noticed that the titles on the grid landing pages weren't all translated; it should be using the translated variables.  Fixed now.
Related to:https://github.com/ampproject/docs/pull/473#issuecomment-300559601
> Fix grids so pulls in translated titles

- examples/src/ampad.html
- examples/src/ampform.html
Adding examples that will be embedded in the reference docs for: amp-ad and amp-form.
Demos: [amp-form](https://barb-ampdocs.firebaseapp.com/amp-form.html), [amp-ad](https://barb-ampdocs.firebaseapp.com/amp-ad.html#example:-displaying-a-few-ads)
> Adding examples for amp-ad and amp-form

- content/docs/tutorials/create/basic_markup.md
> Fix typo in basic_markup.md

- content/docs/reference/components.md
- content/docs/reference/components/_blueprint.yaml
- scripts/component_categories.json
Now that amp-facebook-live component is in production, include it in the docs. Related to: #483 
Also, adjusted side-nav so "1st" component listed is selected when user selects "Social"
Also, removed "amp-share-tracking" from docs because a) there are no docs for the component.
> Include amp-facebook-like component into docs

- views/partials/breadcrumb-nav.html
This PR adds localization support to the breadcrumbs as well as the following minor improvements:
- Add comments for improved readability
- Normalize variable names to improve others' ability to more easily identify the pattern
- Prefer `do` instead of `if` hack
- Prefer underscore naming convention
- Properly indent `set` blocks by using [whitespace control](http://jinja.pocoo.org/docs/dev/templates/#whitespace-control)
> Add localization support for breadcrumbs and other minor improvements

- views/partials/head.html
This PR applies the `gettext` function to page titles. The translations have already been done, this just activates them on non-default locales. This also prepares #501 to utilize an alternative method for breadcrumb translations.
> Incorporate `gettext` function for extracted title translations

- content/support/faqs/supported-browsers.md
- content/support/faqs/supported-browsers@es.md
- content/support/faqs/supported-browsers@ko.md
- content/support/faqs/supported-platforms.md
- content/support/faqs/supported-platforms@es.md
- content/support/faqs/supported-platforms@ko.md
- scripts/update_platforms_page.js
- translations/es/LC_MESSAGES/messages.po
- translations/ko/LC_MESSAGES/messages.po
- translations/messages.pot
Took out "Supported Browsers" section from "Supported Vendors..." and made it it's own topic so it's easier to find and consume.
Also within Supported Browsers linked up images (they were already there, just not generated in yaml), so it'll look like this:
Note, had to add title to messages.po file because the localized title in the actual .md wasn't being picked up.  I suspect it's related to the fixes that Derek will implement (in https://github.com/ampproject/docs/pull/501).
FYI: This was related to some SO questions about this topic.
> Broke out "Supported Browsers" as separate topic in FAQs

- scripts/update_blog_links.js
- views/partials/breadcrumb-nav.html
In addition to the changes mentioned in #486, this PR accounts for path errors as seen in #481, which were also causing the build to break with the previous rendition of this PR. This seems like a Grow bug to me, but I will have to investigate further to see why paths that are only defined in the blueprint are based on collection names. This PR builds without errors and I've tested it to ensure that it is working properly. The reason why several of the breadcrumbs are not translated is because their respective titles are not translated, which may be something worth working on.
> Add partial localization support for breadcrumbs and other minor improvements

- content/docs/guides/responsive_amp/style_pages.md
- content/docs/guides/responsive_amp/style_pages@ar.md
- content/docs/guides/responsive_amp/style_pages@de.md
- content/docs/guides/responsive_amp/style_pages@es.md
- content/docs/guides/responsive_amp/style_pages@fr.md
- content/docs/guides/responsive_amp/style_pages@id.md
- content/docs/guides/responsive_amp/style_pages@it.md
- content/docs/guides/responsive_amp/style_pages@ja.md
- content/docs/guides/responsive_amp/style_pages@ko.md
- content/docs/guides/responsive_amp/style_pages@pl.md
- content/docs/guides/responsive_amp/style_pages@pt_BR.md
- content/docs/guides/responsive_amp/style_pages@ru.md
- content/docs/guides/responsive_amp/style_pages@th.md
- content/docs/guides/responsive_amp/style_pages@tr.md
- content/docs/guides/responsive_amp/style_pages@zh_CN.md
- views/partials/head.html
Per Greg's comment in https://github.com/ampproject/docs/issues/369#issuecomment-305253425, the meta is a no-op so removing from template.
> Remove meta tag for X-UA-Compatible

- content/learn/who-uses-amp@es.yaml
- content/learn/who-uses-amp@it.yaml
- content/learn/who-uses-amp@ko.yaml
- translations/ar/LC_MESSAGES/messages.po
- translations/de/LC_MESSAGES/messages.po
- translations/es/LC_MESSAGES/messages.po
- translations/fr/LC_MESSAGES/messages.po
- translations/id/LC_MESSAGES/messages.po
- translations/it/LC_MESSAGES/messages.po
- translations/ja/LC_MESSAGES/messages.po
- translations/ko/LC_MESSAGES/messages.po
- translations/messages.pot
- translations/pl/LC_MESSAGES/messages.po
- translations/pt_BR/LC_MESSAGES/messages.po
- translations/ru/LC_MESSAGES/messages.po
- translations/th/LC_MESSAGES/messages.po
- translations/tr/LC_MESSAGES/messages.po
- translations/zh_CN/LC_MESSAGES/messages.po
Fixes #520 
Localized text now in localized files, not in translation variables.  
Still need to fix #519
> Pick up localization for who-uses-amp page

- content/learn/who-uses-amp.yaml
- content/learn/who-uses-amp@es.yaml
- content/learn/who-uses-amp@it.yaml
- content/learn/who-uses-amp@ko.yaml
- views/about-who.html
Fixes #519 
Card name was being used as filename and title, but when localized it broke.  Broke out filename as separate - always will be english filename.
> Fix issue 519 - card name localization

- .gitignore
- scripts/import_docs.json
Per Malte's request in https://github.com/ampproject/amphtml/pull/7430#issuecomment-307210873, importing the AMP Cache Debugging guide into docset.
> Import AMP Cache Debugging guide

- content/docs/reference/experimental.md
Removed typo (i.e., 'Q&A') from article and replaced with 'quality assurance (QA)'.
> Updated experimental.md by changing 'Q&A' to 'quality assurance (QA)'

- content/docs/guides/responsive_amp.md
Per initiative to integrate vids into docs, I've embedded the "Beautiful, Canonical, Responsive AMP Pages" vid into main "Style & Layout" guide.
> Add AMP Conf video on beautiful AMPs to doc

- assets/img/ic_open_in_new_blue.svg
- assets/sass/_content-post.scss
To make it apparent that links are "external" to the site, adding CSS and icon that will be used in ref docs, like in the following example:
Now, I'll just need to change all the ref docs that have examples, and add class="external" + consistent wording.
cc: @mattludwig
> Add icon and CSS for external links in ref docs

- content/docs/tutorials/create/include_image@es.md
Modified link name from 'Include Iframes and Media' to 'Include Images & Video' for Spanish.
> (ES) Modified link name "Include images & videos"

- content/pages/amp-roadshow.html
Fixes #665 
By removing the specific locale ("en"), it'll default to default behavior, and for any language, if there's no localized page, it'll just server the default - the English version.  There are no plans to translate this page as it's quite variable.
Tested changes locally with diff locales.
cc: @pbakaus
> Remove en specific localization so locales pick up page

- .travis.yml
- content/docs/reference/components.md
- scripts/component_categories.json
Include new components to docs: amp-imgur, amp-web-push, and amp-position-observer.
Fixes: https://github.com/ampproject/docs/issues/674
nit: cleanup grow version now that 0.2.4 works
cc: @honeybadgerdontcare
> Add new components to docs

- content/docs/guides/responsive_amp/custom_fonts.md
This adds Typekit to the whitelist for custom font serving. This feature was released by Typekit on 2017/08/30 (https://blog.typekit.com/2017/08/30/css-font-loading/). Help documentation can be found here: https://pages.typekit.com/early-access-user-guides/en/css-kits/#html-amp
> Add Typekit origin for serving custom fonts.

- content/docs/guides/responsive_amp/placeholders.md
Added the WebP fallback example (and text) to the fallback guide.
> Add diff image formats example to fallback doc

- .gitignore
- assets/sass/_content-section.scss
- content/support/developer/mailing-list.md
- scripts/import_docs.js
- scripts/import_docs.json
Importing [AMPHTML's support.md](https://github.com/ampproject/amphtml/blob/master/SUPPORT.md) file into ampproject.org docs.  Adding the doc to the "Developer Support" section.
cc: @rudygalfi, @cramforce 
Note: Needed to amend format in support.md - see https://github.com/ampproject/amphtml/pull/11474
> Importing support.md file and adding to dev support section

- examples/src/ampfittext.html
Adding embedded demo code for amp-fit-text.  Docs for amp-fit-text will be updated once these examples are up in production.
> Add example snippets for amp-fit-text

- content/docs/tutorials/login_requiring/add_comment@es.md
- content/docs/tutorials/login_requiring/add_comment@id.md
- content/docs/tutorials/login_requiring/add_comment@ja.md
- content/docs/tutorials/login_requiring/add_comment@pt_BR.md
- content/docs/tutorials/login_requiring/add_comment@zh_CN.md
- content/support/faqs/supported-browser@id.md
- content/support/faqs/supported-browser@ja.md
- content/support/faqs/supported-browser@pt_BR.md
- content/support/faqs/supported-browser@zh_CN.md
- content/support/faqs/supported-platforms@id.md
- content/support/faqs/supported-platforms@ja.md
- content/support/faqs/supported-platforms@ko.md
- content/support/faqs/supported-platforms@pt_BR.md
- content/support/faqs/supported-platforms@zh_CN.md
Updated the following articles:
1) add_comments.md (i.e., creating a login-requiring AMP page, step 2) (es, id, ja, pt_BR, zh_CN)
- Replacing the (es) version with the updated one.
2) supported-browser.md (id, ja, pt_BR, zh_CN)
3) supported-platforms.md (es, id, ja, ko, pt_BR, zh_CN)
- Replacing the (es) and (ko) version with the updated one.
> New batch of T1 locale translations (three articles, 15 translations)

- content/docs/guides/analytics_amp/analytics-vendors.md
As mediarithmics was added as a Vendor yesterday (cf: https://github.com/ampproject/amphtml/pull/11472), I updated the analytics-vendors doc as requested.
> Add mediarithmics entry in analytics-vendors

- content/includes/menu.yaml
Shorten About->Case Studies submenu to show categories instead of all case studies.
> Shorten About->Case Studies submenu

- assets/sass/_header.scss
Remove box-shadow so that mysterious gray box won't appear on hamburger menu hover.
I don't believe this rule applies anywhere else on the site.  I did look around!
Fixes: https://github.com/ampproject/docs/issues/472
> Remove hamburger menu random gray box

- .gitignore
- scripts/import_docs.json
Import the [Actions and Events in AMP](https://github.com/ampproject/amphtml/blob/master/spec/amp-actions-and-events.md) doc into site.
Cleaning up doc in: https://github.com/ampproject/amphtml/pull/11919
> Import the AMP Events & Actions doc into site

- content/docs/guides/integrate-with-apps.md
Adding new guide for Integrating AMP pages with your app.  This PR is implementing the content that was already written and reviewed (in the Google Doc) into Markdown format for the ampproject site.
Preview of what it'll look like: [Here](https://barb-ampdocs.firebaseapp.com/docs/guides/integrate-with-apps.html)
to: @sebastianbenz 
cc: @cramforce, @rudygalfi, @pbakaus, @adewale 
Fixes: #548
> Add guide for Integrating AMP into your app

- content/docs/guides/analytics_amp/analytics-vendors.md
This adds Alexa Internet to the amp-analytics provider list.
Fixes [#11966](https://github.com/ampproject/amphtml/issues/11966)
> Add new amp-analytics vendor: Alexa Internet

- content/includes/roadmap.yaml
This PR reflects the actual status of the progress made. It seems as though these components were not bumped forward on the roadmap update.
> Fix roadmap status of client-side sorting and filtering extensions

- content/pages/404.html
This adds a 404.html to the root of the content directory by overriding the rule in content/pages/_blueprint.yaml : Firebase requires /404.html in the content root; previous rule results in a /404/ directory being created.
> Add 404.html to content root by overriding blueprint configuration (Issue #258)

- assets/sass/_lang_switcher.scss
- content/pages/404.html
- content/pages/amp-conf.html
- views/partials/lang_switcher.html
Fixes #764 including:
- When click on text or any area in h6, lang switcher expands
- For AMP Conf page and 404 page where there was no localized langs the lang switcher shifted;
Intended behavior: cannot collapse lang-switcher if click off it. As we are using an accordion, and it's not an actual drop-down.
> Fix lang switcher click target and shifting

- content/docs/tutorials/add_advanced/adding_carousels.md
- content/docs/tutorials/add_advanced/adding_carousels@es.md
- content/docs/tutorials/add_advanced/adding_components@es.md
- content/docs/tutorials/add_advanced/congratulations.md
- content/docs/tutorials/add_advanced/congratulations@es.md
- content/docs/tutorials/add_advanced/fonts.md
- content/docs/tutorials/add_advanced/fonts@es.md
- content/docs/tutorials/add_advanced/navigating.md
- content/docs/tutorials/add_advanced/navigating@es.md
- content/docs/tutorials/add_advanced/review_code@es.md
- content/docs/tutorials/add_advanced/setting_up@es.md
- content/docs/tutorials/add_advanced/tracking_data.md
- content/docs/tutorials/add_advanced/tracking_data@es.md
Thanks to @calebcordry - amp-fit-text script should be added before component used; turns out the topics weren't in correct order, that is, "Adding carousels" should come *after* "Adding extended components".
> Fix order of topics in tutorial

- content/docs/tutorials/interactivity/get-familiar.md
Link currently points to `amp-form` instead of `amp-selector`. Spanish version was already correct.
> change amp-selector link typo

- content/docs/guides/pwa-amp/amp-as-pwa@es.md
- content/docs/guides/pwa-amp/amp-as-pwa@id.md
- content/docs/guides/pwa-amp/amp-as-pwa@ja.md
- content/docs/guides/pwa-amp/amp-as-pwa@ko.md
- content/docs/guides/pwa-amp/amp-as-pwa@pt_BR.md
- content/docs/guides/pwa-amp/amp-as-pwa@zh_CN.md
Six translations (ja, es, ko, id, pt-BR, zh-CN)
> Translations for "Enable Progressive Web App features for your AMP pages"

- content/docs/tutorials/visual_story/animating_elements.md
I think this section was meant to highlight the "animate-in-delay" on all amp-imgs, but it currently highlights one line earlier in each amp-img.
https://www.ampproject.org/docs/tutorials/visual_story/animating_elements
> Fix the lines that are highlighted on the animate-in-delay step of the story tutorial

- scripts/import_docs.js
Fixes #872 
Ran comparison by turning off logic to change relative links for extensions and there's only two affected docs.  Rather than have breaking links, I'll leave absolute URLs as they are, but will fix links to components in the two docs.
1) Fix links in spec for "amp-form"
2) Fix link in amp-ad for amp-ima-video
> Remove logic for changing abs links to rel links for extensions

- gulpfile.js
- package.json
This PR replaces the deprecated `getFileManifestEntries` with `getManifest`. It also switches back to the latest versions of `workbox-build` and `workbox-sw`
Follow up to https://github.com/ampproject/docs/commit/18245baeca833e6cfc4dbf7c39aff7ca6adfc567
Fixes #878
> Fix build by replacing getFileManifestEntries with getManifest

- content/docs/fundamentals/add_advanced/adding_components.md
Because using `amp-ad` will throw an error soon if it is not imported as a custom component, I'm suggesting an early update to the tutorial.
Fixes #898
> Add instruction in tutorial to add `amp-ad` script

- scripts/import_docs.js
Fix regex syntax so mustache code syntax can render correctly in Grow.
Performed diff and expected changes rendered.
Expect to render these inline code elements correctly: `<{{tagName}}>` and `<div {{attrName}}=something>` and `{{{unescaped}}}`.
fixes: #903
> Fix regex for mustache code syntax

- content/docs/contribute/file-a-bug.md
- content/docs/contribute/github.md
- scripts/import_docs.json
Removing "GitHub" and "File a bug" links from docs side nav; it's not needed and may confuse readers.  Details for filing bugs or contributing already in the "How to contribute" doc.
> Remove unnecessary sidebar links

- assets/sass/_content.scss
H6 font size is too small ([example](https://www.ampproject.org/docs/reference/components/amp-date-picker#template-definition-objects).
> h6 too tiny

- .travis.yml
- build_scripts/check-package-manager.js
- package.json
- yarn.lock
This PR does the following:
- Locks down the versions in `package.json` so that upgrades to dependencies cannot break the build
- Updates `yarn.lock` with the result of running `yarn`
- Since caching is already enabled for `yarn` on Travis, the install step during Travis builds will be much faster
- Adds a new script `build_scripts/check_package_manager.js`, which is run prior to the installation of packages.
- Detects and prints the versions of `node`, `yarn`, and `grow`
- Suggests upgrades if `node` is not LTS, or if `yarn` is not stable, or if `grow` is not latest
- Makes sure that `yarn` is being used to add / install packages during local development
- Fails the install and prints a useful message if `npm` is run instead of `yarn`
Fixes #894
> Update and lock down package versions used by `ampproject/docs`

- assets/sass/_content.scss
- assets/sass/_tables.scss
- Fixes #988 - Change table SCSS so that table doesn't scrunch when mobile, it wraps and is scrollable 
- tested on numerous docs - guides, tuts, and ref docs
- Improve alignment wrapper for images so they don't appear massive on tablet viewport widths, only use width auto for mobile widths (460px and less). Tested in PWA guide and tutorials.
> Fix table wrapping + figure images

- views/partials/promo_banner.html
Updates the main page banner to point to the AMP Contributor Summit instead of AMP Conf.
I tested on desktop and on simulated mobile devices in Chrome.  It's a bit tight on mobile, but it generally works.
> Update main page banner to point to AMP Contributor Summit instead of AMP Conf

- content/docs/design/responsive_amp/style_pages.md
- content/docs/interaction_dynamic/amp-email-format.md
Inline styles are now allowed in the AMP validator. They share the same 50KB limit as `<style amp-custom>`. 
We probably should also add some language to https://www.ampproject.org/docs/design/responsive_amp#add-styles-to-a-page.
I'm not sure if there are other places in the docs that reference this. Please update those too! 
/to @bpaduch
> Allow inline styles

- content/docs/fundamentals/converting/resolving-errors@ja.md
Leftover changes from the previous PR: https://github.com/ampproject/docs/pull/1023
1) Row 117 – updated code to use EN not JA
2) Row 164 – updated code to use EN not JA
3) Row 303 – fixed the heading 1 issue (i.e. "h1 {")
> Updated a few code issues

- content/docs/analytics/analytics-vendors.md
This PR adds Mobify to the amp-analytics provider list.
This addresses #1058
> Add Mobify to list of supported analytics vendors

- content/docs/design/responsive_amp.md
- content/docs/fundamentals/converting/resolving-errors.md
- content/docs/getting_started/create/presentation_layout.md
AMP now allows inline style attributes in HTML. This request adds this as an option to documentation. 
Contributes to issue #1027
> Updated documents to include inline styling 

- content/docs/analytics/analytics-vendors.md
Surfaced during translation requests that offer ID was already translated into ID.
> Updated word from "Angebotskennung" to "offer ID"

- translations/ko/LC_MESSAGES/messages.po
The menu text for "Advertising" is translated to "광고하는" in KO, which doesn't make sense without an additional noun. The current form is an adjective that expects a noun at the end which is missing. So it looks incomplete. 
Instead, it should be good to make it as "광고" as a noun. Yes, it's the same meaning with "advertisement", but in this case, it's better and it works.
> Improve KO translation for a menu text.

- content/docs/analytics/analytics-vendors.md
Fixes #1101 
Google AdWords had been rebranded, so this change needs to be reflected across the site. I'm adding in Google Tag Manager for a discussion about how to incorporate it here. Unlike other vendors, it doesn't have a type attribute to set, you simply paste in what GTM gives you, such as:
<amp-analytics config="https://www.googletagmanager.com/amp.json?id=GTM-T5FMS6S&gtm.url=SOURCE_URL" data-credentials="include"></amp-analytics>
Does it fit on this page? If not, where should it go? The ability to use GTM in AMP should be less difficult to discover.
> Added Google Tag Manager links to vendors, changed AdWords to Google Ads

- content/docs/getting_started/visual_story/congratulations.md
amp-story is no longer on origin trials. The notes have been removed by https://github.com/ampproject/docs/pull/1079.
> Remove Orgin Trial information from amp-story.

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/seatmap.md
This adds an AMP seatmap guide implementation.
I wasn't able to get the code snippet to proper render, it contains some server side code such as {{#name of the variable}} which I don't know how to escape.
I tried with 
`{% raw %}{{#name of the variable}}{% endraw %}` but it still doesn't work, I think because it's not inside an html tag. (you can take a look at the code to see what I exactly mean)
@pbakaus @CrystalFaith any idea how to fix this in grow.io?
> Add seatmap guide

- examples/source/advanced/Favorite_Button.html
- package.json
- pages/content/amp-dev/offline.html
- platform/lib/build/samplesBuilder.js
- platform/lib/pipeline.js
- If Grow had errors during rendering the process exits with error code now and hinders deployment
- The CLI argument to start import is passed correctly to the script
- Samples builder always builds freshly for a complete build
- Samples builder skips samples marked as draft
- `Favorite_Button.html` has been marked as draft as it uses a mustache template that breaks jijnja2 - this needs to be escaped in the Samples Builder but I don't want to break other things with a rushed RegEx now
Local test build is currently running, I'll give you a hint if it worked.
> Fixes for build

- platform/config/podspec.yaml
Uncomments languages in the podspec template. Through this change all language versions are built when performing a build.
> 🔧 Enable all languages to be built

- platform/config/environments/production.json
- playground/src/document/controller.js
- playground/src/editor/editor.js
- playground/webpack.config.js
Two important fixes:
1. Use the appspot domain for embeds (serves the same content as amp.dev)
2. Avoid that homepage jumps to playground
> Playground fixes

- frontend/scss/components/molecules/rolling-formats.scss
- frontend/templates/views/partials/rolling-formats.j2
This should get rid of the extra space in front of the rolling-formats on the homepage 😉
> 💄 Decrease space in front of rolling formats

- frontend/scss/components/organisms/kpi-list.scss
Kpi list was unscrollable across success stories and other pages that used the organism. The issue is fixed with an overflow scroll feature, but should be replaced in the future with amp-carousel if/when a responsive layout is supported by the carousel type. Should solve the first issue in #1548
> 🐛 kpi list scrolling issue

- frontend/scss/components/organisms/resources-grid.scss
- frontend/templates/views/partials/resources-grid.j2
- pages/content/amp-dev/documentation/guides-and-tutorials/index.ads.html
- pages/content/amp-dev/documentation/guides-and-tutorials/index.email.html
- pages/content/amp-dev/documentation/guides-and-tutorials/index.html
- pages/content/amp-dev/documentation/guides-and-tutorials/index.stories.html
- pages/content/amp-dev/documentation/guides-and-tutorials/index.websites.html
- platform/lib/routers/pages.js
This PR currently:
- Fixes the bug that manually filtered variants arent respected
- Puts the resources grid further up in the structure
- Fixes content errors in the introduction texts of the manually filtered pages
> Perf documentation landing pages.

- examples/source/components/amp-recaptcha-input.html
This creates an example for the upcoming `amp-recaptcha-input`. However, this requires a backend, and is currently using [my glitch AMP recaptcha endpoint](https://glitch.com/edit/#!/torch2424-amp-glitch-express). Waiting for some direction on how to implement this in this project's express server
cc @sebastianbenz
* Want me to open a PR in ABE as well? If anything, I can leave the ABE on glitch, and then write the glitch endpoint here?
* The experiment blurb was written by me. Please let me know if there is a new way of handling this. (The old way from ABE didn't work).
> Created an amp-recaptcha-input example

- frontend/scss/components/molecules/teaser-component.scss
- pages/translations/en/LC_MESSAGES/messages.po
- platform/lib/build/pageMinifier.js
- platform/lib/common/filteredPage.js
- Skips component overview from selector rewriting
- Leaves "All" filter intact
- Correctly removes non-format-matching teasers
- "Translates" category names for components
> 🐛 Fix various glitches around component overview.

- frontend/templates/views/partials/burger-menu.j2
... at the same time this hardcodes the sections for the burger menu as in `header.j2` - that saves one query for all collections and probably already improves build times.
> 🐛 Add missing blog link in burger menu.

- content/docs/analytics/analytics-vendors.md
✨  Add [Kenshoo](https://kenshoo.com/)  documentation to the supported Analytics Vendors docs.
> Add Kenshoo analytics service documentation

- frontend/templates/views/partials/toc.j2
> 🐛 Correctly check if document should have a TOC.

- platform/lib/platform.js
- platform/lib/routers/pages.js
This fixes the 404 handler being called after serving a page.
> Don't call next() after serving a page

- frontend/templates/views/partials/header.j2
Grow's API is not consistent, therefore the monkey-patch didn't affect that edge case.
> 🐛 Do not use doc.public_path in language selector.

- frontend/scss/components/molecules/table.scss
When assets were added to table cells, some assets were smaller or larger than intended to be due to styling across all table cells. This is now fixed with a set width for table cells and the table
> 🐛 fix table cells for responsive assets

- frontend/scss/components/molecules/tip.scss
I took out the `margin-bottom:0`. But then I added that for the last paragraph, so that the spacing only exists _between_ paragraphs.
The only thing that may be undesirable is that sometimes content in notes on amp.dev is surrounded by a blank `<p>` or two. With my change, each `<p>` now has a margin. So the whitespace in the note grows.
Fixes #1685 .
> Create spacing between paragraphs inside notes

- frontend/scss/components/atoms/text.scss
Remove the rule that gives `<ul>` and `<ol>` `font-size:0.875rem;`
This would close #1684
> Don't put text in lists in a smaller font size.

- firebase.json
Copied the rules for requests without a language, though can't see why https://www.ampproject.org/amp-conf/ has gone to https://amp.dev/events/amp-conf instead of https://amp.dev/events/amp-conf-2019.
Can you spot the error?
> 🐛 Add redirect rules for language independent requests

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/login_requiring/index.md
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/index.md
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/monetization/index.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp.md
There have been differences between the i18n documents and the default ones which broke redirects.
> 🐛 Dissolve differences between i18n paths and globals

- firebase.json
- The order the rules are currently in is crucial, it only works that way - no idea why.
- Wild-card rules with a destination not ending on `/` can't have a query parameter - Firebase swallows the question mark. We could either configure amp.dev's express to have a trailing slash, or expand the rules here to the specific paths
- ampprojects.org Firebase instance needs to have set `trailingSlash` to true to consequently follow the rules.
The rules have been automatically tested against the staging instance (https://ampproject-staging-cbdb3.firebaseapp.com/) and successfully cover the rules as in the [spreadsheet](https://docs.google.com/spreadsheets/d/1LObaBqtxnSaxCdoJontTxGDfKyWAEYaFn__pcNLctFk/edit#gid=0). Manual/visual testing is pending.
> 🐛 Update redirect configuration pointing to amp.dev

- pages/content/amp-dev/documentation/guides-and-tutorials/start/_blueprint.yaml
> 🐛 Add missing extension to Start collection.

- platform/lib/routers/pages.js
Local format filtering is broken as `fixCheerio` gets the cheerio instance instead of an HTML string. Additionally due to the URL change the lookup for manual filtered variants didn't work.
> 🐛 Fix local format filtering.

- examples/api/hello.js
- examples/api/photo-stream.js
- package-lock.json
- package.json
- Images in `api/photo-stream` now use HTTPS
- Titles in `api/photo-stream` are now generative as well
- `api/photo-stream` now supports image sizes (and other parameters are better sanitized)
- Added `api/hello` endpoint to test forms
> Use https for photo stream, create hello endpoint

- frontend/scss/components/molecules/tip.scss
Safari has performance issues with rendering `filter: drop-shadow` in certain cases. Replaced it with `box-shadow` which doesn't respect the tip's special shapes but at least renders smoothly.
> ⚡️ Use box-shadow instead of drop-shadow for tip

- frontend/scss/components/molecules/format-toggle.scss
- frontend/scss/components/molecules/language-selector.scss
- frontend/scss/components/organisms/header.scss
- frontend/scss/components/templates/_default.scss
- frontend/templates/views/partials/header.j2
Handling one of the most prominent answers from the beta form: the flyout navigation and the format toggle is now fully keyboard accessible and are built without any `input` hacks.
This also leads to the discussed change that the top level navigation items that have a flyout aren't clickable on their own anymore.
> ♻️ Make header keyboard accessible.

- examples/source/1.components/amp-pinterest.html
`data-do` should be `embedPin` and not `embedPing`
> Typo fix in embed pin widget doc

- pages/content/shared/footer.html
- pages/content/shared/header.html
This would make header and footer accessible via http://amp.dev/shared/header.html and http://amp.dev/shared/footer.html.
See the attached documents for reference, the final endpoints would be minified though.
Including [`base.scss`](https://github.com/ampproject/docs/blob/future/frontend/scss/base.scss) can possibly be omitted as you might have similar stylings for the blog in place already
[sample.zip](https://github.com/ampproject/docs/files/3061245/sample.zip)
.
> ✨ Make header and footer available standalone.

- .dockerignore
- .gcloudignore
Fixes #1865.
We could possibly handcraft better ignore rules but I fear that they then don't match all upcoming cases and produce similar errors again. Therefore I went for unignoring the `/example/source` at all.
> 🙈 Unignore files in /examples/source/.

- frontend/templates/layouts/default.j2
- pages/extensions/amp_dev/extension.py
- pages/extensions/amp_dev/markdown_extras/block_filter.py
Fixes #1748.
```markdown
[filter formats="websites"]
This is only visible for [websites](?format=websites).
[/filter]
[filter formats='websites, email']
This is visible for [websites](?format=websites) & [email](?format=email).
[/filter]
[filter formats="stories"]
This is visible for [stories](?format=stories).
[/filter]
```
> ✨ Add shortcode for format filtering.

- frontend/templates/layouts/default.j2
- frontend/templates/views/partials/breadcrumbs.j2
- frontend/templates/views/partials/structured-data.j2
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/_blueprint.yaml
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/_blueprint.yaml
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/_blueprint.yaml
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/_blueprint.yaml
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/_blueprint.yaml
- pages/content/amp-dev/documentation/guides-and-tutorials/start/_blueprint.yaml
Scopes title tag to make it more easy to identify tabs and prevent double titles in regards to SEO. 
And adds the parent collection's title to the Guides breadcrumbs
> ✨ Small UX improvements.

- examples/source/1.components/amp-social-share.html
Remove references in docs to gplus in amp-social-share. #1894
> Remove gplus from amp-social-share

- frontend/scss/components/molecules/teaser-example.scss
teaser examples had an incorrect aspect ratio for the images, this is fixed by adjusting the padding to 9/22 #1815
> 🐛 fixe aspect ratio for teaser examples

- frontend/scss/components/molecules/rolling-formats.scss
Safari triggers rolling animation sooner than other browswers on inital page load, adding an inital animation delayprevents text from overlapping #1898
> 🍏  fix text overlap for rolling animation

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity_data/using_javascript.md
- pages/content/amp-dev/events/amp-conf-2019.html
- pages/content/amp-dev/events/amp-conf-2019@ja.html
Just that we are not facing similar trouble as this morning tomorrow 🙂 
This updates the AMP Conf page to show the livestream for Day 2 and adds a CTA to watch the recording of Day 1. (There possibly is a better term than "Recap")
Video-IDs used for the Day 2 Streams: `3j540p3GxvE` (EN) and `DpEPnOkiVLs` (JA).
Additionally this adds a description to the newly added `amp-script` guide for better sharability and SEO.
Feel free to comment further changes that are needed for tomorrow.
> 💬 Update amp.dev for AMP Conf Day 2.

- frontend/templates/views/partials/format-visuals/ads.j2
- frontend/templates/views/partials/format-visuals/email.j2
- frontend/templates/views/partials/format-visuals/stories.j2
- frontend/templates/views/partials/format-visuals/websites.j2
While doing the live quickcheck I just noticed that the dependency injector adds the unused extensions `amp-ad`, `amp-sidebar` to the homepage.
This strangely isn't picked up by the validator.
> 🐛 Stop injecting unused deps into home.

- pages/content/amp-dev/events/amp-conf-2019.html
- pages/content/amp-dev/events/amp-conf-2019@ja.html
This updates the page for when conf is over and adds sliders for all the highlights.
Let me know which highlights we want to feature! We might probably also want to change the banner text ("AMP Conf 2019. April 17/18. Tokyo.") to something more encouraging to watch the talks but I can't come up with something catchy...
> 💬 Prepare AMP Conf 2019 page for after conf.

- gulpfile.js/deploy.js
- platform/lib/utils/sh.js
Not to sure if this makes sense: to prevent something similar as this morning happening we could append the current timestamp to build tags. Otherwise creating a new build based on the same commit without giving an explicit tag wouldn't be possible.
> 🎨 Verify release tag prior build.

- platform/lib/middleware/subdomain.js
URLs starting with `/static/` should always be treated as site root requests.
> Fix incorrect condition

- platform/lib/platform.js
- platform/lib/routers/pages.js
There was a bunch of things that were a little fishy with the development setup: `_configureDevMode` was called twice, which was the reason for the port already in use message, but additionally the server that has been started by it isn't needed anymore as all things needing CORS requests now have dedicated servers. The sample previews are served from `[10:16:29] › ℹ  info      preview dev server listening on 8084` for example.
The other thing that was broken is that the actual pages router for development was implemented as a middleware while it should have been a router (`use`/`get`). With the included changes `npm run develop` now works fine for me again.
> 🐛 Fix development setup.

- examples/source/0.introduction/Stories_in_AMP.html
mp4 video path was incorrect inside amp-video component. closes #1998
> 🐛 fixed broken link for stories video

- pages/content/amp-dev/documentation/templates/multi_image_ads.yaml
The "Multiple Image" Story Ads template at https://amp.dev/documentation/templates/ can't actually be downloaded, because there's no `href` property on the `<a>`. This is probably why…
> Make "Multiple Image" story ad template zip downloadable

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/art_direction.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes.md
Updated documentation to clarify the difference between `sizes` in HTML5 and `sizes` in AMP. Fixes issues #1997.
> Updated sizes attribute documentation

- package-lock.json
- pages/translations/es/LC_MESSAGES/messages.po
Somehow the encoding for two characters in the spanish messages got messed up.
Problem shows in the breadcrumb and footer:
https://amp.dev/es/documentation/guides-and-tutorials/
> Fix some special characters in the es messages

- platform/config/amp-dev-redirects.yaml
- platform/config/go-links.yaml
- platform/lib/middleware/redirects.js
https://github.com/ampproject/docs/issues/2008
Initial shortcuts:
/ads: /about/ads
/docs: /documentation/guides-and-tutorials/
/email: /about/email
/learn: /documentation/courses/
/samples: /documentation/examples/
/stories: /about/stories
/websites: /about/websites
Also correct an invalid go.amp.dev link
> Support configured redirect links at amp.dev

- platform/lib/pipeline/markdownDocument.js
Fixes #2071.
https://github.com/ampproject/docs/blob/67a6ee7fe13caafa373866d9e3f3a6f2d8903bdd/platform/lib/pipeline/componentReferenceImporter.js#L112-L114
`document.formats` has always been `undefined` before.
> 🐛 Add missing getter for formats to MarkdownDocument

- examples/source/multimedia-animations/Supported_media_types_in_AMP_Stories.html
the amp-audio sample in the documentation was invalid do to only partial support for the amp-audio component in stories. A better reference for adding audio to stories is the background-audio attribute.  fixes #1846
> 🐛 fixed broken reference to amp-audio

- examples/lib/SampleRenderer.js
- pages/content/amp-dev/message.html
- platform/config/environments/development.json
- platform/config/environments/production.json
- platform/config/environments/staging.json
- platform/lib/platform.js
- platform/lib/routers/runtimeLog.js
- platform/lib/runtime-log/formatter.js
- platform/lib/templates/index.js
* adds a new endpoint for the log.amp.dev subdomain.
* moves server-side templates into a helper class
The actual log formatting is not yet implemented. See #2051.
> Setup runtime logging endpoint

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp@ko.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp@zh_CN.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/create_email.md
A more correct fix would be to consistently use `g.doc(...)` in the changed documents, but I'd rather let one of our assistants reverse-match the absolute URLs to their file paths.
`documentation/guides-and-tutorials/learn/amp-email-format.md` is imported from ampproject/amphtml and blocked by ampproject/amphtml/pull/22044.
Fixes #2077.
> 🐛 Use correct URL scheme for component docs.

- pages/extensions/amp_dev/extension.py
- pages/extensions/url_beautifier/__init__.py
- pages/extensions/url_beautifier/url_beautifier.py
- platform/config/podspec.yaml
This change should render the tips usable again in your local setup, @CrystalOnScript and @pbakaus, without installing Grow via `pip`.
Remembering the debugging information I've got from Sebastian code execution just stopped for your environments when we tried to apply the URL monkey patch - but went fine otherwise. No exception whatsoever.
By moving the URL rewrite to a dedicated extension it can (and most probably still will) fail silently while the `AmpDevExtension` responsible for rendering the tips runs flawlessly.
But I'll also try to propose a canonical way of configuring paths to the Grow team again, making this extension obsolete.
> ♻️ Move Grow URL rewrite to dedicated extension

- frontend/scss/components/molecules/rolling-formats.scss
Resolves #1898. As the error isn't deterministic at all this change just sets the default animation state for the rolling animation. This way even if the animation doesn't start it won't look broken on Safari.
> 🍎 Set default state for rolling formats animation.

- firebase.json
Fixes #2100 by disabling the `trailingSlash` option in firebase and manually remove all trailing slashes in the redirect rules which nevertheless match both `/source-url` and `/source-url/`.
> 🔧Update ampproject.org redirects to fix inline samples.

- examples/api/amp-inputmask.js
- examples/source/1.components/amp-inputmask.html
- examples/source/interactivity-dynamic-content/Paged_List.html
Migrated the backend/amp-inputmask.go from ampbyexample.com to amp.dev.
I fixed the examples and updated the second example to match its headline.
> ♻️ Migrate amp_inputmask backend API

- examples/api/autosuggest.js
- examples/source/interactivity-dynamic-content/Autosuggest_form.html
Migrated the backend/autosuggest.go from ampbyexample.com to amp.dev.
This fixes the example on https://amp.dev/documentation/examples/interactivity-dynamic-content/autosuggest_form/.
> ♻️ Migrate autosuggest API to amp.dev

- examples/source/interactivity-dynamic-content/Favorite_Button/api.js
- examples/source/interactivity-dynamic-content/Favorite_Button/index.html
- package-lock.json
- package.json
Migrated the backend/favorite.go from ampbyexample.com to amp.dev.
This fixes the example on https://amp.dev/documentation/examples/interactivity-dynamic-content/favorite_button/.
> ♻️ Migrate favorite button API to amp.dev

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads.md
Clarified that this type of integration is not required to serve AMPHTML ads on non-AMP pages.
> Added ad integration clarification 

- gulpfile.js/build.js
- platform/lib/build/samplesBuilder.js
- The reason while the sample sitemap isn't existing on staging is that `finalizeBuild` collected the static files before the build artifacts had been extracted
- Additionally subsequent calls of `gulp buildSamples` only did write partial sample sitemaps - therefore an existing sample sitemap is not overwritten anymore
> 🐛 Correctly handle multiple sample builds

- gulpfile.js/build.js
- gulpfile.js/develop.js
- platform/lib/utils/grow.js
- platform/lib/utils/sh.js
Problem was, that the grow installation without pip does not put grow in the path, but specifies an alias to ~/bin/grow. This is not available when calling "grow" via node.
* Extra lib for grow to add ~/bin to the path
* To suport blanks in parameters sh can now be called with an array
> Add ~/bin to path for grow exec

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/control_layout.md
This was misleading. Both `width` and `height` are needed for `layout="fixed"`.
Demo: https://jsbin.com/rujipoh/6/edit?html,console
> Style and layout: Updated auto-layout table

- README.md
- gulpfile.js/build.js
- gulpfile.js/develop.js
- Gulp just fails dead-silent if the second argument to `gulp.watch` is not a valid callable which was our case as `sass`, `icons` and `templates` had never been exported from `build.js` - finding this took me longer than I'd like to admit
- Coming from the feedback in #welcome-contributors on Slack I had the feeling it might be helpful to make it clearer which port you should actually access.
> 🐛 Improve DX for local environment

- examples/static/samples/standalone/amp-website/index.html
The default value for input fields is 1 and the default sum is also 1, creating misinterpretation. Since the initial value for Amp state, a and b is not set it is better we keep 0 for input fields.
> changed default input values and sum for calcultor

- examples/static/samples/files/resizable-iframe.html
- platform/lib/build/samplesBuilder.js
- platform/lib/platform.js
- platform/lib/routers/example/static.js
Before, preview.amp.dev would redirect all static
files to amp.dev. Now, preview.amp.dev directly
serves these without a redirect. This will fix the amp-iframe
resizing sample as the embedded iframe is now truly hosted
from a different origin (instead of redirecting...).
This commit also fixes the resizable iframe embed to also set the
height.
Fixes #2115
> Don't redirect static files to amp.dev

- platform/lib/utils/git.js
... otherwise `whoAmI.build.commit.message` on prod would always hold "Merge branch 'future' into production-amp-dev".
> 🚸 Use last non-merge commit message for build info

- .travis.yml
- Moves authentication from `before_install` phase to `script` phase as its only needed there. Otherwise all PRs coming from forks would always fail as they don't have access to the encrypted environment variables
- Adds job type check to stage conditions: `type != pull_request`
- Early exits the preparation stage if the build is a PR or isn't coming from `future`
> ♻️ Refactor travis conf to fix unintended builds

- boilerplate/build.js
- boilerplate/lib/templates.js
- boilerplate/templates/index.html
- boilerplate/templates/styles/main.scss
* remove ampbyexample references
* fix canonical
* don't generate second amp page
* fix amp-list not being displayed (workaround for
https://github.com/ampproject/amphtml/issues/22552).
> Various boilerplate generator fixes

- gulpfile.js/build.js
- package-lock.json
- pages/static/robots/prod.txt
Fixes #2218, the sitemap for Grow is currently missing. Not quite sure how crawlers picked up shared pages in the first place as both header and footer have
```yaml
$sitemap:
enabled: false
```
in their frontmatter. Therefore added `Disallow: /shared` to the production robots.txt
>  🐛 Copy sitemap when building pages.

- frontend/templates/layouts/default.j2
- frontend/templates/views/examples/documentation.j2
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/optimize_amp.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@es.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@id.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@ja.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@ko.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@pt_BR.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/fonts@zh_CN.md
See https://github.com/ampproject/docs/issues/2207 for context. I noticed that `font-display: swap` was already in place in our CSS, which should I think work for us.
/cc @cramforce
> Remove amp-font from amp.dev, and don't recommend its usage any longer

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md
Fixes #2175. Allows component documentation pages from ampproject/amphtml to have either `experimental` and/or `origin_trial` in their frontmatter to get then listed on the [experiments page](https://amp.dev/documentation/guides-and-tutorials/learn/experimental).
Open for suggestions to rename the frontmatter keys but I thought we might need differentiation as not every experimental component is available as an original trial.
Additionally I moved "There is a risk that some experiments will never ship as features on the AMP Project." to the top of the page because I found that bit quite important 😉 
@CrystalOnScript, please feel free to give copy feedback!
> ✨ List experiments on experiments page

- package-lock.json
- package.json
- platform/lib/config.js
- platform/lib/utils/credentials.js
This adds a credential helper to get API credentials from either an environment variable or a Google Cloud Datastore. Usage as follows:
```js
(async () => {
console.log('Trying to get environment credential ...');
await get('GOOGLE_MAPS')
.then((credential) => { console.log(`GOOGLE_MAPS: ${credential}`); })
.catch(() => { console.log('No key named GOOGLE_MAPS.'); });
})();
```
When exporting credentials as environment variables they need to be prefixed with `AMP_DEV_CREDENTIAL_` - in the above example the credential would have been exported by
```bash
$ export AMP_DEV_CREDENTIAL_GOOGLE_MAPS="secure-api-key"
```
> ✨ Add credentials util.

- examples/api/amp-form.js
- examples/source/1.components/amp-analytics.html
- examples/source/1.components/amp-autocomplete.html
- examples/source/1.components/amp-date-picker.html
- examples/source/1.components/amp-form.html
- examples/source/interactivity-dynamic-content/Conference_Survey_Email.html
- examples/source/interactivity-dynamic-content/Multi_Page_Flow.html
- examples/static/samples/files/amp-form-success.html
Migrated the backend/amp-form.go from ampbyexample.com to amp.dev.
This updates and/or fixes the examples [here](https://amp.dev/documentation/examples/components/amp-analytics/), [here](https://amp.dev/documentation/examples/components/amp-autocomplete/), [here](https://amp.dev/documentation/examples/components/amp-date-picker/), [here](https://amp.dev/documentation/examples/components/amp-form/), [here](https://amp.dev/documentation/examples/interactivity-dynamic-content/conference_survey_email/?format=email) and [here](https://amp.dev/documentation/examples/interactivity-dynamic-content/multi_page_flow/).
> ♻️ Migrate amp-form API to amp.dev

- examples/source/advertising-analytics/Doubleclick_AMP_Story_Ads.html
- examples/source/multimedia-animations/Supported_media_types_in_AMP_Stories.html
- examples/source/style-layout/AMP_Story_Layouts.html
- examples/source/user-consent/Story_User_Consent.html
- examples/source/visual-effects/AMP_Story_Animations.html
- examples/source/visual-effects/Ken_Burns.html
change the bookend-link. It is working again. Except for Doubleclick, Publisher and User Consent where only the Demo is working.
> 🐛 Bookend in AMP Story samples are back

- jest.config.js
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/_blueprint.yaml
- platform/config/amp-dev-redirects.yaml
- platform/lib/config.js
- platform/lib/middleware/redirects.js
- platform/lib/middleware/redirects.test.js
Fixes https://github.com/ampproject/docs/issues/2261
**Improve redirect logic:**
Before the redirect mapping did only look for the complete path
and redirected to the target when a complete match was found.
Now we also look for the path without the locale path and use the locale for the redirect.
We also append the original query parameters to support the format=websites param
That means the shortcuts amp.dev/es/docs would work
> Align path "optimize-and-measure" and improve redirect logic

- examples/source/1.components/amp-video.html
https://amp.dev/video/tokyo.m3u8 is a 404.
> Fix the <amp-video> HLS sample

- platform/lib/routers/pages.js
- platform/lib/routers/pages.test.js
- platform/lib/routers/static.js
The sitemap.xml which is mentioned in the robots.txt results in a 404
https://amp.dev/sitemap.xml
Also the grow generated sitemap is not served.
https://amp.dev/sitemap_grow.xml
This PR fixes those issues.
> Fix sitemap 404

- gulpfile.js/build.js
- package.json
- platform/lib/config.js
The grow test contents should not be deployed on prod.
We simply exclude the path /tests/ in the grow build.
On staging the files will still be available:
https://amp-dev-staging.appspot.com/tests/examples/import
> Do not build grow tests for production

- frontend/scss/components/molecules/code-snippet.scss
This PR fixes a problem with code snippets on screens smaller than 1024 pixel (The code runs out of the dark backround):
https://amp.dev/documentation/examples/visual-effects/basics_of_orientation_effects/?format=websites
> Fix code snipped running out of background container

- frontend/scss/components/molecules/code-snippet.scss
- frontend/scss/components/organisms/code-preview.scss
- playground/src/editor/editor.scss
fix #2284 remove background-gradient from code-snippets and add background-color: color('ebony-clay') in order to optimize reading
> 💄Remove gradient from code-snippets

- examples/source/interactivity-dynamic-content/Article_Bookmark_Email/api.js
- examples/source/interactivity-dynamic-content/Article_Bookmark_Email/index.html
Migrated the backend/amphtml-email.go from ampbyexample.com to amp.dev.
This updates the example [here](https://amp.dev/documentation/examples/interactivity-dynamic-content/article_bookmark_email/?format=email).
> ♻️ Migrate amphtml-email API to amp.dev

- frontend/scss/components/atoms/sidebar-toggle.scss
- frontend/scss/components/molecules/format-toggle.scss
- frontend/scss/components/organisms/component-sidebar.scss
- frontend/scss/components/organisms/sidebar.scss
- frontend/scss/components/templates/component-overview.scss
This was caused by missing browser prefix.
Added it there and also everywhere else it was missing.
Also adjusted auto generated margin-top, which also only appeared in safari.
> Fix format-toggle dropdown-list too wide on safari 

- frontend/templates/views/examples/documentation.j2
Fixes two problems with playground links
- Sections in the head will have no section preview file, so the link should not be shown
- For section preview links a / was missing before the section id
Those problems can be seen here:
https://amp.dev/documentation/examples/components/amp-accordion/?format=websites
> Examples playground links: section separator + no link for head snippets

- platform/config/go-links.yaml
go.amp.dev/email-tools is currently the same as go.amp.dev/tools, but this will be updated when #2341 is fixed (I'm adding it now to link from slide deck).
> Add tools and email-tools redirects

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp@es.md
fixes #2343 in validate_amp@es.md page by removing a space between the link and link-description.
> ✏️ remove space in order to fix link

- examples/api/amp-access.js
- examples/source/1.components/amp-access.html
- examples/source/interactivity-dynamic-content/Comment_Section/index.html
- examples/static/samples/files/login.html
Migrated the backend/amp-access.go from ampbyexample.com to amp.dev.
This updates the example [here](https://amp.dev/documentation/examples/components/amp-access/?format=websites) and [here](https://amp.dev/documentation/examples/interactivity-dynamic-content/comment_section/?format=websites).
> ♻️ Migrate amp-access API to amp.dev

- platform/config/go-links.yaml
- platform/lib/routers/go.js
- platform/lib/routers/go.test.js
This PR allows `go-links.yaml` to have this syntax for "catch-all" redirects:
```yaml
/c/amp-([a-z-]+):
url: /documentation/components/amp-$1
useRegex: true
```
It also adds redirects for components (e.g. `go.amp.dev/c/amp-form`) and samples (e.g. `go.amp.dev/s/amp-form`) and closes #2182 and #1860.
> Allows go-links.yaml to have regex based redirects

- pages/content/amp-dev/about/email.html
Fixes #2368 empty link "send emails" on AMP Email page now links to the bottom of the page to "Start sending AMP Emails" section
> 🎨 Add a link and a section with id to repair stage link

- frontend/scss/components/organisms/help.scss
- frontend/templates/views/examples/documentation.j2
Fixes #2308 Change the class name of help-section in example template and edit styling in order to display the help section correctly.
> 🎨 Change class name of section in examples and add styling

- pages/extensions/jinja2_optimized_codehilite/custom_html_lexer.py
- pages/extensions/jinja2_optimized_codehilite/custom_js_lexer.py
- pages/extensions/jinja2_optimized_codehilite/jinja2_optimized_codehilite.py
- pages/extensions/jinja2_optimized_codehilite/readme.md
This improvement is needed to correctly handle jinja2 expressions in markdown code blocks with script tags like
```html
<script type="text/plain" template="amp-mustache">
Hello {% raw %}{{world}}{% endraw %}!
</script>
```
This code block is found here:
https://amp.dev/documentation/components/amp-mustache
> Improve support for jinja2 code in markdown source blocks

- CONTRIBUTING.md
- README.md
I saw that the CONTRIBUTING.md was not updated for the new repository layout.
Since the readme now has a section about contributing (which had a small typo), I did not want to repeat the things there and simply added a link to this section.
Since this file is linked by github in the "create issue" dialog I did not want do delete it.
> Fix typo and broken links in the contributing docs

- jest.config.js
- platform/lib/pipeline/markdownDocument.js
- platform/lib/pipeline/markdownDocument.test.js
The old logic to escape mustache expressions in markdown code blocks did not work well.
It could happen that the end of one code block and the start of an other where considered a code block, which caused problems by placing the {% raw %} tags wrong.
For example on the following page the link 'common attributes' is wrong:
https://amp.dev/documentation/examples/components/amp-img/#offline-fallback
This PR will fix this problem by searching for blocks and only in a second step escape the markup.
Also existing {% raw %} blocks are taken into account.
Additionally source blocks with [sourcecode] tags are supported.
Therefore the escaping logic in the `rewriteCodeBlocks` function could be removed.
Together with this the jest library and test lookup was fixed.
> Fix mustache escaping in markdown and fix unit test lookup

- pages/extensions/amp_example_preview/util/example_extractor.py
- pages/extensions/amp_example_preview/util/example_extractor_test.py
- pages/extensions/amp_example_preview/util/preview.py
Needed to support the imported amphtml documents, where the code blocks are converted to [sourcecode] tags
> Support inline preview for examples with [sourcecode] tags

- examples/source/1.components/amp-date-picker.html
- frontend/scss/components/atoms/text.scss
fixes #2351 add styling (remove padding-left) for the static dayPicker in order to let the days appear in one row above the dates.
> 💄 Add styling to static DayPicker in examples

- examples/source/e-commerce/Housing/api.js
- examples/source/e-commerce/Housing/index.html
Migrated the backend/housing.go from ampbyexample.com to amp.dev.
It updates the example [here](https://amp.dev/documentation/examples/e-commerce/housing/?format=websites#mortgage-calculator).
> ♻️ Migrate housing backend to amp.dev

- frontend/scss/components/organisms/cities.scss
- pages/content/amp-dev/events/amp-roadshow.html
- pages/shared/data/roadshow.yaml
With this PR we can finally complete the roadshow map changes.
It adds an animation for the upcoming cities and also moves Berlin and Atlanta to the past cities list.
@morsssss I've added placeholder content to the nextstop list and commented it out, so it is easier to fill out the needed values.
> Add pulsing animation to upcoming cities on roadshow map

- platform/config/go-links.yaml
Temporary fix until #2180 is resolved.
Also changed from `go.amp.dev/s/...` to `go.amp.dev/e/...` since "**e**xample" makes more sense than "**s**ample" based on how we call them on the website. Open to discussion about that though.
> Add trailing slash for example redirect

- platform/lib/config.js
- platform/lib/config.test.js
We use a locale filter in the travis build, to be able to split the build on different machines.
This PR changes the whitelist filter to a blacklist filter, because a whitelist filter will only build those locales and no sitemap.
Fixes https://github.com/ampproject/docs/issues/2327
> Use blacklist to filter locales so that sitemap is not excluded

- pages/extensions/amp_example_preview/util/amp_component_versions.py
The fix for https://github.com/ampproject/docs/issues/2410 did not work for the python unit tests.
With this PR an absolute path is used to find the file.
> Fix component version path for unit tests

- platform/config/podspec.yaml
- platform/lib/pipeline/markdownDocument.js
- platform/lib/pipeline/markdownDocument.test.js
This addresses problems discussed in https://github.com/ampproject/docs/issues/1809 that sometimes markdown is not evaluated in table tags.
> Allow markdown in all table tags of imported documents

- platform/config/podspec.yaml
- platform/lib/pipeline/markdownDocument.js
- platform/lib/pipeline/markdownDocument.test.js
Reverts ampproject/docs#2434 temporarily as it breaks the rendering of [tip] for a reason I can't figure out quickly.
> 🚑 Revert allowance of markdown in all table tags of imported documents

- .travis.yml
- scripts/unbuffer.sh
Yesterday's staging build and tonight's production build should have never made it to the instances as building the pages finished with a non-zero exit code that is swallowed by `unbuffer`. Also see: https://superuser.com/questions/742121/unbuffer-swallows-the-exit-status-of-killed-process/805309#805309
> 🚑 Make unbuffer respect gulp's exit code

- pages/content/amp-dev/about/success-stories/washingtonpost.yaml
PDF link was incorrect, updating to correct file path
> Fixing WaPo case study

- pages/content/amp-dev/events/amp-cs-2019.html
A few quick edits before we launch the application:
- Updating the blurb to match our summary of the summit from the blog post
- Updating the FAQ to remove AMP Conf references & make it clear who the target audience for this summit is
- Updating the location to remove AMP Conf references
/cc @vishaldodiya
> Update AMPCS2019 page summary, FAQ and location

- pages/translations/en/LC_MESSAGES/messages.po
Re-adds "translated" strings for the category names for them to be properly formatted. Before:
After:
> 🌐 Add translations for category names

- platform/lib/build/samplesBuilder.js
-   Uses content override in abe added in ampproject/amp-by-example#2028 to speed up build
-   Replaces all calls to `then` and `catch` with `await`
-   Minor JSDoc fixes
> Replace promise handling with `await` in samplesBuilder.js

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/email_fundamentals.md
AMP for email is supported across multiple email providers, each with specific CSS rules and restrictions. Email senders should refer to email provider documentation for CSS specifics.
> Removed gmail specific styling information

- pages/shared/data/roadshow.yaml
I moved Sydney over a bit to accommodate Melbourne.
Note that this is the first case where we have a city twice... namely, Sydney. I hacked this by moving the old city Sydney up by a coordinate so that it would fit entirely beneath the new city Sydney. But we're going to have this problem a couple more times soon as we repeat two other cities.
> Adding Sydney and Melbourne to roadshow cities

- .travis.yml
Auto generated versions seem to result in hitting the services quota.
Let's try always using the same version.
> Fix staging deploy errors

- contributing/documentation.md
- contributing/samples.md
- platform/lib/build/samplesBuilder.js
-   Allows examples to use `filters:` frontmatter
-   Allows examples to filter sections using `@format` in the comments ([context](https://github.com/ampproject/docs/pull/2411#issuecomment-509748791))
-   Updates docs for frontmatter and formats
> Add filtering for AMP examples

- frontend/scss/components/molecules/event.scss
- frontend/scss/components/organisms/cities.scss
- pages/content/amp-dev/events/amp-roadshow.html
This fixes the duplicate city issue for the roadshow map.
A past-city will only be added to the map if it doesn't exist in the upcoming-city list.
Also this PR fixes the latest styling issue of the event boxes.
> Fix roadshow maps duplicate locations and event box styling

- frontend/scss/components/organisms/tools-teaser.scss
- frontend/scss/components/organisms/tools-widget.scss
- frontend/scss/components/templates/tools.scss
- frontend/templates/views/partials/tools-widget.j2
I seperated the styling of the tools elements: tools-template, tools-teaser, tools-widget.
This prevents the tools-widget (chosen tool-cards on the bottom of the about pages) from loading the complete css for the tools page, which was never used on the about pages. This is saving us round about 4.6 KB and should fix the css limit error on the about/ads page, see here #2561 
Furthermore I cleaned the code a bit and fixed some UI bugs like cropped box shadow and spacings etc.
No screenshot, because the look hasn't really changed.
> Refactor tools styling files to save bytes on the about pages (~4.6 KB)

- contributing/samples.md
- examples/source/0.introduction/Stories_in_AMP.html
- examples/source/e-commerce/AMP_for_E-Commerce_Getting_Started.html
- examples/source/style-layout/Desktop_and_Landscape_Mode_Support.html
- frontend/scss/components/organisms/code-preview.scss
- frontend/templates/views/examples/documentation.j2
* frontmatter can configure landscape mode for stories via `landscape:
true`
* don't hide story previews on mobile
* remove `media` attribute blocking SSR
* update contribution docs
Fixes 2562
> AMP Story landscape preview mode

- frontend/templates/views/partials/breadcrumbs.j2
- frontend/templates/views/partials/burger-menu.j2
- frontend/templates/views/partials/header.j2
- frontend/templates/views/partials/sidebar-toggle-button.j2
- gulpfile.js/develop.js
- pages/translations/ar/LC_MESSAGES/messages.po
- pages/translations/en/LC_MESSAGES/messages.po
- pages/translations/es/LC_MESSAGES/messages.po
- pages/translations/fr/LC_MESSAGES/messages.po
- pages/translations/id/LC_MESSAGES/messages.po
- pages/translations/it/LC_MESSAGES/messages.po
- pages/translations/ja/LC_MESSAGES/messages.po
- pages/translations/ko/LC_MESSAGES/messages.po
- pages/translations/messages.pot
- pages/translations/pt_BR/LC_MESSAGES/messages.po
- pages/translations/ru/LC_MESSAGES/messages.po
- pages/translations/tr/LC_MESSAGES/messages.po
- pages/translations/zh_CN/LC_MESSAGES/messages.po
I noticed that our UI is still embarassingly untranslated so I:
1. Created a "gulp extract" task to be able to extract new strings into messages.pot regularly
2. Made a lot of untranslated strings translatable
3. Ported some untranslated strings over from the original Japanese messages.po file to the new one (this also needs to be done for all other languages, but is outside of the scope of this PR).
> Add gulp extract task, extract new strings, improve JA UI translation

- pages/extensions/markdown_toc_patch/__init__.py
- pages/extensions/markdown_toc_patch/custom_toc_tree_processor.py
- pages/extensions/markdown_toc_patch/markdown_toc_patch.py
- pages/extensions/markdown_toc_patch/readme.md
- platform/config/podspec.yaml
Fixes https://github.com/ampproject/amp.dev/issues/2556 by removing all html tags from the headlines before using them in the TOC.
The markdown toc extension that is used by grow can not remove html tags in the TOC item names by itself. So we created a grow hook, that hooks into the markdown toc extension to perform this.
> Remove html from TOC item names

- frontend/scss/components/organisms/header.scss
I splitted the css block that handles all :hover, :focus and :focus-within properties of the flyout navigation, because edge doesn't supports the `:focus-within` prop.
By splitting this in two, edge stops ignoring the whole block and still reveal the flyout on :hover and :focus #2532
> 🐛 Fix not opening navigation dropdown on latest edge browsers

- frontend/templates/views/partials/structured-data.j2
Fixes #2491 The Docs pages for amp-components have < > in the title tag and get a new prefix Documentation/Example/Demo
> 🎨Change component docs title to Documentation and  add < > to title tag

- frontend/scss/components/atoms/sidebar-toggle.scss
- frontend/scss/components/molecules/filter-bubble.scss
- frontend/scss/components/molecules/language-selector.scss
- frontend/scss/components/organisms/agenda.scss
- frontend/scss/components/organisms/burger-menu.scss
- frontend/scss/components/organisms/format-explainer.scss
- frontend/scss/components/organisms/fragment-slider-controls.scss
- frontend/scss/components/organisms/fragment-slider-texts.scss
- frontend/scss/components/organisms/video-slider.scss
- frontend/scss/components/templates/roadmap.scss
- frontend/scss/components/templates/tools.scss
- frontend/templates/views/partials/burger-menu.j2
- frontend/templates/views/partials/header.j2
- pages/content/amp-dev/community/roadmap.html
- pages/content/amp-dev/documentation/tools.html
These changes fixes most of the a11y issues from #2385 and #2587 
- removed `outline: none;` anywhere it was possible.
- refactored **mobile-menu** and **language-selector** to be accessible by keyboard
- optimized filter bubbles to be more accessible by keyboard
- fixed fragmet-slider (use-cases page) focusing hidden slides content issue
> ♿️ Fix focus state / keyboard access for many areas

- examples/source/interactivity-dynamic-content/Advanced_Server_Request.html
`binding` was removed from email spec so removing it from sample.
> Remove binding from email sample

- pages/extensions/amp_example_preview/util/preview_generator.py
Fix stupid copy paste error that prevents the import of the amp-mustache template here:
https://amp-dev-staging.appspot.com/tests/examples/template/
> Fix import of templates for inline example preview

- frontend/scss/components/molecules/tools-visual.scss
> 🐛 Fix tool screenshots covering header on latest macos safari

- pages/extensions/markdown_in_html/__init__.py
- pages/extensions/markdown_in_html/html_block_processor.py
- pages/extensions/markdown_in_html/html_block_processor_test.py
- pages/extensions/markdown_in_html/readme.md
- platform/config/podspec.yaml
Fixes 1809
* Activates the markdown extra extension
* Prevent automatically loading more extensions by the extra extension
* automatically add `markdown="span"` to all html table tags in markdown docs (unless found in source code blocks)
> Allow markdown in all html tables

- examples/source/news-publishing/Live_Blog/api.js
- examples/source/news-publishing/Live_Blog/index.html
Migrated the backend/live-list.go from ampbyexample.com to amp.dev.
It updates the example [here](https://amp.dev/documentation/examples/news-publishing/live_blog/?format=websites).
Fixes #2609.
> ♻️ Migrate live-blog to amp.dev

- pages/extensions/amp_dependencies/__init__.py
- pages/extensions/amp_dependencies/amp_dependencies.py
- pages/extensions/amp_dependencies/amp_dependencies_test.py
- pages/extensions/amp_dependencies/auto_dependency_injector.py
- pages/extensions/amp_dependencies/readme.md
Fix https://github.com/ampproject/amp.dev/issues/2644
The amp-dependencies plugin now automatically imports the basic components `amp-anim`, `amp-iframe` and `amp-youtube`
The logic was also improved so that you now can add a dependency without a version and afterwards add a dependency with a version which will be used
> Add automatic import of basic components to amp_dependencies hook

- gulpfile.js/build.js
Finally *really* unblocks #2594 and #2593.
Rewriting the CSS selectors was still using a DOM implementation and therefore broke SSR tags. As all our selectors are prefixed with `ap--` using the in addition faster string based method should be fine, as a quick check showed.
> ♻️ Use RCS string replace over DOM method

- .travis.yml
Moves smoke-tests to `before_script` phase as any command exiting with 0 there will immediately exit the build. 
All commands in `script` still run if a preceeding command failed which trigger a deployment even if the tests failed currently.
> 🐛 Run smoke-tests before running deployment

- firebase.json
As the FAQ section has been migrated in the meantime we can now redirect from ampproject.org
> 🔧 Redirect ampproject.org to new FAQ pages

- frontend/templates/views/partials/structured-data.j2
Once the new meta tags are inside the Google index for all pages, those tags can be used to filter search results in Google Custom Search (`more:pagemap:metatags-xxx:yyyy`)
This will help to implement a better search (#2705).
This change can and should be launched before the search functionality, as long as we will be using Google Custom Search. For other search solutions this change might not be needed.
> New meta tags (locale, format) that can be used for filtering in Google CSE

- gulpfile.js/build.js
- package-lock.json
Correct implementation of what I tried with #2685. Sadly selector rewriting with this method is not as effective (49064 bytes of CSS on home now vs 47828 before) as it has been with the DOM implementation anymore as some selectors can not be safely replaced anymore. 
But still this keeps us under the 50KB limit while at the same time finally allowing full SSR which blocks many new features...
The in my opinion best way to handle this after this temporary fix is moving the selector rewriting into an optional transformer for the amp-toolbox-optimizer. Open for any thoughts 🙂
> ♻️ Do not use DOM for selector rewriting

- frontend/templates/views/partials/structured-data.j2
Reverts ampproject/amp.dev#2721. It seems as if the [validator](https://travis-ci.org/ampproject/amp.dev/jobs/568902483#L870) doesn't like them 😅
> Revert New meta tags (locale, format) that can be used for filtering in Google CSE

- examples/source/1.components/amp-user-notification/api.js
- examples/source/1.components/amp-user-notification/index.html
Migrated the amp-user-notification example backend from herokuapp.com to amp.dev.
It updates the example [here](https://amp.dev/documentation/examples/components/amp-user-notification/).
> ♻️ Migrate amp-user-notification example backend to amp.dev

- pages/shared/data/tools.yaml
Update image src to /static/img/tools/amp-prototyper.jpg.
> Fix snapshot image path for the AMP-Prototyper in tools section

- gulpfile.js/deploy.js
Second try after #2719. This time with `default` scope explicitly assigned additionally to `datastore` according to the [gcloud docs](https://cloud.google.com/sdk/gcloud/reference/compute/instances/create#--scopes).
> 🔧 Add datastore scope to GCE instance templates

- frontend/templates/views/partials/header.j2
- pages/content/amp-dev/events/amp-cs-2019.html
Applications for the Contributor Summit 2019 have closed, so this updates the Contributor Summit page to reflect that and turns off the banner for it.
/cc @vishaldodiya @matthiasrohmer @mattludwig
> Removes Contributor Summit 2019 application & promo banner

- pages/extensions/internal_links/__init__.py
- pages/extensions/internal_links/pod_internal_link_rewriter.py
- pages/extensions/internal_links/pod_internal_link_rewriter_test.py
- pages/extensions/internal_links/readme.md
- platform/config/podspec.yaml
A new grow extension will rewrite pod internal links to site links.
Currently only links in <a href tags are handled.
This is the first step for issue #2243.
The second step would be to change all the ugly links in the content like
`{{g.doc('/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate.md', locale=doc.locale).url.path}}` to relative links like `../learn/spec/amp-boilerplate.md` or pod links like `/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate.md`
The first would be the best, since those links would be valid in markdown.
But the second could be done with a simple search and replace over all documents.
I would leave the links in the templates using g.doc for now.
It looks to me that the growReferenceChecker does not check …
> Rewrite pod internal links in <a href to site links

- examples/source/1.components/amp-recaptcha-input/api.js
- examples/source/1.components/amp-recaptcha-input/index.html
Migrated the amp-recaptcha-input example backend from glitch.com to amp.dev.
It updates the example [here](https://amp.dev/documentation/examples/components/amp-recaptcha-input/).
Fixes #1601.
> ♻️ Migrate amp-recaptcha-input example backend to amp.dev

- frontend/templates/views/detail/component-detail.j2
- frontend/templates/views/detail/docs-detail.j2
- frontend/templates/views/detail/guide-detail.j2
- frontend/templates/views/detail/template-detail.j2
- frontend/templates/views/detail/use-cases-detail.j2
- frontend/templates/views/examples/documentation.j2
- frontend/templates/views/overview/courses.j2
- frontend/templates/views/overview/guides.j2
- frontend/templates/views/partials/component-sidebar.j2
- frontend/templates/views/partials/example-sidebar.j2
- frontend/templates/views/partials/sidebar.j2
- pages/content/amp-dev/documentation/components/index.html
- pages/content/amp-dev/documentation/examples/index.html
We've tried to move the sidebar below the main area and prevent using `<section>` tags inside the sidebar to keep the indexing priority of the search low.
We can't see if those changes take a positive effect to our custom search, until they're not live.
@sebastianbenz could you please take a quick look at this?
> 🎨 Fix search priority of sidebar markup

- frontend/templates/views/partials/card-grid.j2
- frontend/templates/views/partials/teaser-tags.j2
- frontend/templates/views/partials/teaser.j2
- pages/content/amp-dev/documentation/components/index.html
- pages/content/amp-dev/documentation/examples/index.html
- pages/translations/en/LC_MESSAGES/messages.po
This addresses some of the comments in #2756.
- Non-existing linked documents don't show up as `None` anymore
- Example categories are now properly cased and divided
- Featured examples got a headline
- "Categories" has been rephrased to "Filter by category" on example and guides overview
- Playground teaser on filtered example overview opens the playground in matching format
- Format tags are shown in consistent order (websites, stories, ads, email) now. A wrong format key of `emails` so far causing a blank tag is additionally catched gracefully now
- Page title of filtered examples overview shares its format now
> 🎨 Improve new overview pages

- platform/lib/pipeline/componentReferenceImporter.js
- platform/lib/pipeline/markdownDocument.js
Fixes #2808
Also again allow to run the importer standalone.
> Fix importing component docs where the name is not a tag

- frontend/scss/components/organisms/search.scss
- pages/content/amp-dev/search.html
The search.html is no longer in use and can be deleted.
The `min-height` for the result container should be `vh` to prevent issues on smaller devices.
> Small search improvements

- frontend/scss/components/organisms/search.scss
- frontend/templates/views/partials/search.j2
This PR fixes: #2829 and #2817
- We've changed the 'no-results' message accordingly to the 404 page.
Right now the version with the sad looking smiley face `;(` is commited, but I've attached a screenshot with the alternative schruggie `¯\_(ツ)_/¯`. Closes: #2829
- There is now a fallback element for `<amp-list>` which has the same error message like on `load-more-failed`. Closes: #2817
- Additionally we've removed some unused markup
---
**current**
**alternative**
> Further search improvements

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
- pages/extensions/internal_links/__init__.py
- pages/extensions/internal_links/component_version_resolver.py
- pages/extensions/internal_links/component_version_resolver_test.py
- pages/extensions/internal_links/pod_internal_link_rewriter.py
- pages/extensions/internal_links/pod_internal_link_rewriter_test.py
- platform/config/podspec.yaml
Currently a lot of documentation links to component docs without a version.
Those links are broken since the component docs now have the version in the name.
You can see lots of broken links here: https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/control_layout/?format=websites
This PR extends the grow extension that handles relative links to lookup the latest version of a component documentation.
Information about this was added to the contribution formatting documentation.
Also some other missing and misleading parts about links and templates in examples where changed in this file.
> Internal component links without version resolve to the latest

- pages/extensions/internal_links/component_version_resolver.py
- pages/extensions/internal_links/component_version_resolver_test.py
Fix the problem that PR #2851 did not work with older grow versions
> Grow link extension should work with grow 0.7.4

- examples/source/1.components/amp-list.html
Makes it easier to transform to email example.
> Replace animation in amp-list example with static placeholder

- frontend/templates/views/partials/teaser.j2
/cc @dlemm: you can only access frontmatter keys that exist. In comparison to other template languages jinja2 doesn't fail silently 🙂
> 🐛 Only try to access teaser if it exists

- README.md
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
This PR resolves #2888, along with several other problems that I discovered.
Corrections include:
- fixing links broken due to repository renaming
- correcting various typos and grammatical errors
- using accurate and consistent speech
- clarifying OS support & Grow installation instructions
A couple of notes:
- It seems like this repository would benefit greatly by defining voice & tone guidelines. Check out [this link](https://lightningdesignsystem.com/guidelines/voice-and-tone/) for an example. I've wanted to learn more about this myself and I think having them would facilitate collaboration on a repository like this.
- Implementating a [Markdown Linter](https://github.com/DavidAnson/markdownlint) would likely assist in maintaining the quality of a substantially Markdown-based site …
> Clarify Grow installation instructions on Linux, fix broken links, typos, and grammatical errors

- platform/lib/format-transform/index.js
- platform/lib/format-transform/index.test.js
- platform/lib/utils/cheerioHelper.js
-   Makes cheerio not encode HTML entities (required for `<% ... %>` to work).
-   Adds newline before and after `<head>` tag to ensure the parser properly catches it.
Fixes #2901
> Fixes cheerio output for transformation

- pages/extensions/internal_links/pod_internal_link_rewriter.py
- pages/extensions/internal_links/pod_internal_link_rewriter_test.py
Fixes #2875. Other links (Brand guidelines, Styleguide) are also affected.
> 🐛 Only rewrite content paths in Grow pod

- platform/lib/build/samplesBuilder.js
Fixes #2928.
This is needed as we are currently simply serializing the parsedSample with `JSON.stringify`. An alternative would be to implement something like `toString()` on `abe.ExampleFile` which takes care of recursively calling available methods on child objects instead of explicitly calling the ones we need like in this PR.
> 🎨 Unwrap code snippets in sample sections

- pages/content/amp-dev/events/amp-cs-2019.html
- pages/shared/data/amp-cs-2019.yaml
This adds the tentative AMP Contributor Summit 2019 schedule to the AMPCS2019 page.
/cc @alankent @vishaldodiya @nainar @amanrazdan @newmuis @choumx @pbakaus
> Add the tentative AMP Contributor Summit 2019 schedule

- platform/config/go-links.yaml
We want a short link to put on AMPCS2019 badges so people can quickly get to the agenda.
I optimistically used the #Schedule anchor; will this actually work?
/cc @alankent @nainar @mattludwig @sebastianbenz
> Adds a go.amp.dev link for the AMPCS2019 schedule

- pages/content/amp-dev/index.html
Not a fix for a specific issue but something I felt to be better UX: the two Get Started links on the homepage point to the Guides & Tutorials overview page while we introduced the new Get Started page for the documentation which might be a better fit for those links.
> 🚸 Make Get Started links on home point to Docs/Get Started

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-managing-user-state.md
- platform/lib/pipeline/markdownDocument.js
- platform/lib/pipeline/markdownDocument.test.js
Fixes #2865 and makes `/documentation/guides-and-tutorials/optimize-and-measure/amp-managing-user-state/?format=websites` available again.
> 🐛 Escape SSR tags when importing documents

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
Closes [https://github.com/ampproject/amphtml/issues/24441](https://github.com/ampproject/amphtml/issues/24441)
- Adds an explanation about what event and action trust levels are
- Adds a column to specify the required trust level for every action
> Describes trust levels for actions and events

- examples/api/amp-access/index.js
- examples/source/1.components/amp-access.html
- examples/source/1.components/amp-analytics/api.js
- examples/source/1.components/amp-analytics/embed.html
- examples/source/1.components/amp-analytics/index.html
- examples/source/1.components/amp-recaptcha-input/index.html
- examples/source/1.components/amp-web-push/index.html
- examples/source/e-commerce/Checkout_Flow/index.html
- examples/source/e-commerce/Shopping_Cart/index.html
- examples/source/interactivity-dynamic-content/Comment_Section/index.html
- examples/source/interactivity-dynamic-content/Favorite_Button/index.html
- examples/source/interactivity-dynamic-content/Poll/index.html
- examples/source/interactivity-dynamic-content/Star_Rating/index.html
- frontend/templates/views/examples/documentation.j2
The first commit addressed the problem that post requests didn't work in the playground. Unfortunately, there's no way to solve this without re-writing the source files so we'll have to use `<% base_path %>` for these cases. 
The other commits fix the amp-analytics and the amp-access samples which never worked on amp.dev.
> Fix a bunch of broken samples

- examples/source/interactivity-dynamic-content/ComboBox.html
[Related issue](https://github.com/ampproject/amphtml/issues/23737)
Currently the sample only allows opening the suggestions but cannot close them. This change updates the sample to allow the arrow button to close the suggestions if they are being displayed.
> Update ComboBox sample to open and close autocomplete suggestions

- frontend/scss/components/organisms/code-preview.scss
- frontend/templates/views/partials/code-preview/code-preview.j2
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
fix https://github.com/ampproject/amp.dev/issues/2975
also did some small cleanup
> Fixed example top-frame preview in portrait mode

- frontend/templates/views/partials/structured-data.j2
- pages/extensions/amp_dev/extension.py
Currently we search for locale 'en' and the specific locale when we are
not in the 'en' language because the untranslated pages are not in the
google index.
With this change the 'en' documents also have the language in the meta
tags that are not translated, so we can simply search for the language
after the index was updated.
> Search meta tag page-locale has untranslated locales on default page

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-amphtml-email.md
It's outdated and I'm hoping to supersede it with the new viewer documentation and reference implementation docs.
> Remove 'Email Provider integration' doc

- pages/content/amp-dev/events/amp-cs-2019.html
This simply adds the dates to the tab titles of the schedule.
> AMP-CS: add dates to the tab titles of the schedule

- platform/lib/middleware/redirects.js
This enables local testing with other host name than 'localhost'
Useful for testing with other devices in a local network.
Still not all things will work without https (like search)
> Only perform https redirect if scheme is set to https

- frontend/scss/components/templates/support-overview.scss
- frontend/templates/views/overview/support.j2
- frontend/templates/views/partials/breadcrumbs.j2
- pages/content/amp-dev/support/_blueprint.yaml
- pages/content/amp-dev/support/faq/platform-involvement.md
This pull request fixes issues #2339 (P0) and #3036.
I created an overview template for the support section based on the styles being used by other overview templates since there weren't any preexisting ones with this particular format.
Once I added breadcrumbs to this page, they weren't working properly because the support section breadcrumbs weren't meant to target an overview page like this, so I changed them to mimic the behavior seen in [Get Started](https://amp.dev/documentation/), which is the overview page for the documentation section.
Once the breadcrumbs were properly terminating, one of the FAQ page titles was very long, which caused it to look strange. I opted to allow pages in the support section to specify their own breadcrumb title in the frontmatter ($titles.breadcrumb) …
> Fix support section overview and breadcrumbs

- examples/source/1.components/amp-video.html
- platform/lib/build/samplesBuilder.js
This will fix #3048
Also fix an invalid link inside amp-video sample
> Ensure whitespace is aligned correctly when parsing samples

- platform/config/go-links.yaml
This points go.amp.dev/wg to the [Working Groups page](https://github.com/ampproject/meta/tree/master/working-groups) on GitHub.
/cc @ampproject/wg-outreach
> Adds a go link for AMP's Working Groups

- frontend/scss/components/organisms/code-preview.scss
- frontend/templates/views/partials/code-preview/code-preview.j2
Disabling this because of the issue in Safari won't fix.
Tackling this again another time, with a different solution.
Closes: #2695
> :fire: Disable animation for standalone preview

- pages/content/amp-dev/events/amp-cs-2019.html
This updates the location information for the AMP Contributor Summit to be more clear on where people should go.
/cc @ampproject/wg-outreach
> Update the location information for the AMP Contributor Summit

- platform/lib/routers/growPages.js
- platform/lib/utils/HeadDedupTransformer.js
- platform/lib/utils/HeadDedupTransformer.test.js
The samples define head tags are injected into the template
causing validation errors due to duplicated tags. I couldn't
come up with a clean handle this on a template level. Instead,
I've opted for writing a optimizer transformer that'll remove
duplicates.
> Fix sample doc pages not validating

- frontend/scss/components/molecules/code-snippet.scss
I added multiple `&nbsp;` as spacer after the code-snippets to force a space between the last character in the longest line and the edge of the box.
I know this is not the prettiest solution, but after trying to fix this with different approaches like padding, margin, width, calculation etc., I'm almost sure that this is the only solution.
Additionally I made sure that the characters are not selectable.
If anyone has an idea to fix this in a different way, please let me know.
Closes: #2499
> 💄 Optimize spacing at the end of line in code-snippets

- gulpfile.js/deploy.js
This will allow repeated builds with the same commit SHA.
> Add timestamp to deploy tag

- frontend/scss/components/molecules/device-toggle.scss
- frontend/scss/components/molecules/experiments.scss
- frontend/scss/components/organisms/preview-pane.scss
- frontend/templates/views/examples/documentation.j2
- frontend/templates/views/examples/preview.j2
- frontend/templates/views/partials/experiments/experiments-controls.j2
- frontend/templates/views/partials/experiments/experiments-script.j2
- frontend/templates/views/partials/experiments/experiments.j2
- pages/content/shared/experiments.html
- platform/lib/platform.js
- platform/lib/routers/example/experiments.js
With this PR the existing experiment toggle from the example pages coming to the standalone sample previews (View demo button).
Closes: #2991
> ✨ Implement the experiment toggle in standalone sample preview 

- frontend/scss/components/molecules/teaser-faq.scss
Stop including `display: block;` from `teaser-linking` mixin and copy the relevant styles instead.
Fixes: #3111
> 🐛 Fix FAQ teasers

- frontend/scss/components/organisms/banner.scss
- frontend/scss/components/organisms/resources-overview.scss
- frontend/scss/components/templates/_default.scss
- frontend/scss/components/templates/overview.scss
- frontend/scss/components/templates/support-overview.scss
Fixing this by setting a minmax to the grid-columns
> 🐛 Prevent grid columns from oversizing in Chrome Canary

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
> Fix comparing `input-throttled` and `input-debounced` to non-existing `input` event

- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ar.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@es.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@fr.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@id.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@it.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ja.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ko.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@pt_BR.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ru.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@tr.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@zh_CN.md
Update translated md-files for `amp-ad` / `amp-embed` component to add Insticator to the list of supported embed types.
Languages: ar, es, fr, id, it, ja, ko, pt, ru, tr, cn.
@CrystalOnScript 
cc @triso07
> 🌐 Add insticator to translated md-files for amp-ad component.

- frontend/scss/components/organisms/search.scss
- frontend/templates/views/partials/search.j2
With this PR it is possible again to click on any result or teaser, while something new is typed in the input field.
Fixes: #3164
> 🐛 Search: fix autosubmitting by clicking outside of the input

- frontend/scss/components/templates/_default.scss
- frontend/scss/components/templates/examples/manual.scss
- frontend/templates/views/examples/documentation.j2
This PR fixes the following bugs of each example docs page:
- missing background color for the current format
- gap at the help/author section on the bottom
Fixes: #3165
> 🐛 Fix examples documentation pages styling bugs

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-structure.md
- pages/shared/data/blog.yaml
- platform/lib/pipeline/markdownDocument.js
The docs for `amp-izlesene` seem to have been authored on a Windows machine which caused them to have `\r\n` instead of just `\n` in them. That made splicing out the frontmatter fail.
> 🐛 Allow carriage return in MarkdownDocument

- platform/lib/samples/CodeSection.js
- platform/lib/samples/CodeSection.test.js
I'm not sure how I missed this, but #2411 added the same feature as `@formats` and in a different place.
> Remove obsolete @filter logic

- frontend/scss/components/organisms/code-preview.scss
- frontend/templates/views/partials/code-preview/code-preview.j2
This PR fixes the rotation glitch on preview iframes (#3166) by removing the initial orientation class.
Additionally, I found a bug on the overflow fading-bar on top of the code snippets (when scrolling the code up). I fixed this by placing the bar on the parent element.
Fixes: #3166
> 🐛 Fix iframe preview rotation glitch and overflow fading-bar

- platform/lib/config.js
If the URL contains templates like `<% base_path %>`, then `absoluteUrl` will escape this:
```js
absoluteUrl(conf, '<% base_path %>/test') === 'https://amp.dev/%3C%%20base_path%20%%3E/test'
```
This makes `absoluteUrl` ignore these URLs (which are probably absolute anyway) and fixes the current issue where transformed samples don't work (e.g. star rating for email).
> Don't transform URL if it contains <%

- pages/shared/data/tools.yaml
This will remove the WP story editor from the tools page while in its current rough beta state to be more consistent of what quality bar tools need to meet to appear on the page.
> Remove WP Stories editor while we're rebooting

- examples/source/1.components/amp-list.html
**summary**
The height of each row is actually only 22px.
See the "Rendering amp-list" [here](https://amp.dev/documentation/examples/components/amp-list/?format=websites#rendering-amp-state).
**screenshot**
> amp-list rendering from amp-state height fix.

- examples/source/style-layout/Dark_Mode_Toggle.html
Fixes #3224.
This sample demonstrates how to use dark mode. It shows both `prefers-color-scheme` as well as a manual toggle for people on non-supporting browsers.
> Add dark mode sample

- package.json
- platform/config/environments/production.json
- platform/config/environments/staging.json
- platform/lib/config.js
- platform/lib/utils/pageCache.js
I already wasted so much time trying to figure out why looking up instances per API doesn't work... this PR hardcodes the available instances to our config to finally make caching work on production.
> ♻️ Hardcode redis instances for page cache

- platform/lib/routers/search.js
... making them relative was only to have better DX while testing.
> 🐛 Return absolute URLs for search results

- .editorconfig
- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/content.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/tool.md
Prior to this commit, the GitHub issue templates
had inconsistent and suboptimal formatting.
* Correct various typos
* Add emoji to issue template headings<sup>1</sup>
* Add greeting comments to issue templates<sup>1</sup>
* Allow trailing whitespace in Markdown files<sup>2</sup>
<sup>1</sup> Follows [implementation by Node.js](https://github.com/nodejs/node/tree/master/.github/ISSUE_TEMPLATE), adapted for amp.dev purposes
<sup>2</sup> A line break preceded by two or more spaces [makes _hard line breaks_](https://github.github.com/gfm/#hard-line-breaks)
The "new feature" template is the most noticeably incorrect with inverted headings. I discovered this while in the process of making a feature request. Please consider merging this fix.
> contrib: improve issue template formatting

- platform/config/imports/spec.json
As we prepare to announce changes to [release names](https://github.com/ampproject/amphtml/issues/25560), new [nightly releases](https://github.com/ampproject/amphtml/issues/25616), and the new [LTS release channel](https://github.com/ampproject/amphtml/issues/25578), the Release Schedule doc is getting a major [rewrite/upgrade](https://github.com/ampproject/amphtml/pull/26085). This doc includes details on how changes in `ampproject/amphtml` make it through nightly, weekly, and into LTS releases; provides information on the opt-in cookie for the experimental/beta build channels; and includes details on how to use the LTS release channel in a page.
There will be an accompanying blog post (thanks @nainar ) early next year to announce the changes, but it seemed reasonable that we also make …
> Import `release-schedule.md` into AMP.dev

- package-lock.json
- package.json
- playground/src/app.critical.scss
- playground/src/app.js
- playground/src/email-loader/email-loader.js
- playground/src/email-loader/email-loader.test.js
- playground/src/index.hbs
This button opens a file selection dialog, allowing a user to select an .eml file in the MIME format (that's usually created by email clients when you download a message). If the opened email contains an AMP part, that part is loaded into the playground.
> Adds "Import email" button to the playground

- platform/config/go-links.yaml
Currently, we link to bit.ly/amp-cherry-picks for the cherry-pick documentation. https://github.com/ampproject/amphtml/pull/26085 moves that cherry-pick documentation to a different document, but we are unable to change a bit.ly shortlink. This adds an AMP Go link for cherry-pick instructions so we can 1) update docs to use the AMP shortlink and 2) edit that shortlink as needed.
> Add go.amp.dev/cherry-picks link

- .github/ISSUE_TEMPLATE/config.yml
This PR will prevent stuff like this:
- https://github.com/ampproject/amp.dev/issues/3361
- https://github.com/ampproject/amp.dev/issues/3332
It would require contributors to use an issue template.
More info on this config.yml can be found at [Configuring the template chooser](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser).
> feat(meta): disable blank issues

- pages/translations/ar/LC_MESSAGES/messages.po
- pages/translations/en/LC_MESSAGES/messages.po
- pages/translations/es/LC_MESSAGES/messages.po
- pages/translations/fr/LC_MESSAGES/messages.po
- pages/translations/id/LC_MESSAGES/messages.po
- pages/translations/it/LC_MESSAGES/messages.po
- pages/translations/ja/LC_MESSAGES/messages.po
- pages/translations/ko/LC_MESSAGES/messages.po
- pages/translations/pt_BR/LC_MESSAGES/messages.po
- pages/translations/ru/LC_MESSAGES/messages.po
- pages/translations/tr/LC_MESSAGES/messages.po
- pages/translations/zh_CN/LC_MESSAGES/messages.po
In setting up some of the i18n work, I saw a number of strings on the site that were referenced in `_('*')` blocks were not actually defined in the po files. 
This just added all of the missing things to the po files
scripted it to automate the work
```bash
LANGS=(ar en es fr id it ja ko pt_BR ru tr zh_CN)
function join { local IFS="$1"; shift; echo "$*"; }
IFS=$'\n'
for i in `ag -o "_\('\K([^)]*)(?=\'\))" | sed '/^$/d'`; do
IFS=':'
read -a INFO <<< "${i}"
IFS=$'\n'
FILENAME=${INFO[0]}
LINE_NUMBER=${INFO[1]}
THE_REST=$(join : ${INFO[@]:2})
for L in "${LANGS[@]}"; do
LANG_FILE="pages/translations/$L/LC_MESSAGES/messages.po"
if [[ -z $(grep "$THE_REST" "$LANG_FILE" ) ]]; then
echo "#: $FILENAME:$LINE_NUMBER" >> "$LANG_FILE"
echo msgid \"$THE_REST\" >> "$LANG_FILE"
echo msgstr \"\" >> …
```
> add missing strings to po files

- examples/source/interactivity-dynamic-content/Restrict_Duplicate_Selection.html
- examples/static/samples/json/fruits.json
Adding a html file and json file showing how to restrict duplicate selection of items in amp-list. One of the amp-snippets from glitch project [here](https://amp-snippets.glitch.me/)
This snippet uses 'amp-selector' in combination with 'amp-bind' to check whether or not an item is currently in the list (populated by amp-state 'Fruit_Array_holder'). If fruit selected is already in the list nothing changes, if not selected fruit is added to end of list.
> Add new Interactivity & Dynamic Content Restrict Duplicate Selection

- frontend/scss/components/molecules/tag.scss
- frontend/templates/views/partials/teaser.j2
This PR changes the tag labels on success stories page from format to category.
Fixes: #3387
> 🐛 Change success stories tag labels from format to category

- pages/translations/ar/LC_MESSAGES/messages.po
- pages/translations/es/LC_MESSAGES/messages.po
- pages/translations/fr/LC_MESSAGES/messages.po
- pages/translations/id/LC_MESSAGES/messages.po
- pages/translations/it/LC_MESSAGES/messages.po
- pages/translations/ja/LC_MESSAGES/messages.po
- pages/translations/ko/LC_MESSAGES/messages.po
- pages/translations/messages.po
- pages/translations/pt_BR/LC_MESSAGES/messages.po
- pages/translations/ru/LC_MESSAGES/messages.po
- pages/translations/tr/LC_MESSAGES/messages.po
also I moved the zh-CN file from a `.pot` to a `.po`, as it isn't a template
> [docs] add translated apology banner for all languages

- .npmrc
This PR will, by default, pin exact dependency versions saved to package.json.
The equivalent amphtml PR is https://github.com/ampproject/amphtml/pull/23290.
Refs
- https://docs.npmjs.com/files/npmrc.html#per-project-config-file
- https://docs.npmjs.com/misc/config#save-exact
> 🏗 Automatically pin exact versions with `npm install`

- frontend/templates/views/partials/search.j2
This PR changes the prefilled search input from placeholder to value.
> 👌 Prefill search input field with value instead of placeholder

- platform/lib/build/samplesBuilder.js
When `_parseSample` is called on a sample multiple times, ensure the real
path to a sample is maintained in case of normalization.
Fixes #3140
> sampleBuilder: Do not mangle real sample path

- frontend/scss/components/organisms/burger-menu.scss
Increase z-index of burger-menu to the same value as the recently increased z-index of header #3428
> 🐛Fix not showing burger menu icon

- frontend/templates/layouts/example-pages/amp-ads-page.j2
- frontend/templates/layouts/example-pages/amp-stories-page.j2
- frontend/templates/layouts/example-pages/amp-websites-page.j2
- frontend/templates/views/examples/embed-ads.j2
- frontend/templates/views/partials/structured-data.j2
Untested, but hopefully the CI will be able to do that.
Fixes: #3472
Refs:
> Escaping works by piping the variable through the |e filter:
>```jinja
> {{ user.username|e }}
> ```
> — [Template Designer Documentation &#8212; Jinja Documentation (2.11.x)](https://jinja.palletsprojects.com/en/2.11.x/templates/#working-with-manual-escaping)
> 🔥 Escape all HTML inserted into title tags

- frontend/templates/views/partials/structured-data.j2
My mistake, the previous PR's quotes ended up getting repeated and the filter order was causing undesirable results. I've remedied this by changing the order of the filtering — this should be correct.
> 🔧 Fix filter order and quotes

- gulpfile.js/develop.js
First part of #3330. The application relies on `examples/static/samples/samples.json` to exist when starting up.
> 🐛 Build samples when bootstrapping

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/release-schedule.html
Currently the [release schedule visualization](https://amp.dev/documentation/guides-and-tutorials/contribute/vendor-contributions/release-schedule/) is broken. It has `layout="intrinsic" height="0"` which makes the `amp-script` render with a height of 0. This swaps the layout for `layout="container"`, allowing the children to determine the size of the `amp-script` tag. I'm not entirely certain that this is the "correct" use, but it resolves the issue (see below).
> The above was seen by running `npm run develop` on my changes
> Set release-schedule visualization to layout:container

- frontend/scss/components/organisms/release-schedule.scss
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/release-schedule.html
The original implementation used `layout="intrinsic" height="0"` for the `amp-script` container element. A series of recent bug fixes fixed how `amp-script` works with `layout="intrinsic"`, and this broke the page by setting the container's height to 0.
This PR doubles up the `amp-script` tag and defines each as a `fixed-height` layout based on the grid sizes for desktop and mobile views. A CSS media query controls which one is displayed. Tested on desktop and emulated mobile; confirmed valid AMP with AMP Validator Chrome Extension.
> Use fixed-height layout for calendar with desktop/mobile sizes

- frontend/scss/components/molecules/language-selector.scss
- frontend/scss/components/organisms/header.scss
- frontend/templates/views/partials/header.j2
- pages/content/shared/header.html
Part of the fixes for https://github.com/ampproject/amp.dev/issues/3152#issuecomment-568150532.
The language selector doesn't render for the [shared header fragment](https://amp.dev/shared/header/) and it being absent doesn't interfer with the styling of the other elements anymore.
> 🎨 Make language selector in header optional

- platform/lib/platform.js
- platform/lib/routers/growPages.js
- platform/lib/routers/growPages.test.js
- platform/lib/routers/growSharedPages.js
Successor to #2934 and https://github.com/ampproject/amp.dev/issues/3152#issuecomment-567117739. /shared/header/ and /shared/header.html weren't the same. The first one was served by growPages.js and was hence optimized. The later one was correctly served by growSharedPages.js and wasn't.
Both URLs now return the same, unoptimized result.
> 🎨 Ensure shared pages and pages router behave the same

- package-lock.json
- package.json
Hah. Been wondering about every pull request Renovate was creating for this 😄 `got` was once powering the proxy layer to Grow but has been long replaced by `node-fetch`.
> ➖ Remove got as dependency

- frontend/templates/views/partials/search.j2
To add search to blog.amp.dev beside the endpoints returning absolute URLs the endpoints themselves need to be called by their absolute URLs. See https://github.com/ampproject/amp.dev/issues/3152#issuecomment-568150532 for context.
> 🐛 Use absolute URLs for search API endpoints

- pages/extensions/internal_links/pod_internal_link_rewriter.py
Fixes #3519.
Wasn't paying attention during the review of #3486. There is no `String.contains` or `String.includes` in Python but only `String.find` and the `in` operator to check for sub-string existance.
> 🚑 Use in operator instead of non-existant includes

- frontend/scss/components/organisms/component-intro.scss
- pages/content/shared/copy-script.html
Part of the fixes for #3540.
- Fixes the misnamed variable in the copy script
- Increases the padding for the code snippet
> 🐛 Fix-up for component intro tables

- examples/source/1.components/amp-script/index.html
Corrupt references in the examples are not picked up by `GrowReferenceChecker` as the pages are only built from the JSON files. We could think about checking the sample source files though. 🤔
> 🐛 Correctly link to amp-script doc from example

- platform/lib/common/AmpConstants.js
- platform/lib/pipeline/componentReferenceImporter.js
- platform/lib/routers/search.js
Sorry for the PR spam, just things I stumble over while waiting for my test builds to finish 😅
The set of built-in components had been defined twice. The constant is now shared.
> 🎨 Share definition of built in components

- platform/lib/pipeline/componentReferenceDocument.js
As discussed this morning: this will set `formats` to `['websites']` if a component reference doc doesn't specify it. Also fixes #3549.
> 🚸 Force-list components for websites if unspecified

- README.md
- gulpfile.js/build.js
- platform/lib/build/samplesBuilder.js
First part of #3417. Looks hefty but actually isn't, mainly moved code around:
- Instead of sequentially waiting for dependent operations to complete before starting to build I moved them to `_bootstrap` to await them in parallel with `Promise.all`
- The callback for `through` is not blocking anymore, samples build parallelly now
- The first run of the samples builder now always freshly builds all samples and cleans artifacts from previous builds
- Sample maps are only built during that first call to prevent incomplete maps as mentioned in #3540
> 🎨 Make Samples Builder non-blocking, always build all on first run

- frontend/scss/components/templates/component-detail.scss
- platform/lib/pipeline/componentReferenceImporter.js
Fixes #3557.
What's a bit unfortunate (also currently is): this hides the fact that there is a deprecated version of for example `amp-experiment` as there is no version toggle. Alternatively, we could copy the "latest" document and show it for both versions - though that might also be confusing UX.
> 🐛 Fix version toggle issues

- platform/lib/pipeline/componentReferenceDocument.js
Fixes tons of broken Github urls in imported docs.
> Don't use join to concatenate a URL, as it drops double slashes

- platform/lib/config.js
- platform/lib/pipeline/componentReferenceDocument.js
- platform/lib/pipeline/markdownDocument.js
- platform/lib/utils/grow.js
- platform/lib/utils/log.js
This has been confusing not just for @DerekNonGeneric in #3346 but for team mates of mine as well: test cases that test error handling print error messages although the test itself succeeded.
**Currently**
**With this PR**
> 🔇 Disable logs during test runs

- pages/content/amp-dev/index.html
Changed:
> Because it is a open-source project, it is free!
to:
> Because it is an open-source project, it is free!
> Fixed spelling/grammar error on home page

- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/animating_elements.md
> Fix closing tag name typo

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors.md
Page updated: https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors/
The CSS limit has been upped to 75,000 per https://github.com/ampproject/amphtml/pull/26475
> Updating page to reflect updated CSS limit

- pages/translations/zh_CN/LC_MESSAGES/messages.po
**- Fix the main page title not-Chinese-grammatical-correct translation**
(WAS "AMP is a easily to create user-first web component framework | websites/stories/emails/ads" to NOW"AMP is a web component framework easily create user-first website/stories/emails/ads")
- More translations
- Microadjust some words expression
> update homepage grammar on Chinese translation

- platform/lib/pipeline/markdownDocument.js
Related to #3591. For all automatically extracted teaser texts we have been removing all Markdown syntax except headlines - or at least tried to. This PR fixes that and also adds a RegEx for headline tags.
Manual teaser texts don't contain any markdown tags. At the latest after https://github.com/ampproject/amphtml/pull/26383/.
@sebastianbenz, you decide if we should still enable Markdown rendering in the intro table as requested with #3591: the problem is that we somewhat rely on the teaser text to not contain any markdown as when we show it in a teaser (which naturally is an `<a>` the text shouldn't contain any other links as for example Chrome would move them out of their enclosing `<a>` which could have strange side effects.
> 🎨 Remove headline tags from teaser texts

- platform/lib/config.js
after digging into some analytics with the devsite folks, the numbers seem to say having a Deutsch version of the site makes a lot of sense. @ilyaspiridonov and co were kind enough to provide it, we just need to add this to the config (I think? - @matthiasrohmer/@sebastianbenz please correct me if I am wrong)
> Deutsch zu unterstützten Sprachen hinzufügen

- frontend/templates/views/partials/category-filter.j2
- pages/content/amp-dev/documentation/examples/index.html
This unbreaks the build and brings what has been introduced with #3619 to the example overview page as well.
@robinvanopstal, watch out when editing partials 😉 They might be used in more than one place. I also didn't pay enough attention during review, sorry.
> 🚑 Adapt category filtering for examples overview

- frontend/templates/views/partials/toc.j2
- pages/extensions/amp_dev/extension.py
- pages/extensions/amp_dev/markdown_extras/block_filter.py
That's ugly and did cost me more time than I had hoped. It's not possible to access `doc.format.toc` in any of the render hooks to get the generated TOC as this would reevaluate the document's content and make all transformations obsolete.
Therefore this passes a callable to the template in which you are free to call `doc.format.toc` as `doc.format.content` has already been rendered.
Resolves #3545, adds to #2774. @morsssss, this would allow the courses to have level-specific TOCs again. Do you want them back?
> 🚸 Filter TOC based on format and level

- pages/extensions/amp_dev/markdown_extras/block_filter.py
This fixes two problems: Markdown (or more correct: the resulting HTML) is stripped from the TOC but I've been searching for the headlines with them still containing Markdown syntax. I am assuming we only use code blocks in headlines and therefore simply replace backticks.
Second problem was that replacing failed for headlines that contained regular expression special chars. This is now correctly handled by using `re.escape`.
> 🐛 Escape headline when filtering TOC

- pages/extensions/amp_dev/markdown_extras/block_filter.py
That's quick and dirty but will be unnecessary with #3367.
It addresses the problem of nested `{% call %}` blocks that occurs when for example tips are in a filtered section.
> 🐛 Make filter call blocks unique

- pages/content/amp-dev/documentation/courses/index.html
Part of the templating was added for internationalizing this string, but part was omitted.
> Fix typo in courses

- platform/config/go-links.yaml
This PR adds a short link go.amp.dev/wg-updates to redirect to AMP's [working group updates](https://github.com/search?o=desc&q=org%3Aampproject+label%3A%22Type%3A+Status+Update%22&s=created&type=Issues).
> Add a `go.amp.dev` link for working group updates

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_emails.md
Many email senders are struggling with AMP validation failures caused by
ESP's modification to the email markup after the sender sends the markup
to the ESP, and they often find it hard to diagnose exactly what the
validation failures are.
/to @CrystalOnScript 
/cc @fstanis 
/cc @choumx
> Document validation of delievered AMP emails

- README.md
Fixes #3693. Python 2.7.  has officially reached end of life that's why brew removed the matching formula. Grow support for Python 3 is still work in progress though.
> 📝 Update instructions for Python installation

- platform/lib/pipeline/componentReferenceDocument.js
Fixes #3699. The look-up for other required extensions has been happening on the tag instead of the script element.
This made `amp-sidebar` listed as a required extension for `amp-nested-menu` but ignored for what the look-up has actually been implemented: `amp-access-poool` (and related) should list `amp-access` and `amp-access-poool`. This is now the case.
I've quickly gone through all imported component docs and required scripts now look fine from what I can tell.
> 🐛 Only add required scripts for scripts not for tags

- frontend/templates/views/partials/analytics.j2
Resolves #3723. This adds analytics triggers for the following events:
- Clicks on links inside the table of contents 
- Clicks on links inside the sidebar
- Toggling of the sidebar
- Toggling of the TOC
- Clicks on breadcrumb links
- Clicks on a new format inside the format toggle or the format notification
- Scroll depths (50% and 90% depth)
I've been wondering why `event_name` isn't sent to GTM with each request. I assume that's handled under the hood when the configuration is initially transformed by the GTM?
> 📈 Add various analytics triggers

- examples/source/1.components/amp-sidebar.html
Fixes ampproject/amphtml#26196
Added a navigation sidebar to the amp-sidebar example that is always visible.
@sebastianbenz
> 📖 Update amp-sidebar example to include always visible desktop sidebar

- platform/lib/build/samplesBuilder.js
Fixes #3767 - I guess. The order is correct during development for me and it's inverted on prod and honestly, I can't get my head around why. But I assume not reversing the array should fix it for production at least.
> 🚸 Show specific component samples as first in component intro

- examples/source/style-layout/Tab_Panels_with_amp-selector.html
At the request of @sebastianbenz, I've added the `keyboard-select-mode` attribute to each of the three examples on this sample page. 
It's worth noting that I've passed the `focus` option (versus `select` or `none`). There was no stipulation as to which option these examples ought to employ, so I went with what I thought was the most approachable alternative.  Please let me know if you would like me to make any changes.
> Add keyboard-select-mode

- examples/source/style-layout/Dark_Mode_Toggle.html
The article is not at https://web.de/prefers-color-scheme, but at https://web.dev/prefers-color-scheme. Please also update the article at https://amp.dev/documentation/examples/style-layout/dark_mode_toggle/
> Fix speling mistake in article URL

- templates/websites/travel/templates/travel.amp.html
fix wrong links in travel templates landing page to result page
currently the links are without `.html`, and the result page is a 404: https://amp.dev/documentation/templates/preview/websites/travel/templates/travel-results.amp
This page with `.html` works: https://amp.dev/documentation/templates/preview/websites/travel/templates/travel-results.amp.html (but the APIs for that page are not there)
> template, fix pages linking

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md
This PR is to add Permutive to the AMP analytics-vendors page. 
The previous PR for this (ampproject/amp.dev/pull/1313) was merged after analytics-vendors was migrated.
> Add Permutive to the analytics-vendors page

- pages/shared/data/faq.yaml
- dotdigital
- Elastic Email
- Mailrelay
- Mapp Cloud
- Tripolis
> Add 5 more ESPs that support AMP

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
resolves issue [# 27643](https://github.com/ampproject/amphtml/issues/27643)
> removed Supports standard URL substitutions from AMP.navigateTo

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/monetization/content_encryption.md
Previous URL was a Google doc with limited access.
> Fix "Github Issue" link on encryption doc.

- examples/source/user-consent/Geolocation-based_Consent_Flow.html
Update the geolocation-based consent flow example to better address the U.S. CA case.
> Add preset-use-ca support

- playground/src/email-loader/email-loader.js
- playground/src/email-loader/email-loader.test.js
This fixes a bug where `Content-Type` can contain more parameters (like encoding) and overall makes the content type parser more true to [RFC 2045](https://tools.ietf.org/html/rfc2045#page-12).
> Improvements to "import email" logic

- frontend/scss/components/atoms/sidebar-toggle.scss
- frontend/templates/views/partials/sidebar-toggle-observer.j2
Use `scale3d` for hiding sidebar label-title since `display: none` is not supported by `amp-animation`
Fixes: #3885
> 🐛 Fix sidebar-toggle prevents clicking content

- examples/source/1.components/amp-sticky-ad.html
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/release-schedule.html
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/get-familiar.md
- Resolves #3940 and adds a hint about the boilerplate generator to the [Get familiar with the start code](https://amp.dev/documentation/guides-and-tutorials/develop/interactivity/get-familiar/?format=websites) article. The same hint is added to the boilerplate spec by https://github.com/ampproject/amphtml/pull/28413
- Updates the title of [Release Schedule](https://amp.dev/documentation/guides-and-tutorials/contribute/vendor-contributions/release-schedule/?format=websites) to "Interactive Release Calendar" to prevent doubling with the [imported document](https://amp.dev/documentation/guides-and-tutorials/learn/spec/release-schedule/) explaining the release schedule. (Also see https://github.com/ampproject/amphtml/pull/28415)
- Makes the use of dummy content for the [amp-sticky-ad …
> 💬 Various small content updates

- gulpfile.js/import/importRoadmap.js
This currently makes all our PR-checks failing.
> 🐛 Lazily initialize GitHub client for roadmap import

- .dockerignore
- .gcloudignore
- .gitignore
- .travis.yml
- gulpfile.js/deploy.js
- gulpfile.js/thumbor.js
- package-lock.json
- package.json
- platform/config/environments/development.json
- platform/config/environments/local.json
- platform/config/environments/staging.json
- platform/config/shared.json
- platform/lib/routers/growPages.js
- platform/lib/routers/static.js
- platform/lib/routers/thumbor.js
- platform/lib/utils/imageOptimizer.js
- platform/lib/utils/project.js
- thumbor/Dockerfile
- thumbor/app.yaml
> 🎉  Thumbor

- .travis.yml
- gulpfile.js/deploy.js
- gulpfile.js/thumbor.js
- platform/lib/routers/thumbor.js
- thumbor/Dockerfile
As long as we are not using Google Cloud Storage we can keep Thumbor entirely stateless just like the packager.
> ♻️ Use thumbor's HTTP loader to keep it stateless

- pages/extensions/extract_highlights_info/page_info_collector.py
This has been printing errors about a RegEx failing on an empty string before. Now it's a little more helpful.
> 🚸 Improve DX for when documents do not exist during start-up

- .gitignore
- gulpfile.js/import/importRoadmap.js
- package.json
- pages/content/amp-dev/community/roadmap.html
- Roadmap now allows emojis by using JSON instead of YAML 🎉 - fixes #4002
- Removes stale octokit dependency
- Roadmap also shows closed issues/status updates
> 🐛 Various fixes around roadmap.

- frontend/templates/views/partials/banner.j2
- frontend/templates/views/partials/header.j2
/cc @mrjoro 
The banner is somewhat long. It takes up two lines on mobile. I tried to compress this rather complex message... then again, I think the previous banner probably wrapped on mobile too :)
> Add banner for OpenJS Collaborator Summit

- frontend/templates/views/partials/banner.j2
Turns out that, on smaller devices, the previous banner wrapped to 3 lines, causing the text to overflow the banner area, which is fixed to 31px.
I tried making the banner height not fixed, but of course that doesn't play well with the fact that the hamburger menu icon is `position:fixed`.
To allow more text on smaller devices, we could do any of the following:
* fix all the header CSS so that the banner could change height with impunity
* make the font smaller on smaller devices. (0.75rem looked great.)
* just warn people not to make the banner too large 🙃
For now, I'm just shortening the message, even though we lose the date. But others may have a better idea!
> Shorter banner to avoid layout issues

- playground/src/share/index.js
Fix the problem that sharing didn't work when a document was specified
via URL.
See https://github.com/ampproject/amp.dev/issues/3324#issuecomment-642918557
> Playground: remove URL parameter when sharing

- gulpfile.js/build.js
- package.json
Reverts ampproject/amp.dev#4088. We didn't minify in-place but the task also copied the pages to their final destination: `${project.paths.GROW_BUILD_DEST}/**/*.html` !== `${project.paths.PAGES_DEST}`
> Revert 🏗  Remove minifyPages task

- platform/config/go-links.yaml
Adds go.amp.dev links to GitHub & our contributor docs.
> Adds go.amp.dev links to GitHub & our contributor docs

- examples/api/autosuggest.js
- examples/source/1.components/amp-autocomplete-email.html
Fixes #4060 
~Note: The validator errors with `Invalid URL protocol 'http:' for attribute 'src'` because the `<% hosts.platform %>` substitutes for `http:` rather than `https:` -- is it possible to address this to allow the sample to validate in the AMP4Email playground?~
> Create amp-autocomplete-email sample

- playground/src/state-view/state-view.js
- playground/src/state-view/state-view.scss
Similar to the Chrome Dev tools, state changes are now highlighted
> ✨ Highlight amp-state changes in playground state tree view

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/amp_email_best_practices.md
This moves tips from [Gmail's documentation](https://developers.google.com/gmail/ampemail/tips) that aren't Gmail-specific and are useful for other email clients.
> Update AMP for Email best practices

- platform/config/go-links.yaml
Update to 'main' branch.
Discovered in a comment on https://www.youtube.com/watch?v=nOEXIcMdr_g. /cc @kristoferbaxter you also need to update http://bit.ly/amp-script-compat
> Fix go.amp.dev/amp-script-apis URL

- playground/src/app.js
- playground/src/template-dialog/base.js
Fixes defect template dialog for playground. The button creation fails due to a wrong check in app.js 
```
main.c0dd5a62e3e993142f13.js:1598 Uncaught ReferenceError: templateDialog is not defined
at HTMLDivElement.<anonymous> (main.c0dd5a62e3e993142f13.js:1598)
```
The other fix should really only affect a problem for development: if the sitemap is malformed or could not be fetched at all the template dialog did not open.
> 🐛 Fix template dialog in playground

- platform/lib/pipeline/componentReferenceImporter.js
The doc import failed because the version patterned matched
amp-story-360.
> Fix ref doc version pattern

- playground/backend/api.js
@sebastianbenz can you provide guidance on setting sensible limits? Currently requests to `*.amp.dev` would not be limited at all, all other hosts are allowed to be requested 10 times in 10 seconds before requests are blocked for 10 seconds.
Fetch requests are aborted as soon as file size is over 100KB - documents this size would probably render CodeMirror useless anyway.
All responses that don't have `content-type: text/html` set are also blocked.
> 🔒  Harden playground/validator fetch API

- examples/source/style-layout/How_to_support_Images_with_unknown_Dimensions.html
doc should point visitors to https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/control_layout/
> fixed broken link in example

- playground/backend/api.js
This removes the size-limit as it does fail compressed responses, which is a known limitation in node-fetch.
> 🐛 Remove size limit playground fetch API

- frontend/templates/layouts/default.j2
- pages/translations/ar/LC_MESSAGES/messages.po
- pages/translations/de/LC_MESSAGES/messages.po
- pages/translations/es/LC_MESSAGES/messages.po
- pages/translations/fr/LC_MESSAGES/messages.po
- pages/translations/id/LC_MESSAGES/messages.po
- pages/translations/it/LC_MESSAGES/messages.po
- pages/translations/ja/LC_MESSAGES/messages.po
- pages/translations/ko/LC_MESSAGES/messages.po
- pages/translations/messages.po
- pages/translations/pl/LC_MESSAGES/messages.po
- pages/translations/pt_BR/LC_MESSAGES/messages.po
- pages/translations/ru/LC_MESSAGES/messages.po
- pages/translations/tr/LC_MESSAGES/messages.po
- pages/translations/vi/LC_MESSAGES/messages.po
- pages/translations/zh_CN/LC_MESSAGES/messages.po
__Pleaceholder issue to detemine correct path__
Since we are not crowdsourcing the upcoming translations, I want to do something about the banner.
In theory, the automated nature of gitlocalize means that there won't be pages that are untranslated, and therefore this message should never be shown. I am not sure if we want to keep this banner as a backup. 
If we _do_ keep it, I am not sure what the message would be - just an apology? a link to open an issue?
> remove request for help on banner shown when missing translations

- examples/source/1.components/amp-script/index.html
- examples/source/1.components/amp-script/static/hello-world.js
- platform/lib/samples/DocumentParser.js
Updated existing samples to match latest ways of educating folks about <amp-script> and to match changes in the way it works. Also made them each load in the playground independently.  And I added one new sample. Next I'll be adding some more...
Tried to keep <script> tags from being auto-beautified, without success.
We've now got 4 script hashes. I'm debating whether we should drop the script hashes and instead use `data-ampdevmode`. But I kind of feel like we should just keep adding script hashes to show how to do it.
> Overhaul of <amp-script> samples

- frontend/scss/_mixins.scss
- frontend/scss/components/atoms/copy-script.scss
- frontend/scss/components/molecules/code-snippet.scss
- frontend/scss/components/molecules/table-component.scss
- frontend/scss/components/organisms/_sidebar.scss
- frontend/scss/components/organisms/search.scss
- frontend/scss/components/organisms/toc.scss
Replaces #4261.
Hey @morsssss, the `@mixin scrollbar` was only used in the playground so far. I now updated the styling and made use of it throughout the whole project. To create variations (as seen in the screenshots below) the `@mixin` needs to be overwritten. I think for e.g. the `copy-script` it makes sense to leave the scrollbar at `height: 2px`?
> 💄 Adapt mixin for larger scrollbars

- pages/content/amp-dev/documentation/components/reference/amp-lightbox-v0.1@ru.md
fixes #3659
The page was not [valid AMP](https://validator.ampproject.org/#url=https%3A%2F%2Famp.dev%2Fru%2Fdocumentation%2Fcomponents%2Famp-lightbox%2F%3Fformat%3Dwebsites), the snippet intended to be a code sample was being rendered by the docs page.
> fix rendering issue on RU version of amp-lightbox docs

- pixi/src/pixi.hbs
> 🐛 Use absolute URL for pixi's amp-script src

- frontend/templates/views/detail/working-group-detail.j2
I did not test this fix manually.
The "Go to GitHub" link here is broken: https://amp.dev/community/working-groups/stories/
> Fix "Go to GitHub" working group link.

- pages/content/amp-dev/page-experience.html
- pages/translations/de/LC_MESSAGES/messages.po
- pixi/src/pixi.hbs
- pixi/src/ui/I18n.js
- pixi/src/ui/PageExperience.js
- pixi/src/ui/page-experience.hbs
- pixi/webpack.config.js
My idea was to use a prefilled AMP State to provide two things to Pixi: an object containing i18n strings which could be used in the JavaScript codebase like for example:
```js
this.label.textContent = i18n.passed;
```
and on the other hand the URL to check if it has been shared. But sadly the following returns `null`:
```js
AMP.getState().then((state) => {
console.log('AMP State', state);
});
```
Getting it on user-interaction as in this [AMP Playground demo](https://playground.amp.dev/#share=PCFkb2N0eXBlIGh0bWw+CjxodG1sIOKaoT4KPGhlYWQ+CiAgPG1ldGEgY2hhcnNldD0idXRmLTgiPgogIDx0aXRsZT5NeSBBTVAgUGFnZTwvdGl0bGU+CiAgPGxpbmsgcmVsPSJjYW5vbmljYWwiIGhyZWY9InNlbGYuaHRtbCIgLz4KICA8bWV0YSBuYW1lPSJ2aWV3cG9ydCIgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLG1pbmltdW0tc2NhbGU9MSxpbml0aWFsLXNjYWxlPTEiPgogIDxzdHlsZ …
> ✨ Create i18n util for Pixi runtime translations

- package.json
Pixi tests are currently ran twice as `test:platform` was testing packages outside its described target.
> 🎨  Restructure package.json test scripts and don't run Pixi tests twice

- pixi/src/checks/AmpLinterCheck.js
- pixi/src/ui/PageExperience.js
It looks like the HTTPS check always hangs because the AMP linter does not return a `url` property (surfacing as `Cannot read property 'startsWith' of undefined`), and the UI does not update when the error surfaces. For now this PR (1) updates the error message and (2) allows it to fail if `apiResult.url` is `undefined` /cc @tharders
> Allow HTTPS check to report `Analysis failed`

- frontend/scss/components/organisms/pixi-recommendations.scss
- pixi/src/checks/AmpLinterCheck.js
- pixi/src/checks/AmpLinterCheck.test.js
- pixi/src/checks/SafeBrowsingCheck.js
- pixi/src/checks/SafeBrowsingCheck.test.js
- pixi/src/ui/PageExperience.js
- pixi/src/ui/recommendations/RecommendationsView.js
- One common error is cannot read property `result` of `undefined`, due to error cases for the Safe Browsing and HTTPS checks. In this case I return an empty `data` object `{}` to allow the "Analysis Failed" UI to surface.
- Recommendations are hidden during loading. It also looks like some of the flattened recommendations contain a few `undefined` entries so I disregarded those explicitly. We should dig more where they are coming from and consider disregarding any entries that do not have our expected properties (currently `id`, `title`, and `description`).
> Pixi: Cleanup runtime errors and edge cases

- platform/config/imports/componentReference.json
The `amp-youtube` reference doc is corrupt, which breaks the build - @patrickkettner already did the required fixes in https://github.com/ampproject/amphtml/commit/7a07338fd83ddcaafb2fb5c9f57a4a50474f4c5c we now just need to import the doc from `master`...
> 🔧  Fetch amp-youtube from master

- thumbor/Dockerfile
- thumbor/app.yaml
It has been the logs that made the thumbor instances unresponsive:
```
2020-07-28 07:40:13.607 MESZ
[ERROR:serialization_utils.cc(304)] error writing output: No space left on device (28)
2020-07-28 07:40:15.005 MESZ
time="2020-07-28T05:40:15.005186180Z" level=error msg="Failed to log msg \"\" for logger json-file: write /var/lib/docker/containers/9a43cf850db23e35a0c3a014d6f52924f89acbc8853becb75a7e8440aa8eb3c7/9a43cf850db23e35a0c3a014d6f52924f89acbc8853becb75a7e8440aa8eb3c7-json.log: no space left on device"
```
thumbor doesn't use rotating logs but recommends to send logs to something like Sentry. I reduced the amount of logs - currently its ~14 lines for every request with log level `debug`:
```
A 2020-07-30T20:11:26.426142500Z 2020-07-30 20:11:26 thumbor:DEBUG METRICS: timing: …
```
> 🔧 Increase disk size for thumbor instances and make logs less verbose

- pages/content/pixi/status-banners/no-amp.md
- pixi/backend/api.js
- pixi/backend/api.test.js
- pixi/mocks/ampLinterCheck/apiResponse.js
- pixi/src/checks/AmpLinterCheck.js
- pixi/src/checks/AmpLinterCheck.test.js
The linter api now first checks if the page is a declared AMP page and only if that is true the linter checks are executed.
This PR also has the imported release schedule updated, which I did not really want to include here, but should do no harm.
> Add isAmp check to linter api

- pixi/src/checks/PageExperienceCheck.js
Without this parameter, it defaults to desktop results.
> Pixi: Get performance insights for mobile devices

- pixi/mocks/ampLinterCheck/apiResponse.js
- pixi/src/checkAggregation/recommendations.test.js
- pixi/src/checkAggregation/statusBanner.js
- pixi/src/checkAggregation/statusBanner.test.js
- pixi/src/checks/AmpLinterCheck.js
- pixi/src/checks/AmpLinterCheck.test.js
Basic pixi status banner rules
Changed AmpLinterCheck to not throw when the url could not be loaded in order to handle this case like any other check.
Also added unit test for recommendations rules.
The status banner rules are currently not used in the frontend.
> Pixi status banner rules

- frontend/scss/components/molecules/pixi-status-intro.scss
- frontend/scss/components/templates/pixi.scss
- frontend/templates/views/partials/banner.j2
- frontend/templates/views/partials/pixi/input-bar.j2
- frontend/templates/views/partials/pixi/status-intro.j2
- Adds aria labels to the input bar and site-level survey banner.
- Replaces `h4` with `h3` to follow sequential hierarchy of heading importance.
- LH score prior to these changes was 84 and 97 after:
The first is regarding color contrast of the white text over the gradient background. Lighthouse cannot detect the color contrast of text over image, therefore it assumes the text (white) is over the page's off-white `background-color`, resulting in a very low contrast of 1.04. 
While the automated score fails this, the actual manual check reveals that the score is about 5.64 (more than sufficient) in the deepest blue and 2.33 in the lightest. For accessibility purposes I changed the gradient ratio such that the lightest portion underneath white text will have at least a 3:1 ratio region to …
> Pixi: Accessibility improvements

- platform/config/environments/local.json
- platform/config/environments/production.json
- platform/config/environments/staging.json
I couldn't test this locally because I hit an error being emitted by AMP Optimizer. Don't know if others are having this issue or not. Is there a missing `}` in the CSS?
Regardless, I did test this locally and I think it will fix https://github.com/ampproject/amp.dev/issues/4457 .
Let me know though if something in my environment might be causing this error :)
```
AMP Optimizer SeparateKeyframes WARNING Failed to process CSS f.charCodeAt is not a function
[7:23:49 PM] › ✖  error     [OPTIMIZER] { CssSyntaxError: <css input>:49:7: Unclosed block
at Input.error (/Users/morss/Sites/docs/node_modules/rcs-core/node_modules/postcss/lib/input.js:130:16)
at Parser.unclosedBlock (/Users/morss/Sites/docs/node_modules/rcs-core/node_modules/postcss/lib/parser.js:572:22)
at Parser.endFile …
```
> ws=>wss scheme for websockets

- frontend/templates/views/partials/pixi/basic-metric.j2
- frontend/templates/views/partials/pixi/primary-checks.j2
- frontend/templates/views/partials/pixi/primary-metric.j2
- frontend/templates/views/partials/pixi/tooltip.j2
This fixes a bug where the lab data tooltips for `LCP` and `CLS` are toggling the tooltip elements associated with their field data counterparts.
> Pixi: Give tooltip elements unique ids

- frontend/scss/components/organisms/pixi-recommendations.scss
- frontend/scss/components/templates/pixi.scss
This gives the recommendations `section` a paddingTop so that when we scroll to it, it gets shown below the amp.dev site header.
> Pixi: Adjust padding for scrollTo recommendations

- pages/content/pixi/recommendations/intrusive-interstitials.md
When testing a site that has a failure, the language of the current version seems to imply that the scanner has found intrusive interstitials. It seems as though it was very easily become confusing as to what was being refer to to someone who doesn't know that we are not actually scanning for this.
> make intrusive interstitial warning more explict about not scanning

- pixi/mocks/pageExperienceCheck/reportData.json
- pixi/mocks/pageExperienceCheck/reportDataErrors.json
- pixi/mocks/pageExperienceCheck/reportDataNoFieldData.json
- pixi/src/checkAggregation/statusBanner.js
- pixi/src/checkAggregation/statusBanner.test.js
- pixi/src/checks/PageExperienceCheck.js
Prior to this PR, the `isAllFast` property equally considered field and lab data results. This PR modifies the status return to differentiate between the findings from field data and the findings from lab data, in order to more directly compare them across cached and origin versions of a page.
We want to surface results in the following way:
- Prioritize whether a given origin page has returned field data. If so, this should be used to resolve the final status without consideration for its lab data.
- Compare origin field data only to cache field data, and origin lab data only to cache lab data. 
Using the above principles, if an origin page returns field data and its cache page does not, the only statuses we might render passing or failing, no cache-to-origin comparison info in the final …
> Pixi: Granular status resolution of cache and origin data

- pixi/src/checkAggregation/statusBanner.js
- pixi/src/checkAggregation/statusBanner.test.js
It seems kind of confusing to show the invalid AMP status while tests are still running, as well as with recommendations still on the way. This way, even though we know a page is invalid, the user can still keep up with progress.
> Pixi: Display invalid AMP status after other tests have run.

- package.json
- pages/content/pixi/status-banners/amp-cache-url.md
- pixi/backend/api.js
- pixi/backend/api.test.js
- pixi/mocks/ampLinterCheck/apiResponse.js
- pixi/src/checkAggregation/statusBanner.js
- pixi/src/checkAggregation/statusBanner.test.js
- pixi/src/checks/AmpLinterCheck.js
- pixi/src/checks/AmpLinterCheck.test.js
- pixi/src/ui/InputBar.js
- pixi/src/ui/PageExperience.js
The check is implemented in the linter backend api as isCacheUrl.
The frontend linter check component translates this into isNotCacheURL to have all successful checks "true".
The difference is mostly due to the fact that we use the prod api on stage and with this setup pixi will not show the "cache url" status when the new flag is not in the linter api response.
So having said that, **please remember the linter will only show the "amp-cache-url" status in production mode (local or on stage) when this is deployed on prod.**
Fixes #4438
> Implement isCacheUrl check and rule for status banner

- examples/source/1.components/amp-script/index.html
Fixes CSS error in amp-script samples.
This actually doesn't affect the main samples page. But if you pull an individual sample into the playground, the error isn't corrected.
> Fix CSS error

- pixi/src/ui/InputBar.js
This is related to https://github.com/ampproject/amp.dev/issues/4477 and the URLs Patrick send should validate now.
But maybe we want to keep the ticket open until we have a final decision if we can use the URL class or not.
> Pixi URL validation allows URLs with %

- frontend/scss/_variables.scss
- frontend/scss/components/atoms/pill.scss
- frontend/scss/components/atoms/pixi-scale.scss
- frontend/scss/components/molecules/input-bar.scss
- frontend/scss/components/molecules/pixi-basic-metric.scss
- frontend/scss/components/molecules/pixi-primary-metric.scss
- frontend/scss/components/molecules/pixi-recommendations-item.scss
- frontend/scss/components/molecules/pixi-share-dialog.scss
- frontend/scss/components/molecules/pixi-status-intro.scss
- frontend/scss/components/molecules/pixi-tooltip.scss
Fixes #4487, fixes #4509, fixes #4488, fixes #4506, addresses #4501 (but need verification of fix)
Prior contrast (See input bar and button as example):
Increased contrast:
Increased contrast performance-based colors (orange and green):
> Pixi: Increase contrast in CSS

- frontend/scss/components/molecules/pixi-primary-metric.scss
- frontend/templates/views/partials/pixi/primary-metric.j2
- pages/content/pixi/index.md
- pixi/src/ui/recommendations/RecommendationsView.js
- pixi/src/ui/report/CoreWebVitalsReportView.js
The "Take action" text updates with the following when there are 0 recommendations surfaced for a given category:
- Good status => "Nothing to do"
- Else => "File an issue with AMP" + link to GH issue template
This PR also:
- Removes AMP action `scrollTo` in favor of header hyperlink. This fixes #4505
> Pixi: Display messages for 0 recommendations

- frontend/templates/layouts/default.j2
- playground/src/index.hbs
`font-display: swap;` is already set, this simply removes the preload statements.
> ⚡️ Stop preloading fonts in favor of font-display: swap

- pages/content/amp-dev/page-experience.html
- pixi/src/ui/StatusIntroView.js
- pixi/src/ui/recommendations/RecommendationsView.js
**summary**
Fixes: https://github.com/ampproject/amp.dev/issues/4522
The status quo is that recommendation text is written by amp.dev authors in markdown. The markdown is stringified and thrown into a [json map](https://github.com/ampproject/amp.dev/blob/b6e17cef6d530146a6a10a48d3d9b6ceb5b07931/pages/content/amp-dev/page-experience.html#L23-L33), then inserted as `<amp-state>` in the page. If the analyzer api returns that the site deserves said recommendations, it'll run the appropriate rules [through marked](https://github.com/ampproject/amp.dev/blob/de5892187a2fc6ce8d39a2375ffdec3b494fb49d/pixi/src/ui/recommendations/RecommendationsView.js#L88-L89). Due to the convergence of [marked encoding html entities](https://github.com/markedjs/marked/issues/1737) and `worker-dom` [not supporting …
> pixi: remove marked from client. transform in jinja

- frontend/templates/views/partials/pixi/share-dialog.j2
- frontend/templates/views/partials/pixi/status-intro.j2
- pages/content/pixi/index.md
- pixi/src/ui/StatusIntroView.js
This PR will update the "Fix It Now" button to an anchor link instead of an AMP `scrollTo` action to the same header element. The share button dialog contents will also now be appropriately focusable.
Fixes #4498, fixes #4493
> Pixi: Improve accessibility for status buttons

- frontend/scss/components/molecules/pixi-recommendations-item.scss
fixes #4567
marked wraps stuff in a `<p>` by default, so [this change](https://github.com/ampproject/amp.dev/pull/4563/files#diff-0b2fa57cd60a2e58bc20dd3389c45111L88) broke it
> keep pixi rec titles bold

- frontend/scss/components/molecules/pixi-tooltip.scss
- frontend/templates/views/partials/pixi/tooltip.j2
- pages/content/pixi/index.md
Partial for #4500
This PR:
- Adds labels the open/close dialog buttons for info tips
- Hides the closed buttons from screen reader focus
- Focuses automatically on "Close" button after pressing "Open" and vice-versa
Still need to be done from #4500:
1. `the question mark button should not be focusable when the popup is open`
2. `It should not be possible to move keyboard focus outside the popup without the popup closing.`
I believe addressing (2) will also fix (1), by virtue of the question mark button being outside the popup. @robinvanopstal @matthiasrohmer For the above missing pieces, it seems we may have to register an event handler to do this. Are you familiar with any ways to track focus using just AMP HTML?
> Pixi: Manage info tip focus

- examples/source/1.components/amp-script/index.html
Fixed bug where one `<amp-script>` sample could break another one. And then made one sample more fun!
> Improving amp-script samples

- frontend/templates/views/partials/footer.j2
The AMP blog is no longer located at amphtml.wordpress.com. The footer link needs to now point to blog.amp.dev. This is where users are redirected to anyway.
> Update link to AMP blog

- pixi/src/ui/PageExperience.js
- pixi/src/ui/StatusIntroView.js
- pixi/src/ui/recommendations/RecommendationsView.js
- pixi/src/utils/texts.js
- pixi/src/utils/texts.test.js
All links in recommendations and the status banner will open with target _blank.
Fixes #4573 
Also the "Publish valid cached AMP" recommendation now opens the validator URL with the submitted url.
> Open links in new tab and replace checked url placeholder in links

- frontend/scss/components/molecules/pixi-status-intro.scss
This fixes the original a11y issue addressed in #4559 through another means, as well as hides the resurfaced loading banner that was an unintended bug from #4559 (notice how it looks like there are two white cards at the bottom):
@matthiasrohmer Can you confirm if this also fixes the transitions?
> Pixi: Hide status texts with visibility property

- examples/source/1.components/amp-selector.html
Selected elements should have an indication that it is on focus for a11y.
WebAIM suggests to avoid using `Avoid outline:0 or similar styles on links and other elements that can receive keyboard focus.`
Full description is below.
> **Focus indicators**
> A keyboard user typically uses the Tab key to navigate through interactive elements on a web page—links, buttons, fields for inputting text, etc. When an item has keyboard "focus", it can be activated or manipulated with the keyboard. A sighted keyboard user must be provided with a visual indicator of the element that currently has keyboard focus. A basic focus indicator is provided automatically by the web browser and is typically shown as a border (called an outline) around the focused element. However, these outlines can be hidden by …
> a11y radio-selector

- pixi/src/ui/I18n.js
- pixi/src/ui/StatusIntroView.js
Had no luck reproducing #4458 specifically but my best guess is that `AMP.getState` sometimes throws instead of returning something. We've guarded this for the `InputBar` but didn't for the other occurrences until now.
> 🐛 Do not take AMP.getState returning something for granted in Pixi

- pixi/src/ui/report/CoreWebVitalsReportView.js
This PR also checks for a score of `=== 100` not `> 100` for the `V` indicator to go `>`. Fixes #4616
> Pixi: Reset styles in lab data scales between runs

- frontend/templates/views/partials/pixi/status-intro.j2
- pixi/src/ui/StatusIntroView.js
Add `data-cta` attribute to the targeted anchor elements we want to modify. This fixes #4602, which was a consequence of the inline text having a hyperlink of its own (to PSI).
> Pixi: Correctly identify CTA buttons

- frontend/scss/components/molecules/pixi-primary-metric.scss
> Pixi: Hide metric elements for field data error state

- pixi/src/utils/texts.js
- pixi/src/utils/texts.test.js
- platform/lib/routers/growPages.js
This fixes AMP to RTV 002009190410000 where https://github.com/ampproject/amphtml/issues/27153 should be fixed. Quick test I've done with `<test>` in one of the recommendations worked fine.
> ♻️ Stop replacing HTML entities in Pixi

- frontend/scss/_mixins.scss
- playground/src/app.critical.scss
- playground/src/fly-in/fly-in.scss
- playground/src/import-url/import-url.scss
- playground/src/input-bar/input-bar.scss
- playground/src/loader/loader.critical.scss
- playground/src/loader/loading-indicator.scss
> 🐛  Remove deprecated loading indicator to prevent duplicated CSS

- pixi/src/ui/report/CoreWebVitalsReportView.js
Prior to this PR the comparison to surface "Nothing to do" versus "File an issue on GH" for individual metrics' "Take action" field -- we are checking `"Fast" === "fast"` which always failed... Now we are comparing the correct lowercase, non-translated value. :) 
Fixes #4619
> Pixi: Surface "Nothing to do" for good performing metrics with no recommendations

- frontend/scss/components/molecules/pixi-recommendations-item.scss
Fixes
```
[20:19:14] Finished 'templates' after 550 ms
[20:19:14] Finished 'icons' after 582 ms
WARNING: Unknown `boulder` in $colors.
on line 12 of frontend/scss/_functions.scss, in function `color`
from line 87 of frontend/scss/components/molecules/pixi-recommendations-item.scss
```
> 🐛 Use safe light-gray instead of removed boulder color

- pages/content/pixi/status-banners/cache-failed-no-info.md
- pages/content/pixi/status-banners/cache-failed-with-info.md
- pages/content/pixi/status-banners/failed-no-info.md
- pages/content/pixi/status-banners/failed-with-info.md
Fixes #4662
- Also removes `since` from the other edited files wherein it was making it not a sentence.
> Pixi: Remove GH issue link from status when there are recommendations to give

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-email-actions-and-events.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-format.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-managing-user-state.md
- pages/content/amp-dev/support/index.md
- pages/shared/data/recent-guides.yaml
- platform/lib/tools/growReferenceChecker.js
Currently imported documents can break amp.dev's build if they contain invalid anchors. This problem extends to translated documents as they are not checked for integrity during translation.
This PR updates all imported documents and lets translated documents (containing a `@` in their filename) bypass the checks.
> 🎨 Let remote documents not break build

- frontend/templates/views/partials/pixi/input-bar.j2
Fixes #4641. Currently browsers would show input history for all fields named `url` - giving it distinct name should fix it while keeping the user-benefit of autocomplete.
> 🚸 Use distinct name attribute for Pixi input bar

- pixi/src/ui/PageExperience.js
- pixi/src/ui/StatusIntroView.js
- pixi/src/utils/checkAggregation/statusBanner.js
- pixi/src/utils/checkAggregation/statusBanner.test.js
This PR makes the linter check blocking and prevents other checks from running if it fails. This fixes #4669 and fixes that the "Fix it now" button is visible even if no further results are shown.
> ♻️ Run linter check first and in blocking manner for Pixi

- frontend/templates/views/partials/pixi/tooltip.j2
Prior to this change it has been defaulting to "null"
> Pixi: Tooltip aria-expanded value should default to "false"

- pixi/src/ui/recommendations/RecommendationsView.js
> ♿️ Set aria expanded on recommendation header

- pixi/src/checks/constants.js
- pixi/src/utils/checkAggregation/recommendations.js
- pixi/src/utils/checkAggregation/statusBanner.js
- pixi/webpack.config.js
This disables babel transpilations for Pixi as all JS features we are using (`async`/`await` mainly) are gracefully handled by Closure Compiler already. This brought down bundle size from 110 KiB to 98.7 KiB.
Additionally this PR enables CCs' `AGGRESSIVE_BUNDLE` mode which surprisingly didn't require much work. Savings aren't that big though, it brought down bundle size to 98.2 KiB with slight DX degredations.
We could even further bring it down to by only supporting ES2015 capable browsers (82.4KB) but this would exclude IE11.
Biggest optimization would be to get rid of `marked` though, without it and ES2015+ browser support we would land at 48.6 KiB. Creating a follow-up issue to discuss this.
> 🔧  Enable AGGRESSIVE_BUNDLE for Pixi build

- frontend/templates/views/partials/pixi/share-dialog.j2
- pages/content/shared/copy-pixi-url.html
- pixi/src/ui/StatusIntroView.js
Fixes #4458. Even if `AMP.setState` fails the sharing URL would now never be empty.
> ♻️ Do not rely on AMP.getState to get Pixi sharing URL

- pixi/mocks/pageExperienceCheck/apiResponse.json
- pixi/mocks/pageExperienceCheck/reportData.json
- pixi/src/checks/PageExperienceCheck.js
- pixi/src/ui/I18n.js
- pixi/src/ui/PageExperience.js
- pixi/src/ui/recommendations/RecommendationsView.js
- pixi/src/utils/checkAggregation/recommendations.js
Adds needed functionality to pass Lighthouse audit details through to the recommendation view and there rudimentarily renders them.
Works towards #4666.
> ✨ Render resource hints in related recommendations

- frontend/scss/components/molecules/pixi-basic-metric.scss
- frontend/scss/components/molecules/pixi-recommendations-item.scss
- frontend/scss/components/molecules/pixi-status-intro.scss
- frontend/scss/components/organisms/pixi-primary-checks.scss
- frontend/scss/components/templates/pixi.scss
- frontend/templates/views/partials/pixi/basic-metric.j2
- frontend/templates/views/partials/pixi/primary-checks.j2
- frontend/templates/views/partials/pixi/recommendations-item.j2
- frontend/templates/views/partials/pixi/status-intro.j2
- pages/content/amp-dev/page-experience.html
Partial for #4379, which will be fixed once both this and #4702 are merged.
Desktop:
Mobile:
> Pixi: Support RTL direction on full page

- frontend/scss/components/molecules/pixi-primary-metric.scss
- frontend/templates/views/partials/pixi/primary-metric.j2
Fixes #4545
Desktop view with 1607 x 813 inner window size:
Desktop view with 790 x 813 inner window size:
Mobile view with 360 x 640:
> Pixi: Put metric title and summary in one line

- pages/content/pixi/status-banners/generic-error.md
- pixi/src/utils/checkAggregation/statusBanner.js
Otherwise, in the case that the linter response fails, we were originally surfacing "This page is invalid AMP". Tagging #4765 as this is a change in copy.
Now we surface:
> Pixi: Surface generic error before other linter information

- frontend/scss/components/organisms/burger-menu.scss
- frontend/templates/views/partials/banner.j2
- frontend/templates/views/partials/header.j2
This puts up the banner for AMP Fest.
Note that, to avoid layout problems, I had to undo the work that was done to put up the BLM banner in https://github.com/ampproject/amp.dev/pull/4235 - as that PR wasn't compatible with other banner sizes. Going forward, we need to make the header more flexible so that it can accommodate banners of different sizes!
> Banner for AMP Fest

- platform/config/go-links.yaml
We have about 4 shortlinks for the optimizer guide, but none for the really useful [guide to speeding up AMP pages yourself](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/optimize_amp). I need a shortlink for a talk... I hope it's ok to switch this one! It's named ideally for the optimize_amp page....
> Change shortlink for optimize-amp

- smoke-tests/platform/Routes.test.js
This would have prevented https://github.com/ampproject/amp.dev/pull/4792. Before a build goes live on amp-dev-staging.appspot.com or amp.dev itself it now needs to be able to serve a AMP-valid version of Pixi, otherwise it blocks build.
> ✅  Add Pixi to smoke tested pages

- frontend/templates/views/custom.j2
- frontend/templates/views/pixi.j2
- pages/content/amp-dev/page-experience.html
- pixi/src/ui/page-experience.hbs
- pixi/webpack.config.js
Sorry, had a misconception that the AMP optimizer will add the hash, but it only does so for inline-scripts.
Fixes #4813, probably related to https://github.com/ampproject/amp.dev/issues/4818#issuecomment-705389563.
> ✨ Render amp-script hash to Pixi template

- frontend/templates/layouts/sitemap.xml
Currently https://amp.dev/sitemap_grow.xml points to URLs with amp-dev-staging.appspot.com as we did not add a monkey-patch for hostnames in Grow. That's not a problem anywhere else as the sitemap is the only place where we've used `doc.url`
> 🐛 Explicitly use platform URL for sitemap generation

- frontend/templates/views/partials/header.j2
- pages/content/amp-dev/events/amp-fest-2020.html
Added carousels of videos, removed almost everything else.
Also removed the AMP Fest banner.
Note that we need to restore the BLM banner! I just wanted to get this PR out quickly this evening.
> Switch AMP Fest page to post-event state

- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ar.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@es.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@fr.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@id.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@it.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ja.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ko.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@pt_BR.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@ru.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@tr.md
- pages/content/amp-dev/documentation/components/reference/amp-ad-v0.1@zh_CN.md
Currently AJA only supports &lt;amp-ad&gt;.
So move from embed-types to ad-types.
Ref: https://github.com/ampproject/amphtml/blob/master/ads/aja.md
> move AJA from embed to ad

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/cors-in-email.md
This logic/syntax may be used as a reference when utilizing `SSJS` within `SFMC` to setup `JSON` code resources.
> Adding SSJS CORS Header example

- platform/lib/utils/rateLimitedFetch.js
- platform/lib/utils/rateLimitedFetch.test.js
Related to https://github.com/ampproject/amp.dev/issues/4887
Currently the linter API makes error when passed AMP page URL doesn't have `Content-Type` header. This change handle the error case.
> Fix linter API to handle the response without Content-Type header field

- pixi/src/checks/PageExperienceCheck.js
- pixi/src/ui/recommendations/RecommendationItem.js
Fixes #4955.
This force-renders recommendations for Pixi even if the underlying PSI check finishes with a score of 1 as long as it provides further details like response times, resource sizes, etc.
> 🚸 Show passing recommendations if there are details

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer.md
The example for the `transformed` flag is not using a version string (`;v=1`), which seems to be invalid according to the AMP validator.
> Fix invalid transformed example

- frontend/scss/components/atoms/sidebar-toggle.scss
The sidebar toggle on click/focus outlines only the label-icon:
I improved the click behavior to encompass the whole label:
GIFs from Chrome
> better click behavior

- pages/content/amp-dev/documentation/courses/beginning-course/finding-the-right-component.md
- pages/content/amp-dev/documentation/courses/beginning-course/finding-the-right-component@pt_BR.md
The HTML output contained the word "code" and htmlentities. Removed markdown code markers, and replaced hyphen with something similar to avoid line break.
@matthiasrohmer , what I've done here is pretty hacky... "<amp-carousel>" was breaking at the hyphen in the Portuguese version, and when I tried an htmlentity for a nonbreaking hyphen, that was output literally. So I used a Unicode character that resembles a hyphen. This is not what we'd call a best practice :)
I wonder if we'd consider letting picture captions be wider than 300 px. That would solve this problem too.
> Fixed captions

- examples/source/1.components/amp-social-share.html
The Web Share API is now supported on iOS (Safari + Chrome), Desktop Safari, and many other browsers (acc. to https://caniuse.com/web-share roughly 90% of mobile traffic).
Updating the docs to make that clearer. As so many browsers support, not sure we need to list them individually.
> AMP Social Share Docs

- examples/source/2.guides/Using_the_AMP_URL_API.html
- examples/static/samples/files/amp-url-api.html
Fixes #4920
/cc @patrickkettner, @caroqliu: the API key is still scoped to ampbyexample.com and prevents the sample from working. I can't seem to find the matching API in the Cloud Console though. Can one of you advise?
> 🐛 Update AMP URL API sample iframe URL

- package.json
package was added in a4fc6ce2d4046581005385ba9f4e855c8d030401, but was never actually used.
> remove unused package

- playground/src/error-list/error-list-item.hbs
> 🐛 Playground: Only render a learn more link if a URL exists

- package-lock.json
- package.json
- platform/lib/middleware/csp.js
- platform/lib/platform.js
- platform/lib/routers/cspReport.js
Turn on the [reporting](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only), rather than blocking, in CSP, so we can audit potential issues
https://csp-collector.appspot.com/csp/amp is listed as a the endpoint, which is the csp report collector for @ampproject, probably should use a different endpoint?
> use CSP reporting endpoint

- examples/source/1.components/amp-next-page.html
amp-next-page JSON config requires the URL to be on the same origin.
Fixes #4319
> Fix amp-next-page example

- gulpfile.js/build.js
- gulpfile.js/import/importRoadmap.js
- gulpfile.js/import/importWorkingGroups.js
- gulpfile.js/lint.js
- package-lock.json
- package.json
- platform/lib/build/samplesBuilder.js
- platform/lib/config.js
- platform/lib/middleware/redirects.js
- platform/lib/middleware/redirects.test.js
- platform/lib/pipeline/markdownDocument.js
- platform/lib/pipeline/recentGuides.js
- platform/lib/routers/go.js
- platform/lib/routers/go.test.js
- platform/lib/routers/whoAmI.js
- platform/lib/samples/DocumentParser.js
- platform/lib/utils/pageCache.js
Replaces #5155 following the [migration guide](https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md).
> 📌  Update to js-yaml 4 and replace safe prefix from yaml methods

- platform/lib/pipeline/componentReferenceImporter.js
Before, only component docs where pulled from master, but not the
directory structure.
> Fix component doc import from master

- pixi/src/utils/checkAggregation/statusBanner.js
- pixi/webpack.config.js
Fixes #5205. `cacheExperience[dataType]` is either an object or `null` but never undefined.
The webpack config changes are not closely related to this bug but any of the latest updates to either the `CleanWebpackPlugin` or `FileManagerPlugin` caused a race condition that delete the created bundles before they can get copied to where express can find them.
> 🐛 Pixi: Check for falsy value instead of undefined specifically

- platform/config/imports/componentReference.json
- platform/lib/pipeline/componentReferenceDocument.js
- platform/lib/pipeline/componentReferenceImporter.js
This reverts various changes done to the component reference importer and related stuff to get the state on `future` back in a healthy, deployable state.
PR reintroducing the changes done to have the bento docs live upcoming.
> ⏪  Revert changes to component reference importer

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/monetization/content_encryption.md
Tink for JavaScript only works in a browser environment, not in Node.js. Furthermore, it is in an extremely alpha-quality state, largely undocumented, and people shouldn't be directed to it at this point in its development unless they want to brave a lot of sharp edges.
I added Python to the list instead, since support for that is more mature.
If the AMP Project considers Tink Node.js support important for the AMP ecosystem, let me know and I'll see what we can do. There might not be much movement until March, though.
> Remove JavaScript from Tink-supported languages

- frontend/scss/_variables.scss
- frontend/scss/components/atoms/pill.scss
- frontend/templates/views/partials/component-headline.j2
* Remove inline custom properties
* Create modifier class in CSS
* Fixes #5256
> 🐛 Fix amp-validation error caused by inline custom properties

- frontend/scss/components/atoms/copy-script.scss
- frontend/scss/components/organisms/component-intro.scss
- frontend/templates/views/partials/component-intro.j2
- pages/content/shared/copy-script.html
- platform/lib/pipeline/componentReferenceDocument.js
This adds a pill to the copy script for toggling between valid AMP and
Bento mode.
> Add bento js + CSS copy script

- pages/content/amp-dev/documentation/guides-and-tutorials/start/bento_guide.md
Always wait on `customElements.whenDefined` before trying to call `el.getApi()`. This is because `getApi` won't be defined _until_ the Custom Element implementation is registered with the page, which is inherently async.
/cc @CrystalOnScript
> Wait for whenDefined before using getApi

- pixi/backend/api.js
in #5207, I didn't actually import `fetch()`, so this has been throwing in production
> actually have a fetch() to call

- frontend/scss/components/molecules/rolling-formats.scss
As the LCP is being triggered around 3 seconds, and is localized to the header, I was thinking the rolling formats may be the culprit. If this is the case, having text show immediately, or elongating the time that the initial the word is shown could help?
> start rolling-formats mid animation to reduce change

- frontend/scss/components/molecules/code-snippet.scss
- frontend/scss/components/molecules/tip.scss
- frontend/scss/components/organisms/teaser-grid.scss
- frontend/scss/components/templates/_default.scss
- frontend/scss/components/templates/use-cases.scss
- frontend/scss/components/templates/what-is-amp.scss
- playground/src/fly-in/fly-in.scss
Here is a list of pages, that Google Search Console marked as mobile unfriendly:
* https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-managing-user-state/
* https://amp.dev/about/how-amp-works/
* https://amp.dev/zh_cn/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design/
* https://amp.dev/about/use-cases/
* https://playground.amp.dev/?runtime=amp4ads
* https://amp.dev/es/documentation/guides-and-tutorials/optimize-and-measure/amp-managing-user-state/
* https://playground.amp.dev/
* https://playground.amp.dev/embed
* https://amp.dev/id/documentation/guides-and-tutorials/learn/a4a_spec/
* https://amp.dev/es/documentation/guides-and-tutorials/learn/a4a_spec/
> 🚸 Mobile usability fixes

- examples/static/samples/files/copier.html
In iOS safari / chrome, keyboard was popped up after clicking the copy button.
Enable `readonly` mode on input tag
> Prevent keyboard popup in iOS

- examples/static/samples/files/copier.html
- examples/static/samples/internationalization/alternate/fr/index.amp.html
- examples/static/samples/internationalization/alternate/fr/index.html
- examples/static/samples/internationalization/alternate/fr/index.mobile.html
- examples/static/samples/internationalization/alternate/index.amp.html
- examples/static/samples/internationalization/alternate/index.html
- examples/static/samples/internationalization/alternate/index.mobile.html
- examples/static/samples/internationalization/alternate/ja/index.amp.html
- examples/static/samples/internationalization/alternate/ja/index.html
- examples/static/samples/internationalization/alternate/ja/index.mobile.html
- examples/static/samples/internationalization/basic/fr/index.amp.html
- examples/static/samples/internationalization/basic/fr/index.html
- examples/static/samples/internationalization/basic/index.amp.html
- examples/static/samples/internationalization/basic/index.html
- examples/static/samples/internationalization/basic/ja/index.amp.html
- examples/static/samples/internationalization/basic/ja/index.html
Add viewport tag:
- https://amp.dev/static/samples/files/copier.html
Handle overflow of ```pre```-Element:
- https://amp.dev/static/samples/internationalization/basic/index.html
- https://amp.dev/static/samples/internationalization/basic/index.amp.html
- https://amp.dev/static/samples/internationalization/basic/fr/index.html
- https://amp.dev/static/samples/internationalization/basic/fr/index.amp.html
- https://amp.dev/static/samples/internationalization/basic/ja/index.html
- https://amp.dev/static/samples/internationalization/basic/ja/index.amp.html
- https://amp.dev/static/samples/internationalization/alternate/index.html
- https://amp.dev/static/samples/internationalization/alternate/index.amp.html
- https://amp.dev/static/samples/internationalization/alternate/index.mobile.html
- …
> 📱 Mobile usability viewport fixes

- frontend/templates/views/partials/content.j2
This reverts commit e10fdf78b0da3e170a8bce20caa639288f14816a.
Adding the survey to content.j2 enables the survey for almost all pages (including non-doc pages). We should find a better approach to integrate it.
//cc @patrickkettner
> Revert "add a user survey (#5419)"

- pages/content/amp-dev/documentation/guides-and-tutorials/start/create/basic_markup.md
Add missing backtick in 'Create your AMP HTML page' tutorial.
> Fix formatting issue

- packager/Dockerfile
If using both AMP Packager and a 2.8.0 canary release of AMP Optimizer, there is a conflict that will lead to invalid AMP pages.
> Migrate to official packager docker image

- frontend21/webpack.config.js
- pixi/webpack.config.js
/cc @lluerich
This enables the same notifications as for the frontend to know when a build succeeded.
But in the first place this fixes not building the bundle incrementally for `npm run start:pixi`.
> 🚸  Fix errors around Pixi webpack dev config

- platform/lib/format-transform/formats/amp4email.js
fixes #5522 - the example has 
```js
<style amp-custom></style>
```
so the selector matches, but I hadn't done existence checks on the code because "...why would this exist?"
mea culpa
> make sure nodes exist before we access them

- frontend/scss/components/molecules/pixi-recommendations-item.scss
- pages/content/pixi/recommendations/viewport-disables-tap-delay.md
- pixi/src/ui/I18n.js
* Use `<code>` instead of `<pre>`
* Style `<code>` in recommendations
* Also use snarkdown instead of marked (saves 42kb)
Fixes #5417
> Pixi: Fix code snippet in tap deplay recommendation

- .github/workflows/check-grow-link-integrity.yaml
- .github/workflows/lint-js.yaml
- .github/workflows/lint-yaml.yaml
- .github/workflows/nightly.yaml
- .github/workflows/release-production.yaml
- .github/workflows/release-staging.yaml
- .github/workflows/test-grow-extensions.yaml
- .github/workflows/test-pixi.yaml
- .github/workflows/test-platform.yaml
- .github/workflows/test-playground.yaml
- README.md
This adapts the staging workflow for production. Also it updates the Node.js action to v2 and uses Node.js 14 across all workflows as this is the current LTS and not 12 anymore.
Additionally this adds a nightly workflow which is a workaround for the fact that the `schedule` trigger is only respected for workflows on the default branch. It will trigger releases for staging and production every morning at 8 to keep imported docs fresh.
> 🚀  Configure GitHub Actions workflows for production deployment and nightly releases

- .github/workflows/check-grow-link-integrity.yaml
- .github/workflows/lint-js.yaml
- .github/workflows/lint-yaml.yaml
- .github/workflows/release-production.yaml
- .github/workflows/release-staging.yaml
- .github/workflows/test-grow-extensions.yaml
- .github/workflows/test-pixi.yaml
- .github/workflows/test-platform.yaml
- .github/workflows/test-playground.yaml
This tries to enhance workflows: actually running the tests on `push` should be enough; we need to investigate if that works for PRs created after everything has been pushed.
Also this fixes the nightly workflow - the required triggers weren't allowed for the release workflows.
Additionally this tries to implement skipping for concurrent release jobs on `future`. As this is not a core feature we need to rely on a 3p action which has [confusing documentation](https://github.com/fkirc/skip-duplicate-actions/).
All in all: fingers crossed 😅
> 🎨  Further enhance GitHub workflows

- gulpfile.js/build.js
Since there are some duplicate components in the [validator.json](https://cdn.ampproject.org/v0/validator.json) the latest version was overwritten by a former version in at least one case (amp-carousel).
This should fix that and #5586.
> 🐛 Keep only latest component version

- .github/workflows/release-production.yaml
- .github/workflows/release-staging.yaml
Sebastian reported that samples are using `localhost` on prod. This was caused by `gulp buildPrepare` not having the correct `APP_ENV` set [as before on Travis](https://github.com/ampproject/amp.dev/commit/f2d63dce6498e34ac97ea51fdb4b3c4ee894abcb#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485L30).
> 🐛 Set APP_ENV for prepare step in release workflows

- .github/workflows/nightly.yaml
Nightly production builds currently [fail (scroll down to annotations)](https://github.com/ampproject/amp.dev/actions/runs/697111433) as they are build from `future` but should rather be build from `production-amp-dev`
> 🐛 Specify ref for nightly production builds

- .github/workflows/release-production.yaml
- .github/workflows/release-staging.yaml
> 🐛 Explicitly export AMP_DEV_PIXI_APIS_KEY in GitHub workflows

- .github/workflows/test-default.yml
PRs like #5612 are currently hung because we require a `test` job to pass in checks
but the existing workflows all filter on filename.
This PR adds a default workflow to run `npm test` on all PRs as the requisite `test` job. Since this should be run on [`pre-push`](https://github.com/ampproject/amp.dev/blob/future/.husky/pre-push#L4), this shouldn't ever really fail, but folks can force push a [`--no-verify`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify) to get around it locally, so 🤷‍♀️.
If it takes up too much time, we can change the `run` [bit](https://github.com/ampproject/amp.dev/commit/3aa34ffc8a5fa2b9d275c2aa3df9aa24174c2e12#diff-1b8368a50c1714fe9faf0dfd1bf766142f1f0bb1eedd48540fb4bdde0323f50dR29) to something like `exit 0` and it should work, just …
> add default workflow to run tests

- platform/lib/platform.js
- platform/lib/routers/surveyComponent.js
I pulled down the prod docker image, and for some reason when I use `.all` it adds the route to the router, but doesn't register it to any methods. As a result, production requests 404 for `fez-survey-requests`, but worked locally.
> use specific HTTP verbs instead of all for survey router config

- frontend/scss/components/molecules/format-filter-hint.scss
- frontend/scss/components/templates/_default.scss
- frontend/templates/views/partials/format-filter-hint.j2
- removed the format switcher inside the hint
- increase the space at the top of container to fit the hint
- set hint to ```position: absolute``` so that it does not cause CLS when closed
TODO:
- update copy
Fixes #5476
> 🚧  Update format switcher hint

- packager/Dockerfile
closes #5384
per [my question](https://github.com/ampproject/amp.dev/pull/5384#issuecomment-812065306), there _is_ [an issue  with 1.16](https://github.com/ampproject/amppackager/issues/494#issuecomment-781582947), but @​banaag [updated the amppacker](https://github.com/ampproject/amppackager/pull/497) docs with new instructions. Tested with the current certs, and this builds correctly.
> update amp packager to use Go 1.16

- Dockerfile
the survey isn't working in prod because the backend is calling `flat()`, which wasn't caught because out testing uses node lts. I assume this is an over sight?
> use the LTS version of node in prod

- platform/lib/build/samplesBuilder.js
fixes #4211
no idea if this is the "correct" way to go about this, or just a hack, but -  thoughts?
> filter out embed.html from examples in gulp glob

- package.json
Reverts ampproject/amp.dev#5613.
> Revert updating dependency p-queue to v7 due to ESM migration

- pixi/backend/api.js
currently its more difficult than it needs to be to get pixi search events, because they won't show up outside of realtime data without a category attached
> include event category in google analytics events for pixi

- gulpfile.js/build.js
fixes #5661
[Looks like they were removed](https://github.com/ampproject/amp.dev/commit/f2d63dce6498e34ac97ea51fdb4b3c4ee894abcb#diff-f6030ecaa81fe01c520f48d9593ec049587bbca33af2ab8c7e5fb006ffdd5d95L291) when we switched to github actions, not sure if that was intentional or not - @matthiasrohmer ?
> bring back templates

- pages/shared/data/faq.yaml
Added Salesforce to list of Email Platforms and Service Providers
AMP for Email was added to Salesforce in the January 2021 release https://www.salesforce.com/blog/amp-email-interactive/
> Added Salesforce to ESPs list

- smoke-tests/pixi/Run.e2e-test.js
The newly introduced tests currently fail inside the CI: https://github.com/ampproject/amp.dev/runs/2331487733?check_suite_focus=true#step:9:181
Timeouts being too small is more than a wild guess than an exact idea what's wrong though.
> 🔧 Increase timeouts for Pixi E2E tests

- .github/workflows/release-production.yaml
- .github/workflows/release-staging.yaml
Simply increasing the timeouts would have been too easy...
> 💩 Disable Pixi E2E tests in CI for further debugging

- platform/lib/platform.js
- platform/lib/routers/packager.js
The current version of amppackager is curently not compatbile to
optimized AMP + mjs runtime.
> Disable amppackager

- examples/source/user-consent/Granular_User_Consent.html
I did get an assertion failure while running pre-commit tests:
```
FAIL: test_attributes (amp_example_preview.util.example_document_test.SourceCodeExporterTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/morss/Sites/docs/pages/extensions/amp_example_preview/util/example_document_test.py", line 33, in test_attributes
self.assertEqual('0.1', example_doc.imports[1].version) # 0.1 is always the default
AssertionError: '0.1' != '1.0'
```
I imagine this is trying to tell me that I used v1.0 of a component instead of v0.1. As far as I know, though, I didn't. Maybe it's hitting something else in the repo, but, if so, the error doesn't tell me where.
Also... for some reason the reprompt UI isn't showing up on the …
> Granular consent sample

- package-lock.json
the staging build is currently failing because the cache hash is [based on a hash of `package-lock.json`](https://github.com/ampproject/amp.dev/blob/9f8b45577397f80b7b48c4c2e7fd5f5177c3506e/.github/workflows/release-staging.yaml#L39). I updated that file to unblock the build, and will follow up with a workflow change shortly to prevent it from happening again
> commit the package-lock file to update the hash used in actions

- frontend/scss/components/organisms/survey.scss
fixes #5717
@kristoferbaxter we have an amp-script component that shows the survey. It is loading multiple times as a result of `amp-next-page`. I created a PR to hide it via CSS if it is a descendant of of amp-next-page, but that feels fairly kludgey - is there a better way to detect/prevent this behavior?
> hide surveys when they are inside of amp-next-page

- platform/config/go-links.yaml
Adding a short link for the web player with the existing guide as a placeholder, will update the actual URL later.
> Add web player short link

- frontend/scss/components/organisms/survey.scss
- frontend/templates/views/partials/survey.j2
Remove CSS as targeting i-amphtml-* is invalid AMP. Use amp-next-page's
built-in `next-page-hide` element instead to make sure that surveys are
not repeated.
> Fix hide surveys when they are inside of amp-next-page

- README.md
doing builds locally sped up ~500% when it was added, should not make it seem quite as unimportant in the README
> add libyaml/pyYAML information to README, and make it a part of the default installation setup

- frontend/templates/views/2021/partials/extras/about/components-showcase.j2
- frontend21/scss/amp-dev.scss
- frontend21/scss/components/button.scss
- frontend21/scss/components/extra/about/components-showcase.scss
- pages/content/amp-dev/about/websites-2021.html
- pages/shared/components-showcase/amp-accordion.html
- pages/shared/components-showcase/amp-carousel.html
@dlemm, @lluerich: here's a solid starting point for the Grab and Go components section for the new [about websites](https://amp-dev-staging.appspot.com/about/websites-2021/) page:
> 🎉 Bootstrap components section for new about page

- platform/lib/routers/packager.js
Instead return at least the non SXG document.
> Don't fail with a 503 if packager instance is not available

- frontend21/scss/variables.scss
- frontend21/webpack.config.js
> Fix gulp develop warnings

- gulpfile.js/build.js
This should make the icons appear on the new about page.
> 🐛 Keep frontend21 static assets across build stages

- frontend21/webpack.config.js
- gulpfile.js/build.js
- gulpfile.js/develop.js
Follow-up to https://github.com/ampproject/amp.dev/pull/5846.
Didn't think about builds being sharded per locale on GitHub. This made the task break for all languages except English as the pages which should be copied don't exist for them. Sorry!
/cc @patrickkettner
> 🐛 Do not try to publish pages that haven't been build

- platform/config/go-links.yaml
- The I2I link has changed due to the adoption of a new yaml template (https://github.com/ampproject/amphtml/pull/34431)
- The getting-started link will be used by our PR template (https://github.com/ampproject/amphtml/pull/34473)
> Update a couple of go links

- platform/lib/format-transform/index.test.js
- platform/lib/pipeline/componentReferenceDocument.test.js
- platform/lib/pipeline/markdownDocument.test.js
That's a change needed to due a recent jest update which more strictly evaluates return values.
> 👽 Either use callbacks or promises for tests, not both

- frontend21/scss/components/home/formats.scss
In response of
```
(node:35283) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div(math.tan($skew-angle), 2)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
8 │   --skew-tan: #{math.tan($skew-angle) / 2};
│                 ^^^^^^^^^^^^^^^^^^^^^^^^^
╵
scss/components/home/formats.scss 8:17  @import
scss/amp-dev.scss 43:9                  root stylesheet
```
> 👽 Use new preferred division notation

- platform/lib/pipeline/componentReferenceImporter.js
Compare [L456](https://github.com/ampproject/amp.dev/runs/2713031896?check_suite_focus=true#step:10:456) to L457. This slipped #5870's review.
Without the `.html` in the serving path Grow creates files without an extension which don't get picked up by `gulp.src`.
> 🚑 Add file extension to component docs serving path

- frontend21/scss/amp-dev.scss
- platform/lib/utils/cssTransformer.js
This reduces CSS bundle size from ~78KB down to ~57KB for new Home, Get Started and About Websites.
A more sophisticated splitting approach would be nice though. The disabled components will only be needed for the refactored documentation detail page which is not used yet.
> 🎨 Remove currently unused CSS from new frontend bundle

- frontend21/scss/amp-dev.scss
Link styles overruled the special case for the newsletter due to the order in which they are imported.
Fixes #5998.
> 🐛 Fix order of imports

- frontend21/scss/components/content/link.scss
Fixes the ```:hover``` animation for square links.
> 🐛 Fix duplicate animation name

- frontend21/scss/amp-dev.scss
Fixes missing code examples on ```about/websites```.
Reverts this: https://github.com/ampproject/amp.dev/pull/5965/files#diff-b684e37d72ed1b64fc1c8cc9bf1a86366d64a0e05879877ff09cdc824f901c29L31
> ⏪  Add missing import

- examples/source/1.components/amp-render.html
- examples/static/samples/json/cities-lagos.json
- examples/static/samples/json/cities.json
Ok! I cut my more ambitious sample - showing how to do list-style pagination - because it turned out the approach I was taking with `amp-script` wouldn't have worked, as `amp-render` doesn't support the `refresh` action when data comes from `amp-script`. I could have done it in a different way, but I'm going to leave that for later.
I couldn't run pre-commit tests because some Pixi tests were failing. So this hasn't gone through the usual Prettier linting.
> New amp-render samples page

- frontend/scss/base.scss
We're inadvertently modifying and breaking [rendered code samples.](https://amp.dev/documentation/examples/components/amp-lightbox-gallery/?format=websites)
> Specify .amp-carousel-button so it does not pollute rendered sample

- frontend21/scss/components/content/teaser.scss
- pages/content/amp-dev/index-2021.html
Blog posts without title image did render without fallback image due to
mixing {{ }} and [= =] template literals by importing teaser.j2.
Brute force fix by duplicating teaser.j2 in index-2021.html.
> Fix invalid homepage

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting@ar.md
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting@es.md
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting@it.md
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting@ja.md
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting@ko.md
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting@pl.md
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting@vi.md
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting@zh_CN.md
- platform/lib/pipeline/componentReferenceDocument.test.js
- platform/lib/pipeline/componentReferenceImporter.js
Companion PR to https://github.com/ampproject/amphtml/pull/35139, which move `builtins/` to `src/builtins/`.
This PR updates documentation links to the `builtins/` folder.
Context: https://github.com/ampproject/amphtml/issues/34866
> Update references to amphtml/builtins

- platform/lib/utils/git.js
By the nature of our gulpfile the deployment tasks get required with every task run. The deployment tasks do some configuration on module level which also involves calling git commands. That failed.
Moving the configuration into a method would make the deploy task file less readable, hence I settled for the try/catch fallback.
Fixes #6067.
> 🐛 Make determination of commit SHA failable

- frontend/scss/base.scss
Fixes an issue where carousel button selectors for the host document pollutes rendered example snippets.
A followup to #6063, where I did not test that the exclusion selector actually worked. (I verified this time, apologies!)
This selector could be somewhat inefficient since it traverses up to `body`. Alternatively, we could scope it to the `amp-carousel` elements that we want by classname, but I'm not familiar with the parts of the `amp.dev` site that we would like to target.
> Specify namespace to avoid pollution, for real this time

- frontend21/scss/components/content/teaser-carousel.scss
- pages/content/amp-dev/index-2021.html
- set missing class caused by d5745d2999c26499e4b1fb49ab67450c76e677b2
- overrides the styles for this specific section caused by #6087
> 🐛 Fix teaser carousel styles

- pages/content/amp-dev/support/faq/supported-browsers.md
As part of Internet Explorer deprecation (code merge happened last week).
> Remove IE11 listed support

- pages/shared/data/cms.yaml
arcpublishing.com is now arcxp.com
> update arcxp URL

- playground/src/app.js
fix for #6216
Looks like when the modes stuff was updated in #4138, this wasn't.
> playground bugfix

- pages/content/amp-dev/documentation/courses/teachers.md
- pages/content/amp-dev/events/amp-roadshow.html
Changing roadshows page to make it more clear that we're not doing roadshows right now.
And removing my email address and language about certification program from the courses area.
> Update language on courses and roadshow

- platform/lib/routers/inlineExamples.js
This caused playground examples to show as optimized AMP.
> Disable optimizer for inline examples

- pages/shared/data/faq.yaml
Followup to https://github.com/ampproject/amp.dev/pull/6290
> Fix typo in "Salesforce MArketing Cloud"

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/email_fundamentals.md
It appears that this section was copied from the Gmail Email Markup
documentation:
https://developers.google.com/gmail/markup/actions/limited-use-access-tokens
The particular mention about one-time use of the token is specific to
the One Click Action feature of Email Markup:
https://developers.google.com/gmail/markup/actions/limited-use-access-tokens
I don't think we should have such restriction for AMP for Email. For
example, an email that allows users to reply to a comment thread inline
should be able to use the same token to perform reply multiple times. We
should let sender decide whether to make the token one-time use only.
/to @patrickkettner
> Update doc about one-time use access token

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/amp_email_best_practices.md
1. Currently the indentation of the sub-bullets are done using 2 spaces,
which apparently isn't enough to make them render as sub-bullets. We
need 4 spaces instead.
2. Fix the `byte limit on the size of the email` link. It's missing
`email-spec` in the path.
3. Make action and event and amp-bind links point to amp.dev links
instead of GitHub.
> Fix bullet indentation level and link URLs

- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/add-email.md
It looks like the original intention was to italicize the word "before",
but there's a typo that causes it to be not italicized in the rendered
HTML.
@sebastianbenz
> Fix italicization of word

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/amp_email_best_practices.md
Currently, some of these links point to versions of the component
reference that don't apply to the email spec, such as amp-list 1.0 which
is banned in the email format. We should point to the version
specifically supported in emails.
We are doing this for components even for components that don't have
more than 1 version, for consistency and being future-proof.
@sebastianbenz
> Link to fixed version of component reference

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/webstory_technical_details.md
HLS is not widely supported on Android browsers (`canPlayType` returns `maybe`) so we should not recommend it as the main video format for stories, as the browser doesn't fallback properly in many scenarios.
> Removed HLS recommendation from docs

- .gitignore
These are already ignored by the `amphtml` project.
/to @sebastianbenz
> Ignore temporary files generated by Vim

- pages/content/amp-dev/documentation/guides-and-tutorials/start/email-inspiration.md
The "endpoint" form is already used elsewhere in the same page.
/to @sebastianbenz
> Make spelling of "endpoint" consistent

- gulpfile.js/build.js
Introduced this bug when I switched over to programmatically adding go links
> dont overwrite rewrites when adding go links

- pages/content/amp-dev/support/index.md
Redo of ampproject/amp.dev#6669 targeting the static branch, many apologies, hope this is right,
The AMP specific category of the official google forum has gone, and it's rebranded to search central.
This pr corrects the link and updates the anchor text to make it clearer it's not a Google AMP specific forum
I am a [Product Expert in that forum](https://support.google.com/profile/2040358)
> Redoing Update Support Link to Google Forum PR

- gulpfile.js/build.js
Hopefully this would fix the issue. But if it doesn't, I would remove this entire segment of code and it should fix it.
https://github.com/ampproject/amp.dev/issues/6761
In addition, the logic to determine whether a link is relative is updated to be more precise.
> Fix go link not redirecting issue

- .github/workflows/lint-js.yaml
- .github/workflows/lint-yaml.yaml
- .github/workflows/release-static-production.yaml
- .github/workflows/test-platform.yaml
- .github/workflows/test-playground.yaml
- Dockerfile.development
- gulpfile.js/staticify.js
- pixi/webpack.config.js
- platform/lib/common/cheerioOptions.js
- platform/lib/format-transform/index.js
- platform/lib/utils/cheerioHelper.js
- playground/webpack.config.js
See individual commits for each step
Locally, all `npm run test:...` commands pass for me and some but not all the `npm run build:...` commands. It's really difficult to tell which ones are still relevant and which ones are legacy code :/
Importantly, I ran through the steps in `release-static-production.yaml` manually and it does seem to pass with Node 16, so I am optimistic about this PR :D
> Update Node version to 16 and fix other config / API usage for newly-broken deps

- .github/workflows/deploy.yaml
- netlify/configs/preview.amp.dev/netlify.toml
Broken in #6781, not entirely fixed in #6783
Tag-along change:
- Make it so that any branch called `gha-deploy-*` also deploys to Staging - helps with debugging
> Yet another fix for preview.amp.dev

- examples/source/1.components/amp-vine.html
- examples/source/multimedia-animations/Integrating_Videos_in_AMP_an_Overview.html
- examples/source/multimedia-animations/Video_Carousels_with_amp-carousel.html
- examples/static/samples/files/amp-video-iframe-videojs.html
- examples/static/samples/files/custom-video-player.html
While dealing with https://github.com/ampproject/amphtml/issues/39676, found a few examples broken (vine) and the videojs could be using later version of videojs.js. Updating them on amp.dev
> Video examples on amp.dev

- platform/lib/format-transform/index.test.js
So we can at least deploy the site now.
> Validator does not validate ampjs.org, temporarily revert the test

- pages/shared/data/faq.yaml
Added ExpertSender to list of Email Platforms and Service Providers
ExpertSender Email Marketing Platform supports sending messages with AMP content: https://expertsender.com/blog/ten-reasons-to-use-amp-in-email-marketing/
> Added ExpertSender to ESPs list

- gulpfile.js/staticify.js
All component pages are missing _any_ section that has a `[filter ...]` rule applied, since those component markdown pages only list a `format` as a filter, never a `level`, but the filter pre-processor macro is expecting both of those to be set
> Fix for incorrectly applied `[filter ...]` tags in Markdown processor

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages.md
Much content in the page don't apply to AMP for Email:
- Custom fonts are not allowed in AMP for Email
- keyframe animations are not allowed in AMP for Email
- The CSS preprocessor section mostly talks about AMP for website.
Also, the current notice for the additional restrictions in the email spec is easy to miss. Changing it to a warning should help a bit.
/to @erwinmombay
> Update style_pages.md for AMP for Email

- netlify/functions/examples_api_echo/examples_api_echo.js
- netlify/functions/examples_api_hello/examples_api_hello.js
- netlify/functions/examples_api_photo_stream/examples_api_photo_stream.js
- netlify/functions/examples_source_news_publishing_amp-live-list_api/examples_source_news_publishing_amp-live-list_api.js
- netlify/functions/examples_static_samples_json_cart/examples_static_samples_json_cart.js
- netlify/functions/search_autosuggest/search_autosuggest.js
- netlify/functions/search_do/search_do.js
Gmail team has found out that this endpoint is returning inconsistent Access-Control-Allow-Origin header. It could be because it enables `public` cache. The problem is that this header depends on the origin header and therefore it cannot properly be cached without messing the response header up. This PR disables the cache on the Netlify. Given it is only a demo, I do not expect this to become a significant cost problem.
@zhangsu
> Fix amp4email demo XHR endpoint inconsistent header

- package-lock.json
- package.json
- platform/lib/platform.js
It is used in the server for content compression, which is not needed any more since Netflier will do that for us instead. However, it has a bunch of dependencies that are causing many issues. Therefore it makes more sense to remove it.
> Remove deprecated shrink-ray-current from amp.dev

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design.md
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages.md
1. Custom font is not supported
2. Embedding video is not supported
3. Examples link should point to the email examples
4. There's no design templates for email on amp.dev
5. The AMP Conf Workshop codelab link is broken and cannot be found in https://codelabs.developers.google.com/
/to @powerivq
> Filter out non-applicable content for email

- .dockerignore
In the container, it is throwing bunch of errors due to .git is not there.
> Do not ignore .git folder since it is actually being used

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages.md
https://github.com/ampproject/amp.dev/pull/6833 took a shortcut and applied the format filter on just part of the sentence. This resulted in the word "stylesheets" being put in a new paragraph after the word "external". Apparently, the filter mechanism always creates a new paragraph as opposed to coalescing all whitespace characters into a single space.
To fix this, we will have to duplicate some parts of the sentence, unfortunately.
/to @powerivq
> Remove unnecessary new paragraph in style_pages.md

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_emails.md
Some developers are apparently confused by the instruction here and tested the validation by sending the email from, for example, the Gmail playground. That defeats the purpose of the validation mentioned in this section, because the playground skips any ESP-specific post-processing of the AMP email authored by the developer. The purpose is to catch issues sent by the ESP which may not reproduce when using the playground.
/to @powerivq
/cc @missingtrailingcomma
> Clarify ESP-delivered email validation

- playground/webpack.config.js
This optimizer feature was causing  the native `Symbol` implementation to be replaced for some reason. This in turn causes the Closure polyfills code to break inside `validator_wasm.js` Once the Closure Polyfills break inside validator_wasm.js the whole validator is non operational.
Fixes the issue below:
> Remove unsafe terser optimizations
