- pages/content/shared/header.html
> Share search markup for search

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/terminology.md
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps.md
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@es.md
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@id.md
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@ja.md
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@ko.md
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@pt_BR.md
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@zh_CN.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests@zh_CN.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@es.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@id.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@ja.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@ko.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@pt_BR.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached@zh_CN.md
Partially resolves [#22407](https://github.com/ampproject/amphtml/issues/24407). 
Waiting on Cloudfare confirmation before merging. Will update when approved.
> removed references to Cloudflare and replaced with Bing

- pages/shared/data/roadshow.yaml
Reverts ampproject/amp.dev#2949
> Revert "Added Eastern Europe roadshow cities"

- frontend/scss/components/organisms/sampler.scss
- frontend/scss/components/organisms/translation-hint.scss
> 🚸 Improve mobile UX

- pages/content/amp-dev/about/success-stories/nobroker.yaml
> 🐛 Set correct teaser text for NoBroker success story

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/formatting.md
Added missing escaping for the source examples together with @tharders
> added escaping for raw and server_for_email

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components.md
Partially resolves issue [#1951](https://github.com/ampproject/amp.dev/issues/1951)
> added information on https protocol

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
resolved issue [#2280](https://github.com/ampproject/amp.dev/issues/2280)
> clarified inline style byte limit

- examples/source/e-commerce/Payments_in_AMP.html
- examples/source/e-commerce/Product_Page.html
Fix https://github.com/ampproject/amp.dev/issues/2946
> Fixed broken link: payments_in_amp

- examples/source/1.components/amp-next-page.html
> Fix amp-next-page sample

- frontend/templates/views/partials/content.j2
> 🚸 Warn if document doesn't match currently selected format

- platform/lib/platform.js
- platform/lib/routers/growSharedPages.js
> 🐛 Add dedicated router for shared fragments

- pages/shared/data/amp-cs-2019.yaml
This updates the AMPCS2019 schedule to the latest iteration (this time without the extraneous files I had in my last PR).
> Update AMP Contributor Summit 2019 schedule

- pages/content/amp-dev/events/code-of-conduct.html
Replace "Google" with "The AMP Project"
> s/Google/The AMP Project/

- frontend/scss/components/organisms/search.scss
- frontend/templates/views/partials/header.j2
- frontend/templates/views/partials/search.j2
This PR closes: #2831, #2833, #2834, #2864 and #2972 
**DONE**
**Currently not possible**
**Not a bug, browser settings**
---
> ✨ Search: UX improvements

- platform/config/go-links.yaml
I don't suppose there's a way for me to test these go links on my machine?
I get nervous committing things without being able to test them first :)
> Go links for AMP roadshow tutorials

- pages/content/amp-dev/documentation/guides-and-tutorials/start/create_email.md
a client mentioned lack of examples..I think pointing it out its availability in playground would be impactful
> update docs to point out examples

- pages/content/amp-dev/events/amp-cs-2019.html
- pages/shared/data/amp-cs-2019.yaml
This updates the AMP Contributor Summit schedule.
/cc @sebastianbenz @ampproject/wg-outreach
> Updates the AMP Contributor Summit schedule

- pages/content/amp-dev/index.html
> 🐛 Point issue reporters to amphtml instead of amp.dev

- frontend/scss/components/atoms/headline.scss
- frontend/scss/components/molecules/teaser-component-code.scss
- frontend/scss/components/molecules/teaser-component.scss
- frontend/scss/components/molecules/teaser-guides.scss
- frontend/scss/components/molecules/teaser-highlight-guides.scss
- frontend/scss/components/organisms/format-cards.scss
- frontend/scss/components/organisms/resources-grid.scss
- frontend/scss/components/organisms/resources-overview.scss
Fixes #3042, fixes #3043 
Sadly I had to fix this with overall 8 media queries, which will cause 209 Bytes more than before 👀
> 💄 Implement UI fixes for iPhone 5/SE

- platform/config/go-links.yaml
> added go links for presentation

- pages/shared/data/roadshow.yaml
Sadly, people had to change this date.
> Change Kyiv roadshow date

- platform/config/go-links.yaml
Link to be used in presentation at AMP CS.
> Add link for CS presentation

- README.md
Fixes: https://github.com/ampproject/amp.dev/issues/3031
> Include OS-specific pip setup instructions

- pages/shared/data/faq.yaml
> add idealmedia to ad vendors

- pages/shared/data/faq.yaml
> add mgid to ad vendors

- pages/shared/data/roadshow.yaml
Middle East roadshows recede into the past.
Korea roadshows appear in the future!
> Moar roadshows!

- frontend/templates/views/partials/format-toggle.j2
> Format toggle links to current page if target format is supported

- platform/lib/routers/search.test.js
> Search test should not rely upon external data

- pages/content/amp-dev/documentation/index.html
This is a teensy PR that I'm sending to get the ball rolling. I'm new to OSS, so am still figuring out how to get myself added to the CLA.
> Corrects the spelling of "referencees" to "references."

- package.json
#3065 killed the csso dependency.
> 🐛 Readd csso dependency

- pages/shared/data/roadshow.yaml
> Removed Busan from roadshows

- pages/content/amp-dev/about/websites.html
Changed "AMP Cache" -> "AMP Caches"
Issue #2382 Change "AMP Cache" -> "AMP Caches" 
@sebastianbenz
> Issue ampproject#2382 updated

- examples/source/1.components/amp-selector.html
Fixes ampproject/amphtml#18668
> Add examples for keyboard-select-mode to `amp-selector`

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations.md
Changed it to "Contribute translations" and cleaned up some of the language
> updated translation page

- platform/config/go-links.yaml
To be used in PR template in `ampproject/amphtml`
Related: https://github.com/ampproject/amphtml/pull/25841
> Add go links for contribution process and I2I

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations@pt_BR.md
Hi @CrystalOnScript
I've included a Brazilian Portuguese version for the translation guide
> adding translation guide for Brazilian Portuguese

- pages/content/amp-dev/about/how-amp-works.html
resolves issue [#2995](https://github.com/ampproject/amp.dev/issues/2995)
> nit fix about custom JS

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/index.md
cc @honeybadgerdontcare 
Resolves [#2681](https://github.com/ampproject/amp.dev/issues/2681)
> clarified CSS byte limit

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/introduction_to_animations.md
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics_basics.md
Resolves issue [1075](https://github.com/ampproject/amp.dev/issues/1075)
@sebastianbenz and @matthiasrohmer - I couldn't get the filters didn't work on my local build, any idea why?
> added info on Ads animations

- .github/ISSUE_TEMPLATE/--content-proposal-.md
- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/content.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/tool.md
A continuation of the previous effort towards
issue template format uniformity.
<sup>1</sup>Used [titlecaseconverter.com](https://titlecaseconverter.com) for the title case conversion.
<sup>2</sup> Follows implementation by [Angular](https://raw.githubusercontent.com/angular/angular/master/.github/ISSUE_TEMPLATE/1-bug-report.md), adapted for amp.dev purposes.
<sup>3</sup> Only viewable in GitHub ([technically task lists](https://help.github.com/en/github/managing-your-work-on-github/about-task-lists))
Title capitalization conformance validation can be automated in the future when checked with a Markdown linter. I've started a list of things that should probably remain consistent between documents. 🙂 Any changes welcome!
> meta: further refine issue template formatting

- contributing/samples.md
Although this revision adds no new content, it contains typo corrections and grammatical improvements that I hope will help move this document closer to surfacing on amp.dev.
Refs: https://github.com/ampproject/amp.dev/issues/3325
> fix(doc): revise Creating a New Sample formatting

- gulpfile.js/deploy.js
This will help reduce costs for Google Cloud. Before creating a new instance template old ones (except the last three) will be deleted.
Side note: I configured Google Cloud Storage (which stores Travis artifacts) to auto-delete everything older than 7 days.
> ✨ Clean up stale Google Cloud instance templates

- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@es.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@id.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@ja.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@ko.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@pt_BR.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/navigating@zh_CN.md
Resolves [issue 26295](https://github.com/ampproject/amphtml/issues/26295)
> fixed css issue

- frontend/templates/views/partials/header.j2
- frontend/templates/views/partials/search.j2
- pages/static/serviceworker.js
- platform/config/search-promoted-pages.json
- platform/lib/routers/search.js
With this PR the latest search query and results will be cached via the service worker.
Currently, there may appear a styling glitch in the results list (sporadically), so this is why this still is a Draft PR.
Feel free to test. I look forward to your feedback :)
> ✨ Cache latest search query and results in service worker

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages.md
Solves CSS disallowed inconsistency. Issue #3373
> resolved issue 3373

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
- platform/lib/routers/search.test.js
> Imported spec docs don't link to each other correctly #3107

- pages/content/amp-dev/documentation/index.html
attempted to link to mission and vision page but links are blue background is blue.
Resolved issue [#3336](https://github.com/ampproject/amp.dev/issues/3336)
> removed suck less... 

- frontend/templates/views/partials/format-toggle.j2
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
- platform/lib/routers/search.test.js
update on https://github.com/ampproject/amphtml/issues/19095
all amp-inputmask examples show the correct mobile keyboard
> Ensure all amp-inputmask examples show the correct mobile keyboard 

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md
I wanted to propose these changes to the previous PR but had unrelated changes.
>  📝 Revise Include custom JavaScript in AMP pages

- package-lock.json
- package.json
- platform/lib/utils/HeadDedupTransformer.js
- platform/lib/utils/HeadDedupTransformer.test.js
- platform/lib/utils/cssTransformer.js
- collapses whitespace
- 40% faster optimization
- auto extension import
> Upgrade AMP Optimizer

- pages/content/amp-dev/about/success-stories/index.html
> ✨ Allow SSR for success-stories page

- platform/config/go-links.yaml
> Update go.amp.dev/email-tools to use format filter

- examples/source/interactivity-dynamic-content/Restrict_Duplicate_Selection.html
> Remove formats from Restrict Duplicate Selection

- platform/config/amp-dev-redirects.yaml
- platform/config/go-links.yaml
Prevent needless redirects by adding trailing slashes in `amp-dev-redirects.yaml` and `go-links.yaml`.
Resolves: #3040
> ✨ Prevent needless redirects

- pages/shared/data/roadshow.yaml
Removed wrongly mentioned events in upcoming events and moved them to past events in descending order
> Removed past events from upcoming events

- pages/content/amp-dev/events/amp-roadshow.html
- pages/shared/data/roadshow.yaml
Fixup to #3471 which broke the build.
> 🐛 Handle empty next stops for roadshow gracefully

- frontend/templates/views/partials/sidebar.j2
> 🐛 Set correct class for example sidebar

- pages/content/amp-dev/index.html
> 🐛 Fix dynamic button text for format explainer

- frontend/scss/components/templates/working-group.scss
- frontend/templates/views/detail/working-group-detail.j2
- pages/content/amp-dev/community/_blueprint.yaml
> 🐛 Fix active state for working group navigation items

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/_blueprint.yaml
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/index.md
Third party seems to be a more accurate name than vendor...
> changed vendor to third party

- gulpfile.js/develop.js
- pages/extensions/log_beautifier/__init__.py
- pages/extensions/log_beautifier/log_beautifier.py
- platform/config/podspec.yaml
- platform/lib/utils/grow.js
- platform/lib/utils/sh.js
Extracted from #3552 as it is not really related, adds to #3330. This improves Grow's logging behaviour like so:
**Currently**
**With this PR**
> 🚸 Improve logging behaviour around Grow

- pages/translations/zh_CN/LC_MESSAGES/messages.po
That's a lot of translation work need to be done.
Done about 1/2
Also I found out some mispelling like "affiliate link → affliate link"
> zh-CN translation update

- package-lock.json
- package.json
- platform/lib/utils/cssTransformer.js
> 📦 Update rcs-core to version 3.0.0

- examples/source/1.components/amp-bind-macro.html
- examples/source/1.components/amp-bind-recaptcha.html
- examples/source/interactivity-dynamic-content/Dynamic_Accordion.html
- examples/static/samples/json/cold.json
- examples/static/samples/json/hot.json
New samples: 
amp-bind-macro
amp-bind-recaptcha
Dynamic Accordion (2 json files needed for this snippet)
> 3 new samples for amp playground

- examples/source/interactivity-dynamic-content/Currency_Conversion.html
- examples/source/interactivity-dynamic-content/JSON_Filter.html
- examples/source/interactivity-dynamic-content/Linked_Dropdowns.html
- examples/static/samples/json/linked_dropdowns.json
Added onto Linked Dropdown and new json filter snippet
> Amp playground interactive snippets

- examples/source/1.components/amp-accordion.html
- examples/source/interactivity-dynamic-content/Conditional_State.html
- examples/source/interactivity-dynamic-content/Multi_Page_Flow.html
- examples/static/samples/json/accordion-fruit.json
1 New File: Conditional State snippet
2 snippets appended to end of the following files: 
- amp-accordion (comparison accordion)
- Multi_Page_Flow (form & submit button added to Vertical Stepper)
@philkrie
> 3 more snippets

- frontend/scss/components/molecules/format-filter-hint.scss
> 🐛 Remove select format call out on mobile

- platform/lib/pipeline/componentReferenceDocument.js
- platform/lib/pipeline/componentReferenceImporter.js
> 🐛 Correctly build component scripts

- pages/content/amp-dev/about/mission-and-vision.html
- pages/translations/ar/LC_MESSAGES/messages.po
- pages/translations/en/LC_MESSAGES/messages.po
- pages/translations/es/LC_MESSAGES/messages.po
- pages/translations/fr/LC_MESSAGES/messages.po
- pages/translations/id/LC_MESSAGES/messages.po
- pages/translations/it/LC_MESSAGES/messages.po
- pages/translations/ja/LC_MESSAGES/messages.po
- pages/translations/ko/LC_MESSAGES/messages.po
- pages/translations/messages.po
- pages/translations/pt_BR/LC_MESSAGES/messages.po
- pages/translations/ru/LC_MESSAGES/messages.po
- pages/translations/tr/LC_MESSAGES/messages.po
- pages/translations/zh_CN/LC_MESSAGES/messages.po
the translation folks pointed out some weird phrasing, after talking to @sebastianbenz it seems best to just remove it.
> remove some awkward phrasing

- pages/translations/ar/LC_MESSAGES/messages.po
- pages/translations/en/LC_MESSAGES/messages.po
- pages/translations/es/LC_MESSAGES/messages.po
- pages/translations/fr/LC_MESSAGES/messages.po
- pages/translations/id/LC_MESSAGES/messages.po
- pages/translations/it/LC_MESSAGES/messages.po
- pages/translations/ja/LC_MESSAGES/messages.po
- pages/translations/ko/LC_MESSAGES/messages.po
- pages/translations/messages.po
- pages/translations/pt_BR/LC_MESSAGES/messages.po
- pages/translations/ru/LC_MESSAGES/messages.po
- pages/translations/tr/LC_MESSAGES/messages.po
- pages/translations/zh_CN/LC_MESSAGES/messages.po
> remove story titles from translation files

- frontend/templates/views/partials/footer.j2
ref: https://github.com/ampproject/amp.dev/pull/3582#pullrequestreview-363619749
> unwrap sidebar 2020 amp conf link

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/index.md
https://github.com/ampproject/amphtml/pull/26475
https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/
> Updated CSS limit to 75,000 bytes from 50,000

- pages/shared/data/roadshow.yaml
totally biffed it originally. sorry @morsssss
> fix roadshow dates

- examples/source/1.components/amp-script/index.html
Context: https://stackoverflow.com/questions/60317056/how-to-implement-regex-in-amp
> add custom form validation amp-script sample

- examples/source/news-publishing/News_Article.html
light on light was not readable
> make cookie text readable

- frontend/scss/components/molecules/format-filter-hint.scss
- frontend/templates/views/partials/format-filter-hint.j2
> 🐛 Prevent format filter banner from jumping

- frontend/scss/components/organisms/cities.scss
- pages/content/amp-dev/events/amp-roadshow.html
- pages/shared/data/recent-guides.yaml
- pages/shared/data/roadshow.yaml
> remove events

- examples/source/interactivity-dynamic-content/Copy_Button.html
> Fix copy button sample

- platform/lib/pipeline/componentReferenceDocument.js
- platform/lib/pipeline/componentReferenceImporter.js
> 🐛 Correctly import amp-story sub-components

- pages/shared/data/faq.yaml
> Adds ExpressPigeon to ESP list

- boilerplate/templates/partials/analytics/amp-analytics-import.html
- boilerplate/templates/partials/media/amp-video-import.html
> 🐛 Hide unused script tags in Boilerplate Generator 

- examples/source/1.components/amp-inputmask.html
> Remove experiment flag

- examples/source/1.components/amp-analytics/api.js
Part of #3567. @robinvanopstal is taking care of some others.
> 🐛 Correctly resolve embed path for amp-analytics example

- examples/source/interactivity-dynamic-content/Tic_Tac_Toe.html
> 🐛Fix and refactor broken tic tac toe example

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics_basics.md
> Fix invalid JSON

- frontend/scss/components/organisms/toc.scss
> 🐛 Fix documentation toc scrolling

- frontend/templates/views/partials/category-filter.j2
- pages/content/amp-dev/documentation/components/index.html
- pages/content/amp-dev/documentation/examples/index.html
> 🐛 Keep scroll position when filtering on overview pages

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/_blueprint.yaml
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/secure-pages.md
Resolves [issue 3320](https://github.com/ampproject/amp.dev/issues/3320)
> Removed documentation from ads filtering 

- frontend/templates/views/partials/breadcrumbs.j2
> 🐛 Clickable components and examples breadcrumbs

- platform/lib/pipeline/componentReferenceDocument.js
- platform/lib/pipeline/componentReferenceDocument.test.js
> 🐛 Stop removing tables from component docs

- examples/source/1.components/amp-analytics/api.js
> 👽 Upgrade amp-analytics to new uuid export scheme

- frontend/templates/views/partials/content.j2
> 💬 Adapt unsupported format warning to fit all pages

- frontend/templates/views/partials/analytics.j2
- frontend/templates/views/partials/consent.j2
> 🎨 Use new configuration scheme for amp-consent

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics_basics.md
> 🐛 Fix json error for analytics_basics script tag

- platform/lib/pipeline/markdownDocument.js
> 🐛 Remove trailing and leading blank lines from tip 

- frontend/templates/views/partials/component-intro.j2
> 🐛 Use length of filtered examples to decide if list is expandable

- examples/source/user-consent/Story_User_Consent.html
cf https://amp.dev/documentation/components/amp-consent/#prompt-ui-for-stories
Fixes #3775
> Fix AMP Story consent example.

- package-lock.json
- package.json
- pages/content/amp-dev/documentation/guides-and-tutorials/start/create_email.md
- pages/content/amp-dev/documentation/tools.html
- platform/lib/utils/cssTransformer.js
AMP Optimizer now uses css-nano for minification.
> Remove csso

- frontend/scss/components/molecules/banner.scss
- frontend/templates/views/partials/analytics.j2
- frontend/templates/views/partials/banner.j2
- frontend/templates/views/partials/header.j2
This makes banners also dissmissable (optional).
> add DevX survey banner

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations@zh-CN.md
I have translated translations.md to Chinese Simplified.
> Add Chinese Simplified Localization

- frontend/templates/views/detail/working-group-detail.j2
> 🔥 Remove nugatory text label

- frontend/templates/views/partials/sidebar.j2
- pages/content/amp-dev/documentation/components/index.html
> 🐛 Respect all versions filtering supported formats

- examples/source/1.components/amp-next-page.html
> Update amp-next-page demo to use version 1.0

- pages/shared/data/faq.yaml
Source: https://www.notion.so/custio/Customer-io-Beta-Sending-AMP-Messages-73a817e0a9c14a42a12d6b427e436eb4
> Add Customer.io to support list

- pages/shared/data/faq.yaml
Add MoonMail as an esp supporting amp
> Add MoonMail as an esp supporting amp

- frontend/scss/components/molecules/banner.scss
- frontend/scss/components/organisms/burger-menu.scss
- frontend/templates/views/partials/banner.j2
- frontend/templates/views/partials/burger-menu.j2
- frontend/templates/views/partials/header.j2
> 🐛 Fix burger toggle for dismissable banners

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-urls.md
Resolves issue [#3851](https://github.com/ampproject/amp.dev/issues/3851)
> updated AMP Cache URL with new algorithm 

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/optimize_amp.md
remove some left over markdown that is leaking into the docs.
> remove vestigial markdown

- pages/content/amp-dev/about/stories.html
- pages/content/amp-dev/index.html
- pages/shared/data/benefits.yaml
- pages/translations/ar/LC_MESSAGES/messages.po
- pages/translations/en/LC_MESSAGES/messages.po
- pages/translations/es/LC_MESSAGES/messages.po
- pages/translations/fr/LC_MESSAGES/messages.po
- pages/translations/id/LC_MESSAGES/messages.po
- pages/translations/it/LC_MESSAGES/messages.po
- pages/translations/ja/LC_MESSAGES/messages.po
- pages/translations/ko/LC_MESSAGES/messages.po
- pages/translations/messages.po
- pages/translations/pt_BR/LC_MESSAGES/messages.po
- pages/translations/ru/LC_MESSAGES/messages.po
- pages/translations/tr/LC_MESSAGES/messages.po
- pages/translations/zh_CN/LC_MESSAGES/messages.po
Context "[Web Stories, powered by AMP](https://blog.amp.dev/2020/05/01/web-stories-powered-by-amp/)"
This only updates the landing page. Other pages are left unchanged.
> Rename AMP Stories to Web Stories

- pages/content/amp-dev/documentation/guides-and-tutorials/start/create_successful_stories.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/_blueprint.yaml
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/add_more_pages.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/animating_elements.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/congratulations.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/create_cover_page.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/index.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/parts_of_story.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/setting_up.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/start_story.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/validation.md
Phase 1 of name migration - update confusing language while other documentation is working on being merged.
> updated language to reflect web story name migration

- examples/static/samples/internationalization/alternate/fr/index.amp.html
- examples/static/samples/internationalization/alternate/fr/index.html
- examples/static/samples/internationalization/alternate/fr/index.mobile.html
- examples/static/samples/internationalization/alternate/index.amp.html
- examples/static/samples/internationalization/alternate/index.html
- examples/static/samples/internationalization/alternate/index.mobile.html
- examples/static/samples/internationalization/alternate/ja/index.amp.html
- examples/static/samples/internationalization/alternate/ja/index.html
- examples/static/samples/internationalization/alternate/ja/index.mobile.html
- examples/static/samples/internationalization/basic/fr/index.amp.html
- examples/static/samples/internationalization/basic/fr/index.html
- examples/static/samples/internationalization/basic/index.amp.html
- examples/static/samples/internationalization/basic/index.html
- examples/static/samples/internationalization/basic/ja/index.amp.html
- examples/static/samples/internationalization/basic/ja/index.html
- examples/static/samples/internationalization/rtl.html
> 🐛 Statify template expressions and fix paths in i18n guide

- frontend/scss/components/molecules/tip.scss
- frontend/scss/components/templates/roadmap.scss
- pages/content/amp-dev/community/roadmap.html
- platform/config/imports/roadmap.json
Overall styling improvements. E.g. scroll-behavior and optimizations for tablet
> 💄 Roadmap styling fixes

- gulpfile.js/import/importRoadmap.js
- pages/content/amp-dev/community/roadmap.html
Time-saving due to parallelization:
New: 2.57 s. 
Old: 16 s
> ⚡️Reimplement roadmap importorter

- examples/source/1.components/amp-soundcloud.html
Adds info on `data-color` and `data-secret-token` attributes
> add supported amp-soundcloud attributes

- examples/source/1.components/amp-date-display.html
- examples/source/1.components/amp-install-serviceworker.html
> 💬 Various content fixes.

- package-lock.json
- package.json
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/story_ads_best_practices.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/release-schedule.md
- platform/config/go-links.yaml
- playground/src/app.js
- playground/src/document/controller.js
- playground/src/index.hbs
- playground/src/params/base.js
- playground/src/share/index.js
- playground/src/share/share-dialog.scss
> Enable playground sharing via hash string

- platform/config/go-links.yaml
Also put a few other things into alphabetical order!
> go link for amp-script supported APIs

- .gitignore
- frontend/templates/views/detail/working-group-detail.j2
- gulpfile.js/import/importWorkingGroups.js
- package.json
Applies the same fix as for the roadmap (#4051) to the working group pages.
> ♻️  Allow use of emojis for working group data

- gulpfile.js/import/importWorkingGroups.js
Brings down execution time from 13s to 2.37s.
> ⚡️ Remove blocking behaviour from WG importer

- playground/src/editor/editor.js
- playground/src/editor/editor.scss
> ✨ Add line numbers to playground

- playground/src/editor/editor.scss
> 🐛 Align line numbers in playground

- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/animating_elements.md
fixes ampproject/amphtml#28890
> fix minor typo

- gulpfile.js/build.js
- package.json
Minifying now happens on request.
> 🏗  Remove minifyPages task

- frontend/scss/components/molecules/tip.scss
- frontend/templates/views/partials/content.j2
- pages/content/amp-dev/community/roadmap.html
> 💄 Update manual occurences of tip

- pages/content/amp-dev/documentation/guides-and-tutorials/start/email_sender_distribution.md
We're hoping to have this live before EOD Monday - does that align with the next amp.dev deploy @matthiasrohmer ?
> added sender distribution guidelines for email

- frontend/scss/components/molecules/nav-link.scss
- frontend/scss/components/organisms/burger-menu.scss
- frontend/templates/views/partials/burger-menu.j2
- frontend/templates/views/partials/header.j2
- frontend/templates/views/partials/sidebar.j2
- platform/lib/templates/index.js
Fixes #3858 - improves page build speed by 15s.
> ⚡️  Cache navigation partials and SSR active states

- platform/config/imports/componentReference.json
Blocked by https://github.com/ampproject/amphtml/pull/28941
> 🔧  Fetch amp-subscriptions from master

- platform/config/go-links.yaml
Coming soon (once we write it)
go.amp.dev/service
> go links for AMP at your service web.dev LIVE talk

- frontend/templates/views/partials/teaser.j2
> 🐛  Fix example teasers

- frontend/templates/layouts/default.j2
- frontend/templates/macros/atoms.j2
- frontend/templates/views/detail/success-story-detail.j2
- frontend/templates/views/examples/documentation.j2
- frontend/templates/views/examples/preview.j2
- frontend/templates/views/partials/accordion.j2
- frontend/templates/views/partials/analytics.j2
- frontend/templates/views/partials/burger-menu.j2
- frontend/templates/views/partials/component-sidebar.j2
- frontend/templates/views/partials/component-visual-image.j2
- frontend/templates/views/partials/consent.j2
- frontend/templates/views/partials/float-image.j2
- frontend/templates/views/partials/format-filter-hint.j2
- frontend/templates/views/partials/format-visuals/email.j2
- frontend/templates/views/partials/fragment-slider-controls.j2
- frontend/templates/views/partials/header.j2
- frontend/templates/views/partials/kpis.j2
- frontend/templates/views/partials/search.j2
- frontend/templates/views/partials/service-worker.j2
- frontend/templates/views/partials/sidebar-toggle-observer.j2
- frontend/templates/views/partials/sidebar.j2
- frontend/templates/views/partials/teaser.j2
- frontend/templates/views/partials/toc.j2
- frontend/templates/views/partials/video-carousel.j2
- frontend/templates/views/partials/video.j2
- pages/content/amp-dev/about/mission-and-vision.html
Removes the  dependency hints from Issue #3576
> 🔥 remove dependency hints

- frontend/templates/views/partials/header.j2
Just removing the banner, now that the event is over!
> Remove banner

- README.md
- package-lock.json
- package.json
- platform/lib/pipeline/gitHubImporter.js
Fixes #4092. But also increases import times 🙁
> ♻️  Queue requests to GitHub API

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
A few details I noticed while doing a live-coding version of this tutorial!
> Small fixes in amp-script tutorial doc

- playground/src/error-list/error-list.scss
Can't tell where this got lost. But it's missing.
> 🔀 Bring back lost error-list stylings for playground

- playground/src/fly-in/fly-in-background.scss
- playground/src/index.hbs
> 🐛 Only show fly-in background if lightbox class is added

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md
Hi,
These commits are for the non-existing referenced urls of the worker-dom repo; 
Kindly see if this can be merged.
https://github.com/ampproject/amp.dev/issues/4171
Thanks
Manjeet
> Typo correction worker dom repo 404 urls 2

- frontend/scss/components/atoms/headline.scss
- frontend/scss/components/atoms/pill.scss
- frontend/scss/components/templates/component-detail.scss
- frontend/templates/views/partials/component-headline.j2
- frontend/templates/views/partials/content.j2
- frontend/templates/views/partials/version-toggle.j2
Adds the experimental and deprecated tags to the components headline
> ✨ add experimental and deprecated tag

- frontend/scss/components/atoms/pill.scss
- frontend/scss/components/templates/tools.scss
- frontend/templates/views/partials/filter-bubbles.j2
- pages/content/amp-dev/about/success-stories/index.html
- pages/content/amp-dev/documentation/templates/index.html
- pages/content/amp-dev/documentation/tools.html
> 🐛 Fix filter bubble stylings

- examples/source/1.components/amp-list.html
https://github.com/ampproject/amp.dev/issues/4020 just corrected the typo of this issue.
Please see if this can be merged.
thanks!
> 4020 typo correction fixes

- pages/content/amp-dev/documentation/examples/index.html
A little thing that's been bothering me...
> Fix grammar in menu item description

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/email_fundamentals.md
Related: https://github.com/ampproject/amphtml/pull/29524
> Add "Authenticating Requests" section in "Email Fundamentals" 

- .travis.yml
- pages/translations/pl/LC_MESSAGES/messages.po
- pages/translations/vn/LC_MESSAGES/messages.po
- platform/lib/config.js
add the langs to the build config to make testing the upcoming translations easier
> add Vietnamese and Polish options to the build

- pages/content/amp-dev/documentation/components/reference/amp-animation-v0.1@tr.md
> fix typo in turkish amp-animation doc

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/advertise_amp_stories.md
> s/AMP Stories/Web Stories/g

- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/add_more_pages.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/animating_elements.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/congratulations.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/create_cover_page.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/index.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/parts_of_story.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/setting_up.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/start_story.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/validation.md
> s/web stor/Web Stor/g

- examples/source/user-consent/Story_User_Consent.html
Fixes https://github.com/ampproject/amphtml/issues/29549
> migrate consent endpoint to amp.dev

- platform/config/imports/componentReference.json
Blocked by https://github.com/ampproject/amphtml/pull/29554
> 🔧 Fetch amp-list docs from master

- frontend/scss/components/organisms/burger-menu.scss
- frontend/scss/components/organisms/header.scss
- frontend/templates/views/partials/banner.j2
> add #BlackLivesMatter banner

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/advanced-interactivity.md
fix #2497.
I grepped through all of the other tutorials, and I can't find any  other mention of amp-bind being new.
> minor tweaks to amp-bind docs

- platform/config/podspec.yaml
Fixes #4264 - see https://github.com/ampproject/amp.dev/issues/4264#issuecomment-668746298 for history.
> 🔧  Enable markdown.extensions.sane_lists for Grow

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/index.md
See https://developer.wordpress.org/reference/functions/capital_p_dangit/
> CamelCase WordPress

- pages/content/amp-dev/page-experience.html
- pixi/src/ui/PageExperience.js
Workaround for https://github.com/ampproject/worker-dom/issues/912
> 🐛 Try to get URL from amp-state if not filled

- frontend/scss/components/atoms/pixi-analyzing-dots.scss
- frontend/scss/components/atoms/pixi-scale.scss
- frontend/scss/components/molecules/pixi-basic-metric.scss
- frontend/scss/components/molecules/pixi-primary-metric.scss
- frontend/scss/components/organisms/pixi-primary-checks.scss
- frontend/scss/components/templates/pixi.scss
- frontend/templates/views/partials/pixi/analyzing-dots.j2
- frontend/templates/views/partials/pixi/basic-metric.j2
- frontend/templates/views/partials/pixi/primary-checks.j2
- frontend/templates/views/partials/pixi/primary-metric.j2
- frontend/templates/views/partials/pixi/scale.j2
- pages/content/amp-dev/page-experience.html
- pixi/mocks/pageExperienceCheck/reportData.json
- pixi/src/checks/PageExperienceCheck.js
- pixi/src/checks/constants.js
- pixi/src/ui/PageExperience.js
- pixi/src/ui/report/BooleanCheckReportView.js
- pixi/src/ui/report/CoreWebVitalsReportView.js
Fixes #4345. This polishes the UI for the Core Web Vitals view and adds the tabbed lab results.
> ✨  Add lab results to core web vitals view

- frontend/scss/_mixins.scss
- frontend/scss/components/molecules/input-bar.scss
- frontend/scss/components/templates/pixi.scss
- frontend/templates/views/partials/pixi/input-bar.j2
- pages/content/amp-dev/page-experience.html
- pixi/src/ui/InputBar.js
- pixi/src/ui/PageExperience.js
> ♻️ Pixi - Refactor input bar + add error label

- examples/source/1.components/amp-carousel.html
- examples/source/1.components/amp-img.html
- examples/source/1.components/amp-social-share.html
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/index.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/release-schedule.md
- pages/shared/data/recent-guides.yaml
Suggested changes and additions based on the TetraLogical accessibility review commissioned by @nainar / @caroqliu
See the related documentation changes proposed at https://github.com/ampproject/amphtml/pull/29609
> ♿ TetraLogical: P0 components accessibility review

- examples/source/user-consent/Advanced_User_Consent_Flow.html
- examples/source/user-consent/Geolocation-based_Consent_Flow.html
- examples/source/user-consent/Server_Side_User_Consent_Flow.html
Simple fix for links to github
> Fix samples with multiple authors

- package.json
... that's why staging is broken.
> 📦  Move amphtml-validator to prod deps

- pixi/src/ui/report/CoreWebVitalsReportView.js
> limit the number of significant figures on pixi lab data results

- pages/content/amp-dev/page-experience.html
- pages/content/pixi/info-texts/cls.md
- pages/content/pixi/info-texts/core_web_vitals.md
- pages/content/pixi/info-texts/fid.md
- pages/content/pixi/info-texts/field_tests.md
- pages/content/pixi/info-texts/https.md
- pages/content/pixi/info-texts/intrusive_interstitials.md
- pages/content/pixi/info-texts/lab_tests.md
- pages/content/pixi/info-texts/lcp.md
- pages/content/pixi/info-texts/mobile-friendliness.md
- pages/content/pixi/info-texts/opportunity_to_improve.md
- pages/content/pixi/info-texts/page_score.md
- pages/content/pixi/info-texts/safe_browsing.md
- pixi/src/ui/I18n.js
Created the content and the interface to maintain the text for information tips.
> Add pixi info texts to be used in information tips

- frontend/scss/components/templates/pixi.scss
> Pixi: Update styles for coming soon page

- frontend/scss/components/atoms/pixi-scale.scss
> make negative portion of pixi performance scale solid

- pixi/src/checkAggregation/recommendations.js
- pixi/src/checkAggregation/recommendations.test.js
- pixi/src/checks/MobileFriendlinessCheck.js
- pixi/src/checks/MobileFriendlinessCheck.test.js
Rename a pixi check missed in https://github.com/ampproject/amp.dev/pull/4427
> Rename noResourceIssues to resourcesLoadable

- pixi/mocks/pageExperienceCheck/apiResponse.json
- pixi/mocks/pageExperienceCheck/apiResponseErrors.json
- pixi/mocks/pageExperienceCheck/apiResponseNoFieldData.json
- pixi/mocks/pageExperienceCheck/reportDataErrors.json
- pixi/mocks/pageExperienceCheck/reportDataNoFieldData.json
- pixi/src/checkAggregation/recommendations.js
- pixi/src/checkAggregation/recommendations.test.js
- pixi/src/checkAggregation/statusBanner.js
- pixi/src/checks/PageExperienceCheck.js
- pixi/src/checks/PageExperienceCheck.test.js
- support results without field data
- add isAllFast result flag
- use psi results in recommendation rules
> Improve pixi psi check logic

- pages/content/amp-dev/page-experience.html
- pixi/mocks/pageExperienceCheck/reportDataErrors.json
- pixi/mocks/pageExperienceCheck/reportDataNoCacheFieldData.json
- pixi/mocks/pageExperienceCheck/reportDataNoFieldData.json
- pixi/src/checks/PageExperienceCheck.js
- pixi/src/checks/PageExperienceCheck.test.js
- pixi/src/ui/PageExperience.js
also fix psi check when cache url has no field data
> Hide results if page is not amp

- pages/content/pixi/recommendations/enable-js-module-runtime.md
- pages/content/pixi/recommendations/upgrade-amp-optimizer.md
- pixi/src/checkAggregation/recommendations.js
- pixi/src/checkAggregation/recommendations.test.js
...and update optimizer upgrade text
> Add specfic recommendation to enable js module runtime

- frontend/templates/views/partials/header.j2
> do not show survey banner

- pages/content/amp-dev/page-experience.html
- pages/content/pixi/status-banners/invalid-url.md
- pages/content/pixi/status-banners/no-amp.md
- pixi/src/ui/PageExperience.js
- pixi/src/ui/StatusIntroView.js
fixIt button is hidden when no relevant recommendations are found
share button is hidden if configured in markdown file
> Hide status buttons depending on result

- pixi/src/checks/PageExperienceCheck.js
- pixi/src/ui/I18n.js
- pixi/src/ui/PageExperience.js
> Pixi: Get localized PSI result

- frontend/templates/views/partials/header.j2
> fix banner offset

- frontend/scss/components/molecules/pixi-primary-metric.scss
- pages/content/pixi/index.md
- pixi/src/ui/I18n.js
- pixi/src/ui/PageExperience.js
- pixi/src/ui/recommendations/RecommendationsView.js
- pixi/src/ui/report/CoreWebVitalsReportView.js
Also cleans up a few related i18n bits. :)
> Pixi: Implement "Take action" texts

- pixi/src/ui/recommendations/RecommendationsView.js
- pixi/src/ui/report/CoreWebVitalsReportView.js
- Resets colors of performance summaries
- Fixes bug in filter UI resetting
Fixes #4478
> Pixi: Fully reset loading UI between runs

- pixi/src/ui/InputBar.js
Fixes https://github.com/ampproject/amp.dev/issues/4486
@caroqliu
> analyze button: dont attempt to validate on focus

- frontend/templates/views/partials/pixi/primary-checks.j2
- frontend/templates/views/partials/pixi/recommendations-item.j2
- frontend/templates/views/partials/pixi/recommendations.j2
- pixi/src/ui/recommendations/RecommendationsView.js
- pixi/src/ui/report/CoreWebVitalsReportView.js
Properly label major regions of the UI with respect to accessibility considerations. Specifically:
- Identify "Field data" and "Lab data" as a "Tab" UI (Fixes #4499)
- Identify filter buttons as "Toggle buttons" (Fixes #4507)
- Identify recommendation items as "Expandable" (Fixes #4508)
> Pixi: Label major regions with accessibility attributes

- frontend/scss/components/molecules/pixi-status-intro.scss
- frontend/templates/views/partials/pixi/basic-metric.j2
- frontend/templates/views/partials/pixi/input-bar.j2
- frontend/templates/views/partials/pixi/primary-checks.j2
- frontend/templates/views/partials/pixi/primary-metric.j2
- frontend/templates/views/partials/pixi/recommendations.j2
- frontend/templates/views/partials/pixi/scale.j2
- frontend/templates/views/partials/pixi/share-dialog.j2
- frontend/templates/views/partials/pixi/status-intro.j2
- pages/content/amp-dev/page-experience.html
- pages/content/pixi/index.md
- pages/content/pixi/index@de.md
- pages/content/pixi/no-field-data.md
- pages/translations/de/LC_MESSAGES/messages.po
> Put all pixi static texts into markdown files

- frontend/scss/components/molecules/pixi-basic-metric.scss
- frontend/scss/components/molecules/pixi-primary-metric.scss
- frontend/scss/components/molecules/pixi-tooltip.scss
- frontend/scss/components/organisms/pixi-basic-checks.scss
- frontend/templates/views/partials/pixi/basic-checks.j2
- frontend/templates/views/partials/pixi/basic-metric.j2
- frontend/templates/views/partials/pixi/tooltip.j2
- Add inverted version 
- Click background to hide the tip
> Pixi - Fix tooltips

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/cors-in-email.md
Per ampproject/wg-amp4email#7
cc @ampproject/wg-amp4email
> Adds "CORS in AMP for Email" page

- frontend/scss/components/molecules/pixi-recommendations-item.scss
- pixi/src/ui/recommendations/RecommendationsView.js
+ fix toggle size on mobile
Fixes #4525
> Pixi - Expand first recommendation

- pages/content/pixi/index.md
> update pixi placeholder text

- frontend/scss/components/molecules/input-bar.scss
- frontend/templates/views/partials/pixi/input-bar.j2
- pixi/src/ui/InputBar.js
- pixi/src/ui/PageExperience.js
> 🐛  Fix various things for Pixi input bar

- pages/content/amp-dev/documentation/components/reference/amp-audio-v0.1@zh_CN.md
Hi,I have already translated amp-audio.md into Chinese!
> Add amp-audio.md Chinese translation.

- pages/content/pixi/index.md
> Pixi - Rename `FID` tag to `FID and TBT`

- frontend/scss/components/molecules/pixi-status-intro.scss
> Pixi: Hide invisible text from screen readers

- frontend/templates/views/partials/pixi/share-dialog.j2
- pages/content/pixi/index.md
- pages/content/pixi/index@de.md
- pages/content/shared/copy-pixi-url.html
> pixi: Fix share dialog localization

- frontend/scss/_functions.scss
- frontend/scss/_variables.scss
- frontend/scss/components/atoms/pill.scss
- frontend/scss/components/atoms/pixi-scale.scss
- frontend/scss/components/molecules/input-bar.scss
- frontend/scss/components/molecules/pixi-basic-metric.scss
- frontend/scss/components/molecules/pixi-primary-metric.scss
- frontend/scss/components/molecules/pixi-recommendations-item.scss
- frontend/scss/components/molecules/pixi-share-dialog.scss
- frontend/scss/components/molecules/pixi-status-intro.scss
- frontend/scss/components/molecules/pixi-tooltip.scss
- frontend/scss/components/organisms/pixi-basic-checks.scss
- frontend/scss/components/organisms/pixi-primary-checks.scss
+ add list of a11y safe colors
> Pixi - Adapt colors in favor of  a11y

- frontend/templates/views/partials/pixi/primary-metric.j2
- frontend/templates/views/partials/pixi/scale.j2
- pages/content/pixi/index.md
- pixi/src/ui/report/CoreWebVitalsReportView.js
> Pixi: Make scale information accessible through non-visual means

- pages/content/pixi/info-texts/cls.md
- pages/content/pixi/info-texts/fid.md
- pages/content/pixi/info-texts/lcp.md
See https://github.com/ampproject/amp.dev/issues/4502
> Update metric thresholds in info tips

- playground/src/experiments/experiments.js
Fixes #4558.
Some of the recent experiments do not have a descriptive name but just an id but we assumed for all experiments to have one.
/cc @morsssss
> 🐛 Gracefully handle experiments without a descriptive name in playground

- pages/content/pixi/info-texts/cls.md
- pages/content/pixi/info-texts/fid.md
- pages/content/pixi/info-texts/lcp.md
- pages/content/pixi/info-texts/tbt.md
- pages/content/pixi/no-field-data.md
- pages/content/pixi/recommendations/hero-images.md
- pages/content/pixi/recommendations/mobile-friendly.md
- pages/content/pixi/recommendations/preconnect-google-fonts.md
- pages/content/pixi/recommendations/safe-browsing.md
- pages/content/pixi/recommendations/valid-cached-amp.md
> Pixi: Add line breaks to metric info tips

- frontend/templates/views/partials/pixi/tooltip.j2
> Pixi: Implement tooltip as an accessible region

- frontend/scss/_variables.scss
> Pixi: Rename css red variable

- frontend/scss/components/molecules/pixi-status-intro.scss
- frontend/templates/views/partials/pixi/status-intro.j2
- frontend/templates/views/partials/pixi/tooltip.j2
> Pixi: Fix validation issues for status and tooltip elements

- platform/config/amp-dev-redirects.yaml
> Redirects for pixi

- frontend/scss/components/molecules/pixi-recommendations-item.scss
> 🐛 Pixi - Wrap code snippets

- frontend/templates/views/partials/analytics.j2
> Pixi: Add amp-analytics triggers

- frontend/scss/components/molecules/pixi-recommendations-item.scss
- frontend/templates/views/partials/pixi/recommendations-item.j2
> Pixi: Make recommendation item header a native <button>

- pixi/src/ui/recommendations/RecommendationsView.js
> Pixi: Select by `button` instead of header

- pages/content/pixi/index.md
Fixes #4695 with follow up effort #4735
> Pixi: Update text for no recommendations to be "No action needed!"

- pages/content/pixi/no-field-data.md
> Update copy for no field data to include more actionable steps

- pixi/src/ui/recommendations/RecommendationsView.js
> ♻️  Simplify and fix recommendations filter logic

- frontend/scss/components/organisms/pixi-primary-checks.scss
- frontend/templates/views/partials/pixi/primary-checks.j2
- pixi/src/ui/PageExperience.js
- pixi/src/ui/report/CoreWebVitalsReportView.js
- pixi/src/utils/checkAggregation/recommendations.js
- pixi/src/utils/issueUrl.js
> Pixi: Display "Analysis failed" for PSI API failure

- pixi/src/utils/texts.js
- pixi/src/utils/texts.test.js
> ♻️ Stop replacing HTML entities in Pixi

- frontend/scss/components/molecules/pixi-recommendations-item.scss
> Pixi: Auto wrap code snippets

- pixi/src/utils/issueUrl.js
> File new issues with ampproject/wg-performance

- pages/content/pixi/index.md
> Changed text

- examples/source/1.components/amp-app-banner.html
> Fix broken link in amp-app-banner doc

- .gitignore
- gulpfile.js/deploy.js
tried to make the packager release a little easier
> attempt to improve DX for packager releases

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/release-schedule.md
- pages/content/pixi/index.md
- pages/content/pixi/index@ar.md
- pages/content/pixi/index@de.md
- pages/content/pixi/index@fr.md
- pages/content/pixi/index@id.md
- pages/content/pixi/index@it.md
- pages/content/pixi/index@ja.md
- pages/content/pixi/index@ko.md
- pages/content/pixi/index@pl.md
- pages/content/pixi/index@pt_BR.md
- pages/content/pixi/index@tr.md
- pages/content/pixi/index@vi.md
- pages/content/pixi/index@zh_CN.md
- pages/shared/data/recent-guides.yaml
- pixi/src/ui/report/CoreWebVitalsReportView.js
fixes #4735, though not sure if I am being naive by using innerHTML
> add emoji to "nothing to do" message in pixi

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/contribute-documentation/terminology.md
Fixs #3961 AMP.dev issue
Updated AMP terminology guide 
AMP story / AMP stories -> Web Story / Web Stories
@CrystalOnScript
> Updated AMP terminology guide

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/discovery.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/discovery_web_stories.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/optimize_amp.md
> added Web Story discovery guide

- pages/content/amp-dev/page-experience.html
> update search console meta description

- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/embed-stories.md
Updating the docs with the latest changes from https://github.com/ampproject/amphtml/issues/30512
> Update amp-story-player docs

- pages/content/amp-dev/events/amp-fest-2020.html
Also add <meta name="description"> to provide a nice snippet for Search.
> Add text and meta tag to AMP Fest page

- pixi/src/checks/AmpLinterCheck.js
- pixi/src/checks/AmpLinterCheck.test.js
- pixi/src/utils/checkAggregation/recommendations.js
- pixi/src/utils/checkAggregation/recommendations.test.js
> 🐛  Pixi - Remove JS Module recommendation

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/advertise_amp_stories.md
In prep for GDN for GAM launch.
> 📓Update story ad docs

- gulpfile.js/build.js
This currently blocks build: https://travis-ci.org/github/ampproject/amp.dev/jobs/741346293
> 🐛 Build new frontend bundle during full build

- examples/source/user-consent/Server_Side_User_Consent_Flow.html
Also made this work on localhost, and fixed up text in UI.
This fixes #4910 .
> Add missing "promptUI" to consent flow example

- pixi/mocks/pageExperienceCheck/reportDataErrors.json
> Translation ES - Teachers section

- pages/content/pixi/status-banners/invalid-content-type.md
- pixi/src/checks/AmpLinterCheck.js
- pixi/src/ui/StatusIntroView.js
- pixi/src/utils/checkAggregation/statusBanner.js
Fixes #4887.
/cc @nainar for copy.
> 🚸  Provide better user feedback for unspecified content-types

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md
> updated to include Google Cloud Marketplace

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity_guide/index.md
> remove unused component from import list

- platform/lib/pipeline/markdownDocument.js
re: #4999 
not confident that this is the right place to do the transformation
> force docs to rewrite curly quotes to straight

- pages/content/amp-dev/documentation/guides-and-tutorials/start/email-inspiration.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/productivity_sender.md
Add guides for productivity based Email senders
> Add email sender guides

- platform/lib/routers/go.js
- platform/lib/routers/go.test.js
> strip trailing slashes for go links

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/how_amp_is_different@pl.md
fixes for some broken translations
cc @ilyaspiridonov
> Polish fixes

- examples/source/e-commerce/Payments_in_AMP.html
- examples/source/user-consent/External_User_Consent_Flow.html
- examples/static/samples/files/external-consent-iframe.html
- examples/static/samples/files/payments.html
fixes #4909
samples still need to be actually updated, but this should start hosting it again
> update old amp-by-example samples

- playground/src/experiments/experiments.js
> substring strings, rather than array indices

- pixi/mocks/pageExperienceCheck/apiResponseNoLoadingExperience.json
- pixi/mocks/pageExperienceCheck/reportDataNoLoadingExperience.json
- pixi/src/checks/PageExperienceCheck.js
- pixi/src/checks/PageExperienceCheck.test.js
> Consider missing loadingExperience in api result

- playground/src/runtime/templates/a4a.template.html
- playground/src/runtime/templates/amphtml.template.html
- playground/src/runtime/templates/story.template.html
I've accidentally ran prettier over the boilerplate
> fix boilerplate formatting

- platform/lib/routers/growPages.js
- platform/lib/routers/notFound.js
- platform/lib/utils/ampOptimizerConfig.js
probably a bad idea, but fixes #5080
> optimize 404 pages

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/index@es.md
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/amp-to-pwa@es.md
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/integrate-with-apps@es.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/combine-amp-pwa@es.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/add_advanced/adding_components@es.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/create/presentation_layout@es.md
> fix ES localization typos

- frontend/scss/components/molecules/biggy.scss
| Before | After |
|-|-|
|![image](https://user-images.githubusercontent.com/254946/102398490-344b6c80-3f94-11eb-86fa-75fcf99b2a33.png)|![image](https://user-images.githubusercontent.com/254946/102398399-15e57100-3f94-11eb-98ec-be8ef176e912.png)|
> Fix mission & vision headings on low res

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@pt_BR.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/intro-to-amphtml-ads@pt_BR.md
- pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/setting_up@pt_BR.md
> brazilian fixes

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer@ar.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer@fr.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer@id.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer@it.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer@ja.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer@ko.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer@pt_BR.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer@vi.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/explainer@zh_CN.md
> fix accidental invalid amp

- examples/source/1.components/amp-autocomplete-email.html
- playground/src/app.js
> add data-amp-autocomplete-opt-in to email playground samples

- frontend/scss/components/atoms/pill.scss
- frontend/templates/views/partials/component-headline.j2
> ✨ Add badge to bento component docs

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@ja.md
> fix ja build

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/media_iframes_3p/third_party_components@ko.md
- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@ko.md
> fix ko build

- pixi/backend/api.js
meant to collect information as narrowly as possible, let me know if it should change
> log analytics events based on pixi searches

- frontend/templates/views/2021/partials/header.j2
> remove out of date banner on the 2021 pages

- platform/lib/routers/notFound.js
fix for #5218
bisecting the issue got me to  [this commit](https://github.com/ampproject/amp.dev/pull/5081) (mea culpa)
I think this was trying to read the file before it had been written. I hit quota limits from bootstrapping before I was able to test this, but I believe it should work
> dont read 404 file before its written

- package-lock.json
- package.json
- pixi/webpack.config.js
> 🎨 Remove CleanWebpackPlugin in favor of FileManagerPlugin

- examples/source/interactivity-dynamic-content/Subscription_Settings/api.js
> 🐛 Fix subscription settings example

- examples/source/interactivity-dynamic-content/Article_Bookmark_Email/api.js
> 🐛 Fix article bookmark email example 

- frontend/scss/components/molecules/tip.scss
* updates the background-color of tip components
* removes border of tip components
> 💄 Update tip style

- examples/source/interactivity-dynamic-content/Subscription_Settings/index.html
> Fix minor issues in subscription settings

- examples/source/1.components/amp-bind.html
This will hopefully finally fix #2760 😄 
@CrystalOnScript will this work for you?
> 🚸 Minor improvements to amp-bind examples

- pages/shared/data/tools.yaml
See https://github.com/ampproject/ampbench#status.
> ampbench has been turned down

- frontend/templates/views/partials/component-intro.j2
Those were `U+00A0` instead of `U+0020`.
Fixes #5260.
> 🐛 Replace non-breaking space with simple space

- frontend/scss/components/atoms/copy-script.scss
- frontend/scss/components/organisms/component-intro.scss
- frontend/templates/views/partials/component-intro.j2
* use radio buttons instead of pills
* wrap script text
> Bento script polish

- pages/content/amp-dev/documentation/guides-and-tutorials/start/bento_guide.md
* remove duplicated heading and changed title to include Bento (better
SEO)
* formatting
* added suggestion to inline CSS
> Bento Guide polish

- playground/webpack.config.js
fixes #5272, not sure how to fully test the playground, however
> shim "this" reference in playground

- frontend/templates/views/examples/documentation.j2
@sebastianbenz does this do anything? it looks like a bunch of noops
> remove noop code

- frontend/templates/views/partials/case-band.j2
- package-lock.json
- package.json
- platform/lib/routers/growPages.js
- platform/lib/utils/ampOptimizerConfig.js
* Enable blurry placeholders (only for homepage to save CPU)
* Transform all stage amp-img to img by increasing the # of hero images
to 5
> Improve stage rendering on homepage

- examples/source/advertising-analytics/Tracking_Core_Web_Vitals.html
> Fix minor docs typo for amp-analytics

- platform/lib/platform.js
- platform/lib/routers/thumbor.js
- platform/lib/templates/ImportBlogFilter.js
Just noticed that this has still been sitting on my machine...
> ✨  Optimize blog images on homepage

- platform/lib/routers/thumbor.js
However that did slip in... sorry!
> 🚑  Do not try to get original query param but set it

- pages/shared/data/faq.yaml
For https://github.com/ampproject/amphtml/issues/32428
Opened a separate issue to automate this task.
> Add tcsemotion to ad vendor lists

- platform/lib/routers/growPages.js
gets rid of warning in server output
> use optimizeHeroImages instead of the deprecated preloadHeroImage

- frontend/scss/_fonts.scss
- frontend/scss/base.scss
- frontend/scss/components/atoms/_headline.scss
- frontend/scss/components/atoms/_text.scss
- frontend/scss/components/atoms/pill.scss
- frontend/scss/components/molecules/_teaser.scss
- frontend/scss/components/molecules/input-bar.scss
- frontend/scss/components/molecules/pixi-recommendations-item.scss
- frontend/scss/components/molecules/pixi-share-dialog.scss
- frontend/scss/components/organisms/_sidebar.scss
- frontend/scss/components/organisms/cities.scss
- frontend/scss/components/organisms/release-schedule.scss
- frontend/scss/components/organisms/tools-teaser.scss
- frontend/scss/components/templates/success-story.scss
- frontend/scss/components/templates/tools.scss
- frontend21/scss/variables.scss
- playground/src/fly-in/fly-in.scss
- playground/src/import-url/import-url.scss
- playground/src/input-bar/autocomplete-item.scss
- playground/src/input-bar/input-bar.scss
- playground/src/share-view/share-view.scss
> Building upon #5334: use system fonts as fallback 

- platform/lib/routers/growPages.js
> preload poppins

- pages/content/shared/copy-pixi-url.html
- pages/content/shared/copy-script.html
- pages/content/shared/experiments.html
- pages/content/shared/footer.html
- pages/content/shared/header.html
Can't quite make out why but this at least seems to fix it. Fixes #5342.
> 🐛 Add explicit paths to shared pages frontmatter

- gulpfile.js/import/importRoadmap.js
* YYYY-DD-MM caused errors since the format should be YYYY-MM-DD
* prevents errors like #5344
* fixes #5344
> ♻️  Validate date format

- package.json
- pages/extensions/amp_dependencies/amp_dependencies_test.py
- pages/extensions/amp_example_preview/util/example_document_test.py
- pages/extensions/amp_example_preview/util/example_exporter_test.py
- pages/extensions/amp_example_preview/util/example_extractor_test.py
- pages/extensions/amp_example_preview/util/preview_test.py
- pages/extensions/internal_links/component_version_resolver_test.py
- pages/extensions/internal_links/pod_internal_link_rewriter_test.py
* update test command
* fix relative imports
* fix deprecation warning
* only check for default version of amp-component
> ✅ Fix grow tests

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/advertise_amp_stories.md
Closes ampproject/amphtml#32680
> 📓Update adsense for story ads

- examples/source/advertising-analytics/Doubleclick_AMP_Story_Ads.html
> fix demo in amp-ads doubleclick docs

- examples/source/advertising-analytics/Publisher_Served_AMP_Story_Ads.html
- examples/source/user-consent/Story_User_Consent.html
> fix sample in Story_User_Consent docs

- pages/content/amp-dev/documentation/components/reference/amp-iframe-v0.1@id.md
Fixed typo `allow<-same-origin` to `allow-same-origin`
> Fixed typo `allow<-same-origin`

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/index.md
> correct AMP Ads CSS Limit in docs

- boilerplate/data/categories.json
- boilerplate/templates/files/websites.html
- boilerplate/templates/partials/structured-data/product.html
> add ecommerce structure data to boilerplate page

- templates/ads/single-video/single-video/single-video.html
using a local ref as I believe the code is intended to be downloaded by others, so didn't want to bake in `<% host.platform %>` or whathaveyou
> use relative path to video rather tha absolute localhost ref

- platform/config/imports/spec.json
Added new doc per [PR #32789](https://github.com/ampproject/amphtml/pull/32789)
> Import new documentation

- frontend/templates/views/partials/teaser-tags.j2
- platform/lib/pipeline/markdownDocument.js
- platform/lib/pipeline/markdownDocument.test.js
> Normalize frontmatter

- frontend/scss/components/organisms/fragment-slider-texts.scss
> adjust breakpoints to stop css overflow issue

- examples/source/1.components/amp-bodymovin-animation.html
> make relative paths absolute in amp-bodymovin example

- pages/content/amp-dev/about/email.html
> update email landing page video

- platform/config/imports/spec.json
This document gets referenced enough that it may need a place on amp.dev
> Add "Video in AMP" to spec.json

- boilerplate/data/categories.json
> include `es` as a lang in the boilerplate

- pages/content/pixi/recommendations/early-iframes.md
- pixi/mocks/ampLinterCheck/apiResponse.js
- pixi/src/checks/AmpLinterCheck.test.js
- pixi/src/utils/checkAggregation/recommendations.js
building off of @sebastianbenz's work, **DO NOT MERGE** until the cloud function features have been upstreamed
> Pixi iframe check

- pages/content/pixi/recommendations/dynamic-layout-extensions.md
- pixi/src/checks/AmpLinterCheck.js
> Pixi: warn amp-subscriptions might cause cls

- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/embed-stories-nonamp.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-debugging.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amp-html-responsive-attributes.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amp-video-interface.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/release-schedule.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-managing-user-state.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md
- pages/shared/data/recent-guides.yaml
these showed up during local build debugging - should they be merged? Or just pulled in on the next deploy
> doc updates

- frontend/templates/views/partials/analytics.j2
add host analytics per @sebastianbenz's request in #5569
> add amp host to analytics

- package-lock.json
- package.json
- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/embed-stories-nonamp.md
- pages/content/pixi/recommendations/hero-images.md
- pixi/cloud-function/package-lock.json
- pixi/cloud-function/package.json
- pixi/mocks/ampLinterCheck/apiResponse.js
- pixi/src/checks/AmpLinterCheck.test.js
- pixi/src/ui/recommendations/RecommendationItem.js
- pixi/src/utils/checkAggregation/recommendations.js
Use check based on Puppeteer to avoid false positives.
Fixes #5416
> Pixi: add new hero images check

- gulpfile.js/build.js
- gulpfile.js/import/importAdVendorList.js
- pages/shared/data/faq.yaml
* list of ad vendors will be fetched and injected during build
* fixes #5322
> ✨ Add automated ad vendor import

- .eslintcache
- .gitignore
- pages/content/pixi/status-banners/all-passed-missing-field-data.md
- pages/content/pixi/status-banners/failed-with-info-missing-field-data.md
- pages/content/pixi/status-banners/passed-missing-field-data.md
- pixi/src/utils/checkAggregation/statusBanner.js
fixes #4877 - maybe? Not 100% sure what @nainar was looking for
> highlight the lack of field data in applicable pixi situations

- platform/lib/routers/thumbor.js
Fixes https://github.com/ampproject/amp.dev/issues/5578 - getting response handling back from the proxy implementation is a little cumbersome, using `resEnd` events et. al. - I think the original implementation never had a chance to write to the response.
Hence I switched to a `node-fetch` based implementation which might be a little bit slower but easier to read and maintain.
> 🎨  Use node-fetch instead of proxy to get optimized images

- examples/source/e-commerce/Product_Browse_Page.html
- examples/source/e-commerce/Product_Page.html
The request now leads to a valid endpoint, but this endpoint redirects to a non existing page. @sebastianbenz does this suffice in terms of showing that a search endpoint could be behind a form?
Fixes #2835.
> 🐛 Fix product page sample

- frontend/templates/views/detail/component-detail.j2
- frontend/templates/views/examples/documentation.j2
- frontend/templates/views/partials/first_survey.j2
- frontend/templates/views/partials/survey.j2
- platform/config/build-info.yaml
- platform/lib/templates/SurveyFilter.js
- platform/lib/templates/index.js
continuing #5533...
moved the j2 file that is importing the content below the `super()` call. I was bisecting the change, and everything passed with just this change left, but I hit a rate limit before this PR completed locally.
> survey. again.

- frontend/templates/views/partials/case-band.j2
- platform/lib/routers/growPages.js
Now that https://github.com/ampproject/amphtml/issues/32644 has been fixed.
> re-enable hero images

- frontend/templates/views/detail/component-detail.j2
- frontend/templates/views/examples/documentation.j2
- frontend/templates/views/partials/first_survey.j2
- frontend/templates/views/partials/survey.j2
- platform/config/build-info.yaml
- platform/lib/templates/SurveyFilter.js
- platform/lib/templates/index.js
reverts #5607, which reverted #5547, which reverted #5545, which reverted #5533, which reverted #5431, which reverted #5419
> use absolute url in survey script src path

- frontend/templates/views/partials/survey.j2
[as per @matthiasrohmer ](https://github.com/ampproject/amp.dev/pull/5620/files/7a7211578376adeca81ca99b19d918c4823014d5#r605157921)
> use correct context for full path survey script

- pages/content/amp-dev/documentation/courses/advanced-course/remembering-what-the-user-has-done.md
Final Glitch example was missing the Glitch link
> Add missing link

- frontend/scss/components/organisms/code-preview.scss
- frontend/templates/views/partials/code-preview/code-preview.j2
Simplify preview to fix amp-iframe reload loop. This unfortunately removes the nice rotation animation :(.
Fixes #5624
> Simplify preview

- .github/workflows/test-default.yml
without this ,it is causing the same hanging issue on PRs from bots
> run default test workflow on external PRs

- pages/static/survey.js
- platform/lib/templates/SurveyFilter.js
handful of fixes to get better survey results
> Survey fixes

- examples/source/interactivity-dynamic-content/Paged_List/index.html
> fix Paged List Example

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/story_ads_best_practices.md
> Link to story ad templates from best practices

- platform/lib/routers/packager.js
Reverts ampproject/amp.dev#5659
> Revert "serve optimized AMP to packager"

- examples/lib/SampleRenderer.js
- examples/source/1.components/amp-analytics/api.js
- examples/source/1.components/amp-live-list/api.js
- examples/source/interactivity-dynamic-content/SeatMap/api.js
- examples/source/interactivity-dynamic-content/SeatMap_Multiple_Selection/api.js
- examples/source/news-publishing/Live_Blog/api.js
- platform/lib/routers/growPages.js
- platform/lib/routers/notFound.js
- platform/lib/utils/ampOptimizer.js
Potentially fixes #4250.
@lluerich, that's what I had in mind. Didn't had time to test this yet.
> 🐛 Optimize pages served by SamplesRenderer

- examples/lib/SampleRenderer.js
- examples/source/1.components/amp-addthis.html
- frontend/templates/views/examples/documentation.j2
Some minor fixes that popped up along the analysis of #4250.
> 🐛 Minor example fixes

- pages/content/pixi/status-banners/all-passed-missing-field-data.md
- pages/content/pixi/status-banners/failed-with-info-missing-field-data.md
- pages/content/pixi/status-banners/passed-missing-field-data.md
> spelling fixes for pixi

- frontend/scss/components/templates/pixi.scss
- frontend/templates/views/partials/pixi/recommendations.j2
> add sticky headers to pixi

- examples/source/1.components/amp-video.html
- examples/source/1.components/amp-youtube.html
> define "supported browsers" in autoplay

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md
> explicitly list version in expiremental components listing

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-optimizer-guide/index.md
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/optimize_amp.md
* list docker and cloudflare worker integration
* mention data-hero
* don't recommend manually optimizing the head
* recommend pixi
> Update AMP Optimizer guides

- frontend/scss/components/molecules/pixi-tooltip.scss
- frontend/scss/components/organisms/release-schedule.scss
- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/vendor-contributions/release-schedule.html
Not quite morning, but here it is. Sorry for the delay.
What has been done:
- try to adapt the page to the new design that Ferdi provided
- implemented architectural changes
- removed most of the duplicate code (mobile/desktop)
What needs to be done:
- new copy on the tooltips, they look kind of lost
- change interim-```div```s to actual ```button```s, but ```amp-script``` wouldn't let me append them to the DOM.
- probably improve a11y, even though there's always the screenreader-compatible version
Fixes #3969.
> 💄 Apply new design to release timetable

- platform/config/environments/production.json
- platform/lib/platform.js
Verified locally that packager works with mjs. Also update packager
instance id.
> Re-enable packager

- platform/lib/routers/notFound.js
> fix the 404 page

- examples/source/user-consent/Granular_User_Consent.html
> Add missing paren

- pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/index.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@ar.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@de.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@fr.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@id.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@it.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@ja.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@pl.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@ru.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@tr.md
- pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@zh_CN.md
> Make fallback example format independent

- .github/workflows/release-staging.yaml
> use package.json and package-lock to calculate hash for build cache

- examples/source/1.components/amp-bind-recaptcha.html
> fix the bind-recaptcha example markup

- .github/workflows/release-staging.yaml
Try to fix build error (see #5752) following https://github.com/pypa/pip/issues/9880#issuecomment-827807619.
> Trigger re-install of python env in CI

- .github/workflows/release-staging.yaml
> re-enable build cache

- .github/workflows/release-staging.yaml
Reverts ampproject/amp.dev#5754
> Revert "re-enable build cache"

- platform/lib/routers/inlineExamples.js
> 🐛 Optimize inline example previews to add component scripts

- platform/config/environments/production.json
- platform/lib/routers/thumbor.js
> Thumbor fix

- templates/websites/gallery/templates/gallery-inner.amp.html
make gallery-inner page responsive
.gallery-inner-background-2 {
position: fixed; // from absolut to fixed
> make gallery-inner page responsive

- frontend21/scss/components/content/teaser-carousel.scss
- frontend21/scss/components/content/teaser.scss
- frontend21/scss/components/home/formats.scss
- frontend21/scss/variables.scss
- hide pagination on devices > 767px
- Adjust teaser width
> Hide carousel pagination on larger devices

- frontend/templates/views/2021/partials/extras/about/components-showcase.j2
- frontend21/scss/components/extra/about/components-showcase.scss
- pages/shared/components-showcase/amp-animation.html
- Remove style duplicates
- add condition to `amp-animation` example in order to render translatable example with markup in example code.
> Refactor grap and go component

- platform/lib/routers/thumbor.js
Gracefully fail if thumbor is not available for remote images. See https://github.com/ampproject/amp.dev/issues/5777#issuecomment-832694224
> Thumbor: fallback for remote images

- platform/lib/routers/thumbor.js
Patrick was of course right! Redirect is the better choice here.
> redirect instead of proxy

- frontend21/webpack.config.js
- gulpfile.js/build.js
- gulpfile.js/develop.js
build is failing currently, merging to unblock before debugging this
> Revert "✨  Overwrite home and about page for default language with ne…w versions (#5841)"

- frontend/templates/views/partials/sidebar.j2
> 🐛 Set fitting default format for single-format examples

- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/web-story-player-guide.md
In my previous PR (#5863) (commit d1eb2d7960018861c2d9263a04db2ba5dff9c1ce) I renamed the file name of the guide and missed adding it again to the commit. This PR adds it back again.
> Web Story Player Guide - add missing file

- pages/content/amp-dev/documentation/guides-and-tutorials/integrate/web-story-player-guide.md
> Fixing formatting on web story player guide

- package-lock.json
- package.json
- playground/webpack.config.js
> fix playground amp-script hash generation

- frontend21/webpack.config.js
- package-lock.json
- package.json
> 📦 Update to svg-spritemap-webpack-plugin v4.0.3

- boilerplate/lib/templates.js
- package-lock.json
- package.json
- platform/lib/samples/CodeSection.js
Resolves #5912, supersedes #5910.
> 📦 Update to highlight.js 11

- frontend/templates/layouts/default.j2
- frontend21/amp-dev.ejs
Wouldn't have discovered this without pixi...
> Preload fonts in new frontend

- playground/src/preview/preview.js
- playground/src/runtime/detector.js
> 🐛 Omit development hash for amp-stories on playground preview

- pages/shared/data/tools.yaml
re: https://github.com/ampproject/amp.dev/commit/d33d1c3f02a1cc8f70417e77c382e20c16c78920#commitcomment-52045558
> add URL for zmooz

- platform/lib/pipeline/componentReferenceImporter.js
- smoke-tests/platform/Routes.test.js
Make sure that the latest version of built-in components is not
overriden.
Fixes #5991
> Fix: built-in components missing

- playground/src/snackbar/snackbar.scss
> 🐛 Add missing imports

- examples/source/visual-effects/CSS_animation_in_email.html
I'd like to contribute these CSS Animation examples for AMP Email. Examples are based on my codepen examples that I share often.
https://codepen.io/david-stys/pen/XWMwygz
In the codepen I do reference [css-tricks](https://css-tricks.com/almanac/properties/t/transform/) where I originally learned about these CSS attributes. However, my examples go beyond what he shares there. 
Thank you for the opportunity to contibute.
> Added AMP Email example demonstrating CSS Animations.

- examples/source/advertising-analytics/Tracking_Core_Web_Vitals.html
> update analytics CWV docs

- examples/static/samples/json/amp-autocomplete-fruit-items.json
Needed by https://github.com/ampproject/amphtml/pull/35305
> Add amp-autocomplete json file for "items" example

- examples/static/samples/files/diy-consent.html
> 🚨  Set viewport

- frontend/templates/views/2021/partials/header.j2
- frontend21/scss/components/header.scss
> ✨ Add tapable nav items

- frontend21/webpack.config.js
Build was failing due to changes in webpack-dev-server 4.0.0
See [changelog](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md).
> 🔧 Update webpack-dev-server config

- pages/shared/data/tools.yaml
We at Plumrocket Inc have migrated our website and changed all links. So we would like to update our links on amp.dev to new ones.
> Update plumrocket links due to website migration

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/advertise_amp_stories.md
> 📧 Use amp.dev group instead of google

- pages/shared/data/tools.yaml
> remove jumprope

- pages/shared/data/faq.yaml
> add mailmodo to the ESP list

- pixi/src/ui/recommendations/RecommendationItem.js
> remove style reset for pixi recommendations

- examples/source/interactivity-dynamic-content/Subscription_Settings/api.js
- examples/source/interactivity-dynamic-content/Subscription_Settings/index.html
> fix broken email sample

- examples/source/interactivity-dynamic-content/Subscription_Settings/index.html
to fully fix for #5289
last commit wasn't included in the first PR (#6245)
> also fix url

- pages/content/amp-dev/documentation/guides-and-tutorials/contribute/index.md
Fixed the broken link related to --- the page you are reading.
> Fixed the broken link.

- pages/content/amp-dev/documentation/guides-and-tutorials/start/create/index.md
- pages/content/amp-dev/documentation/index.html
> Link to new Bento homepage

- pages/content/amp-dev/about/websites-2021.html
- pixi/cloud-function/index.test.js
[test was timing out](https://github.com/ampproject/amp.dev/runs/5210467142?check_suite_focus=true#step:6:146)
also other fixes so the linting/testing would allow me to push
cc @sebastianbenz
> explictly skip test that isnt testing anything

- examples/source/1.components/amp-story-shopping.html
- examples/static/samples/json/amp-story-shopping.json
Adds `productTitle` to the flowers product JSON.
Adds `\n` in examples for `productDetails`
> [amp story shopping] Update product json to have newlines and title

- examples/source/1.components/amp-story-shopping.html
- examples/static/samples/json/amp-story-shopping.json
Updates example to have valid numbers for rating data instead of strings.
> [amp story shopping] Update data to be numbers

- pages/content/amp-dev/documentation/guides-and-tutorials/develop/amp_email_best_practices.md
/to @CrystalOnScript @samouri @sebastianbenz
> Add tips on reducing the size of AMP emails

- playground/src/email-loader/email-loader.js
> fix eml uploader to allow arbitrary preambles

- examples/source/1.components/amp-script/index.html
translation can be overwritten if the language isn't recognized.
> Fix non-constant variable definition

- examples/source/advertising-analytics/Tracking_Core_Web_Vitals.html
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/tracking-engagement.md
- change type=googleanalytics to type=gtag on snippets
- add relevant links to the new GA4 and AMP docs
> add GA4 specific code

- examples/source/advertising-analytics/Tracking_Core_Web_Vitals.html
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/tracking-engagement.md
fix bad link to the gtagjs instructions
> Fix dev link

- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/tracking-engagement.md
turn the normal links into markdown links
> Fix ga4 links

- examples/source/advertising-analytics/Tracking_Core_Web_Vitals.html
- pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/tracking-engagement.md
some fixes for links and wordage
> Fix more links

- gulpfile.js/deploy-static.js
This was the last version we had a successful deployment
> pin the netlify version to 15.7.0

- renovate.json
> Change renovate config to only send out PRs once a week

- pages/shared/data/tools.yaml
> Sort tools alphabetically

- netlify/configs/preview.amp.dev/netlify.toml
> Fix preview.amp.dev redirects on Netlify

- package-lock.json
- package.json
Currently the page generated use Google AMP CDN. This PR changes that.
> Change toolbox to use ampjs version

- package-lock.json
- package.json
This PR will resolve the sidebar issue on the amp.dev.
I was trying to publish an update on optimizer, but I encountered an access issue that requires longer time to resolve. This PR will point to the latest main of optimizer pending resolution.
> Change toolbox optimizer to main branch

- package-lock.json
- package.json
Fixes https://github.com/ampproject/amp.dev/issues/6794
> Change back to published version of amp toolbox

- .gitignore
Automatically generated during build process.
> Ignore artifacts folder in gitignore

- examples/source/advertising-analytics/Tracking_Core_Web_Vitals.html
Fixes https://github.com/ampproject/amp.dev/issues/6383
> Fix extra comma in json example

- .github/workflows/deploy.yaml
- .github/workflows/lint.yaml
- .github/workflows/test-platform.yaml
- .github/workflows/test-playground.yaml
- Dockerfile
- package.json
> Update to nodejs 22

- .github/workflows/deploy.yaml
We are hitting github rate limiting. This PR should improve the situation. Impact on the build time is pretty minimal.
> Add rate limiting for github
