_guides/validate.md

Change loose to lose as this is the correct word for this context.

Fix spelling/grammar mistake in validate.md

---

_reference/validation_errors.md

Note: I'm currently working on intro and validation tables in the amphtml repo as well. This doc needs to go live so that the links in the specs work.

Updates to validation errors doc

---

_guides/analytics/analytics_basics.md
_guides/analytics/deep_dive_analytics.md
_guides/analytics/use_cases.md
_guides/analytics_amp.md
_reference/extended.md

This isn't the easiest PR to review; it's a detailed set of analytics docs.
Rudy reviewed the content quickly in a doc, and I've iterated a good few times.
It would be great to get this in, but I understand things are crazy.

New suite of analytics guides

---

_guides/discovery.md

fix typo: thinks -> things

---

_scripts/import_reference_docs.js

- Added \n to orderer lists, to make it compatible with Jekyll
- Improved regex to avoid catching part of table and copyright
- Fixed handling inline highlights as html code Issue #21

Improved importing script

---

_sass/content.scss

This change addresses the Safari layout bug mentioned in #18

Add flex container style declaration to support older versions of Safari

---

_reference/extended/amp-audio.md

Reference audio instead of animated image

---

_jekyll/sass/header.scss

@pbakaus @Meggin please review. will deploy asap once reviewed

always give hamburger width

---

content/docs/guides/validate.md

I'm inserting newlines before the ```. Hoping this helps.

Attempt to fix the layout of the code sections.

---

content/docs/guides/validate.md

This fixes the TODO, aligning the images better with the text.

Use a table to lay out the validator icons.

---

assets/sass/_header.scss
assets/sass/_nav.scss
views/base.html

bunch of RTL fixes for the hamburger icon and nav.
`rtl` class on `body` was also not being applied (white-space bug)

Bunch of RTL fixes

---

content/docs/guides/amp_replacements.md

Added reference to HTML layout spec per issue #173

Add reference to HTML layout spec; fixes #173

---

content/docs/reference/validation_errors.md

Fixes https://github.com/ampproject/amphtml/issues/4791

Update validation error doc to reflect current state

---

content/docs/get_started/create/basic_markup.md
content/includes/blog_feed.yaml

Two changes
1) Since <meta charset...> is required after <head>, put it next in the list.
2) Move <script ... v0.js"></script> to second child of <head>, since v0.js will block showing the page.
And apparently also update the blog feed.
I didn't change other language pages, please let me know if I should do anything there.

Update required mark up

---

.gitignore
content/docs/reference/components.md
scripts/import_docs.js

Created new landing page for Components that lists all components.  Previously was pulling in extensions  README but this list of components goes beyond that.
@pbakaus - please review

Create landing page for all components

---

scripts/import_docs.js

Fixes https://github.com/ampproject/amphtml/issues/5555.
Play around with it on [regex101.com](https://regex101.com/r/w88hCA/1).

Ignore relative URLS to the same document

---

content/docs/get_started/create/basic_markup@es.md
content/docs/get_started/create/include_image@es.md
content/docs/get_started/create/prepare_for_discovery@es.md
content/docs/get_started/create/presentation_layout@es.md

**Spanish translation fixed on get started**

Spanish translation fixed on get started

---

.travis.yml

Maybe this will fix the build

---

scripts/import_docs.js

Correct code for case when pointing to your own local version of amphtml.

Fix script when running local build

---

content/docs/get_started/login_requiring/summary.md

Bullets needed a space above to render correctly on amproject site.
to/ @kul3r4 - ptal

Correct bullets so they appear correctly

---

content/docs/get_started/create/basic_markup@zh_CN.md
content/learn/how-amp-works@zh_CN.md

html <head> should not translated to 其标头.All html element should be keep in original.

---

content/docs/reference/components.md

Added new components to list and split some categories based on feedback from Malte.  Note: This is just a minor fix-up until I do the "real" categorization/tagging.
to/ @pbakaus

Updated components list with new components

---

content/docs/guides/ads_on_amp.md
content/docs/guides/ads_on_amp/_blueprint.yaml
content/docs/guides/ads_on_amp/ads_getting_started.md
content/docs/guides/ads_on_amp/ads_tips.md
content/docs/guides/engagement.md

Add new pages on ads and tips for improving engagement under Guides.

---

content/docs/guides/ads_on_amp/ads_tips.md

TOC in guide isn't needed and makes for funny rendering.

Remove unnecessary toc

---

content/docs/get_started/login_requiring/add_comment.md
content/docs/get_started/login_requiring/add_comment@ko.md

Correcting link for amp-mustache per issue - https://github.com/ampproject/amphtml/issues/7149
to: @pbakaus

Fixing broken link for amp-mustache component

---

content/docs/reference/components.md

Updated category naming, slotted components into correct category, and added new components to list.

Update categories for components

---

views/base.html

Here's a possible fix for #331.  I'm adding the [locale](https://github.com/ampproject/docs/blob/master/podspec.yaml#L6) as the lang attribute.

Added lang attribute to html base

---

content/docs/guides/responsive_amp/placeholders.md

Issue came up in https://github.com/ampproject/amphtml/issues/7690
/to @bpaduch

Documenting that placeholder will always fill the parent

---

content/learn/about-how.yaml

Fixes issue #335.
to/ @pbakaus 
cc/ @cramforce, @chenshay

Improve wording re: async JavaScript

---

content/learn/case-studies/terra.md

Small word change so it doesn't sound like "2 times times faster"

Remove redundant 'times' from '2x times'

---

views/partials/head.html

See https://github.com/ampproject/amphtml/pull/8123 for more details.

Opt in visibility-v3 experiment

---

content/docs/contribute/contribute@es.md
content/learn/overview@es.yaml

Some corrections in spanish
Broken links.
Merged PR #388 here.

Some corrections in spanish

---

firebase.json

When click "Docs" should land on new landing page.

Remove redirects for docs index page so it can go to new landing page

---

.github/ISSUE_TEMPLATE

Requesting defined information for any reported issues on ampproject.org.

Creating ISSUE_TEMPLATE

---

views/partials/head.html

Unlaunch visibility v3 until more data is collected

---

content/pages/home.html

Make v2 and v3 visibility more comparable

---

content/learn/overview.yaml
content/learn/overview@it.yaml
content/learn/who-uses-amp@ko.yaml
translations/ar/LC_MESSAGES/messages.po
translations/de/LC_MESSAGES/messages.po
translations/es/LC_MESSAGES/messages.po
translations/fr/LC_MESSAGES/messages.po
translations/id/LC_MESSAGES/messages.po
translations/it/LC_MESSAGES/messages.po
translations/ja/LC_MESSAGES/messages.po
translations/ko/LC_MESSAGES/messages.po
translations/messages.pot
translations/pl/LC_MESSAGES/messages.po
translations/pt_BR/LC_MESSAGES/messages.po
translations/ru/LC_MESSAGES/messages.po
translations/th/LC_MESSAGES/messages.po
translations/tr/LC_MESSAGES/messages.po
translations/zh_CN/LC_MESSAGES/messages.po

- Removed '@' on text strings that didn't need them
- Ran `grow extract` to extract the translations and update all the .po files

Remove unnecessary @'s + update translations by grow extraction

---

content/docs/guides/deploy/analytics_amp.md
content/docs/guides/deploy/analytics_amp/analytics_basics.md
content/docs/guides/deploy/analytics_amp/deep_dive_analytics.md
content/docs/guides/deploy/analytics_amp/use_cases.md

Added callouts to navigate to other sections + added callout formatting for already called out info.
to: @rudygalfi 
fixes #315

Improve callouts in Analytics guides & navigation

---

content/includes/home.yaml

Per #378 swap wired case study with womp

---

content/docs/guides/author_develop/amp_replacements.md

Minor fix on title 

---

translations/es/LC_MESSAGES/messages.po

More translations in Spanish, and minor corrections.

More translations in Spanish, and minor corrections.

---

assets/sass/pages/_post-detail.scss

Per #349 fix bullet styling in case studies

---

content/docs/guides/author_develop/pwa-amp.md
content/docs/guides/author_develop/pwa-amp/amp-in-pwa.md

PWAMP: Add paragraph that describes how to figure out when Shadow AMP is ready

---

views/partials/head.html

@pbakaus Please merge at your discretion. No urgency to deploy.

Visibility V3 is in PROD: remove doc override.

---

content/docs/contribute/integrate-your-tech.md

Added new guide on Integrating your Technology for 3Ps.
to: @jasti 
cc: @pbakaus

Add Integrate your Technology guide to Contribute section

---

content/support/faqs/supported-platforms@es.md

New file for ../es/support/faqs/supported-platforms
***
I allow edits from maintainers; feel free to modify if you need it.

New supported-platforms@es.md file

---

content/pages/home.html
views/partials/head.html

Fix homepage title

---

scripts/import_docs.js

Automatic dependency injection for imported docs, fixes #457

---

content/pages/home.html

Keep eventCategory same, changed the eventAction name.
@dvoytenko @lannka

Add identical hidden-v3 trigger monitoring

---

content/learn/overview.yaml

Update overview with information about linking and making page discoverable per issue: https://github.com/ampproject/amphtml/issues/5756.
Also: fix broken links, and make some links relative instead of pointing to github project.
to: @pbakaus 
Fixes: https://github.com/ampproject/amphtml/issues/5756

Update overview with info on linking

---

translations/it/LC_MESSAGES/messages.po

All translations have been made.

Updated italian translations

---

content/pages/home.html

Fix: Use the correct visibilitySpec config

---

views/partials/breadcrumb-nav.html

Reverts ampproject/docs#486
/cc @derekcecillewis

Revert "Add localization support for breadcrumbs and other minor improvements"

---

content/docs/contribute/integrate-your-tech@es.md

`integrate-your-tech.md` in spanish :es: :+1:

New integrate-your-tech@es.md

---

translations/ko/LC_MESSAGES/messages.po

Re-using existing wordings + a little help from Google Translate. :)
@techhtml: Can you confirm my updates are correct?

Some basic Korean text updates

---

content/learn/who/advertisers.yaml

Updated 'it's' to 'its' for "Even the most memorable creative won't serve its purpose if..."

Update advertisers.yaml: Fixed grammar for 'its'

---

content/learn/case-studies/wego.md

This is also a problem in the attached PDF: https://www.ampproject.org/static/img/case-studies/wego.pdf

Removed extra 'hotels' in the first paragraph

---

content/learn/case-studies/nobroker.md

Just cleaning up a spacing issue.

Added space between ' drive"connections" '

---

views/partials/head.html

Adds a structured data header of type "WebPage" to the ampproject.org site.  
Uses description if available.

Add structured data

---

examples/src/thirdparty.html

Code samples for "Include Third-Party Content".
Related to: #553

Add code samples for third-party guide

---

content/docs/guides/responsive_amp/placeholders.md
content/docs/guides/responsive_amp/placeholders@es.md
content/docs/guides/responsive_amp/placeholders@ko.md

Add embedded examples to placeholders guide

---

content/docs/guides/responsive_amp/art_direction.md
content/docs/guides/responsive_amp/art_direction@es.md
content/docs/guides/responsive_amp/art_direction@ko.md

Add demos in art_direction guide

---

scripts/update_platforms_page.js

Add link for wordpress.com

---

content/support/faqs/overview.md

Add faq on AMP is not just for mobile

---

content/docs/guides/analytics_amp/analytics-vendors.md

Add note for vendor.js file

---

content/pages/home.html

Clean up redundant analytics trigger as we have launched hidden-v3. And are now removing v3 experimental flag.

Clean up redundant analytic trigger in home page

---

content/docs/guides/ads_on_amp/ads_getting_started.md
content/docs/guides/ads_on_amp/ads_getting_started@ko.md

PR for Improvement: Fixes #572

PR for Improvement: #572 

---

content/docs/guides/analytics_amp/analytics-vendors.md

Improvement to **Note** at Line 191

Add note for oewa vendor

---

content/docs/guides/responsive_amp/responsive_design.md

Clarify CSS for max-width per #581

---

content/docs/tutorials/create/include_image@es.md

Correct link in tutorial (ES)

---

content/docs/guides/ads_on_amp/ads_getting_started.md

Updated the term "pub" to "publisher" for more clarity.

Updated ads_getting_started.md by modifying "pub" to "publisher"

---

examples/src/amplist.html
examples/src/data/amp-list-data.json
examples/src/data/amp-list-urls.json
gulpfile.js

Created samples for amp-list that will be embedded in amp-list ref doc.

Add samples for amp-list ref doc

---

assets/sass/_header.scss

Fixes #509 
Tested on various heights + devices.

Make submenu restricted height and scrollable

---

translations/ja/LC_MESSAGES/messages.po

Dear AMP Project.
I've complete translate menu items into Japanese.
Please take a look.
Thanks.

Translate menu items into Japanese

---

content/docs/guides/pwa-amp.md

Typo in pwa-amp.md

---

content/docs/reference/components.md
scripts/component_categories.json

Import amp-ad-exit component to docs

---

content/docs/getting-started.md
content/docs/guides/analytics_amp@de.md
content/includes/menu.yaml

Creating a no-nonsense, get up and running, quickstart guide.  This guide is purposely minimal as it's a quick reference for users to use AMP (one stop-shop for boilerplate etc.).  Any detailed instructions will remain (or be added) to the existing "Create your first AMP page" tutorial.
Preview here: https://barb-ampdocs.firebaseapp.com/docs/getting-started/
Tidbit: also fixed analytics guide syntax.

Create "Getting Started" quickstart guide

---

assets/sass/_footer.scss
views/partials/footer.html

Improve visibility of privacy link

---

content/docs/guides/responsive_amp/placeholders.md

Related to #618 - Added info on interaction of placeholders & fallbacks that will be common text for amp-twitter and amp-list.  Per https://github.com/ampproject/amphtml/pull/10488#issuecomment-316133089.

Add interaction behav for placeholders & fallbacks

---

content/docs/guides/analytics_amp/analytics-vendors.md
content/docs/guides/analytics_amp/analytics-vendors@es.md
content/docs/guides/analytics_amp/analytics-vendors@id.md
content/docs/guides/analytics_amp/analytics-vendors@ja.md
content/docs/guides/analytics_amp/analytics-vendors@ko.md
content/docs/guides/analytics_amp/analytics-vendors@pt_BR.md
content/docs/guides/analytics_amp/analytics-vendors@zh_CN.md

Add Rambler/TOP-100 analytics vendor to docs

---

content/learn/overview.yaml
content/learn/overview@ar.yaml
content/learn/overview@de.yaml
content/learn/overview@es.yaml
content/learn/overview@fr.yaml
content/learn/overview@id.yaml
content/learn/overview@it.yaml
content/learn/overview@ja.yaml
content/learn/overview@ko.yaml
content/learn/overview@pl.yaml
content/learn/overview@pt_BR.yaml
content/learn/overview@ru.yaml
content/learn/overview@th.yaml
content/learn/overview@tr.yaml
translations/ar/LC_MESSAGES/messages.po
translations/fr/LC_MESSAGES/messages.po
translations/pl/LC_MESSAGES/messages.po
translations/ru/LC_MESSAGES/messages.po
translations/th/LC_MESSAGES/messages.po
translations/tr/LC_MESSAGES/messages.po

- Use localized Intro videos on Overview page, where available; default to English

Use localized videos for Overview pages

---

content/docs/guides/validate.md

Add validation episode of amplify to validator guide

---

content/docs/guides/validate@es.md

From https://github.com/ampproject/docs/commit/4b3a10f61422dc5097d572bcd84a1fe0135336f9 and other differences.

Fix youtube and other changes

---

content/docs/contribute/contribute@es.md
content/docs/guides/discovery@es.md
content/docs/guides/responsive_amp/control_layout@es.md
translations/es/LC_MESSAGES/messages.po

fixes https://github.com/SidVal/docs/issues/35

More diffs in translations files

---

content/docs/tutorials/create/include_image@id.md

Created 'Read On' callout section with previous text, and modified link name for 'Include Iframes and Media' to 'Include Images & Video' for Indonesian.

(ID) Created 'Read On' callout, modified link name

---

content/docs/tutorials/create/include_image@ja.md

Created 'Read On' callout section with previous text, and modified link name for 'Include Iframes and Media' to 'Include Images & Video' for Japanese.

(JA) Created 'Read On' callout, modified link name

---

content/docs/tutorials/create/include_image@zh_CN.md

Created 'Read On' callout section with previous text, and modified link name for 'Include Iframes and Media' to 'Include Images & Video' for Chinese.

(zh_CN) Created 'Read On' callout, modified link name

---

content/docs/tutorials/create/include_image@ko.md

Created 'Read On' callout section with previous text, and modified link name for 'Include Iframes and Media' to 'Include Images & Video' for Korean.

(KO) Created 'Read On' callout, modified link name

---

content/docs/tutorials/create/include_image@pt_BR.md

Created 'Read On' callout section with previous text, and modified link name for 'Include Iframes and Media' to 'Include Images & Video' for Portuguese.

(pt_BR) Created 'Read On' callout, modified link name

---

content/docs/guides/analytics_amp/analytics-vendors.md

Adds description and link to Top.Mail.Ru AMP-analytics configuration details.

Top.Mail.Ru AMP-analytics

---

content/docs/getting-started@ja.md

Dear AMP Project.
I've complete translate getting-started into Japanese.
(I copied getting-started.md and translated getting-started@ja.md)
Please take a look.
Thanks.

Translate getting-started into Japanese

---

content/docs/guides/responsive_amp@ko.md

(EN) Watch UpperQuad talk about the AMPproject site redesign, including the challenges of using AMP for the first time.
(KO) AMP를 처음 사용할 때 어려운 점을 비롯하여 새롭게 설계된 AMP 프로젝트 사이트에 관한 UpperQuad의 이야기를 들어보세요.

Updated video caption for responsive_amp@ko.md

---

content/docs/guides/responsive_amp@ja.md

(EN) Watch UpperQuad talk about the AMPproject site redesign, including the challenges of using AMP for the first time.
(JA) 初めて AMP を利用するにあたっての課題など、UpperQuad における AMP プロジェクトでのサイト再設計に関する話をご覧になれます。

Updated video caption for responsive_amp@ja.md

---

content/docs/guides/responsive_amp@id.md

(ID) Tonton UpperQuad yang menyampaikan perancangan ulang situs proyek AMP, termasuk tantangan dalam menggunakan AMP untuk pertama kalinya.

Updated video caption for responsive_amp@id.md

---

content/docs/guides/responsive_amp@pt_BR.md

(EN) Watch UpperQuad talk about the AMPproject site redesign, including the challenges of using AMP for the first time.
(pt_BR) Veja o que a equipe da UpperQuad tem a dizer sobre a reforma do site AMPproject e os desafios de usar AMP pela primeira vez.

Updated video caption for responsive_amp@pt_BR.md

---

content/docs/guides/responsive_amp@zh_CN.md

(EN) Watch UpperQuad talk about the AMPproject site redesign, including the challenges of using AMP for the first time.
(zh_CN) 观看 UpperQuad 工作人员介绍 AMP 项目网站重新设计相关内容（包括初次使用 AMP 会遇到的难题）的视频。

Updated video caption for responsive_amp@zh_CN.md

---

views/partials/head.html

see https://support.google.com/analytics/answer/7486764

Use Google Analytics AMP Client ID API

---

views/partials/head.html

Revert "Use Google Analytics AMP Client ID API"

---

content/docs/tutorials/add_advanced/adding_carousels.md
content/docs/tutorials/add_advanced/adding_components.md
content/docs/tutorials/add_advanced/fonts.md
content/docs/tutorials/add_advanced/navigating.md
content/docs/tutorials/add_advanced/tracking_data.md

I made some clarifications for things I found a little bit confusing when walking through this codelab.
/cc @pbakaus

Add clarifications to "Add advanced AMP features" codelab

---

content/docs/tutorials/converting/building-page.md
content/docs/tutorials/converting/discoverable.md
content/docs/tutorials/converting/resolving-errors.md

In preparation for the Roadshow I walked through the "Convert HTML to AMP" tutorial and made some changes/additions that may make things more clear for people not familiar with AMP.
cc/ @pbakaus

Add some clarifications to the "Convert HTML to AMP" Tutorial

---

content/docs/guides/responsive_amp/style_pages.md
content/docs/guides/responsive_amp/style_pages@ar.md
content/docs/guides/responsive_amp/style_pages@de.md
content/docs/guides/responsive_amp/style_pages@es.md
content/docs/guides/responsive_amp/style_pages@fr.md
content/docs/guides/responsive_amp/style_pages@id.md
content/docs/guides/responsive_amp/style_pages@it.md
content/docs/guides/responsive_amp/style_pages@ja.md
content/docs/guides/responsive_amp/style_pages@ko.md
content/docs/guides/responsive_amp/style_pages@pl.md
content/docs/guides/responsive_amp/style_pages@pt_BR.md
content/docs/guides/responsive_amp/style_pages@ru.md
content/docs/guides/responsive_amp/style_pages@th.md
content/docs/guides/responsive_amp/style_pages@zh_CN.md

Fixes https://github.com/ampproject/amphtml/issues/11611

Remove filter from disallowed styles

---

content/docs/reference/components.md
scripts/component_categories.json

The amp-vk component is now available and in production, so including it in the docset.

Add amp-vk component to docs

---

scripts/update_platforms_page.js

As per https://github.com/ampproject/docs/issues/686 I've added Kentico as a supported platform (CMS).

Added Kentico as an AMP-enabled platform

---

content/docs/getting-started.md
content/docs/tutorials/create/basic_markup.md

Add note to getting started materials (quickstart and tutorial) to strongly consider using HTTPS vs HTTP.  
Fixes: https://github.com/ampproject/docs/issues/670
cc: @rudygalfi

Add note encouraging use of HTTPS

---

scripts/update_platforms_page.js

Fixes https://github.com/ampproject/docs/issues/525

Added Textpattern CMS

---

content/support/faqs/supported-platforms.md
content/support/faqs/supported-platforms@es.md
content/support/faqs/supported-platforms@id.md
content/support/faqs/supported-platforms@ja.md
content/support/faqs/supported-platforms@ko.md
content/support/faqs/supported-platforms@pt_BR.md
content/support/faqs/supported-platforms@zh_CN.md
scripts/update_platforms_page.js

Fixes: https://github.com/ampproject/amphtml/issues/11899

Update supported vendors and platforms

---

content/docs/guides/analytics_amp/analytics-vendors.md

Fixes https://github.com/ampproject/amphtml/issues/11932

Adds Facebook Pixel documentation

---

content/includes/menu.yaml

Fixes https://github.com/ampproject/docs/issues/777

Added link to AMP status pg

---

assets/sass/_content.scss

Add styles for use in imported reference docs, particularly amp-story.

Add special styles for imported component doc - ampstory

---

scripts/update_platforms_page.js

Fixes https://github.com/ampproject/docs/issues/800

Add arc publishing to CMS list

---

content/pages/home.html

To monitor the fix of https://github.com/ampproject/amphtml/issues/12761
cc @lannka

Add more visible tracking examples to home page

---

assets/sass/_syntax_highlighting.scss
podspec.yaml

Adding configuration for the new code highlight to use classes.

---

scripts/update_platforms_page.js

As per https://github.com/ampproject/docs/issues/811 I've added Rabbit as a supported platform (CMS).

Added Rabbit as an AMP CMS platform

---

content/learn/case-studies/category/ecommerce.md
content/learn/case-studies/eski_mobi.md
content/learn/case-studies/event_ticket_center.md
content/learn/case-studies/fastcommerce.md
content/learn/case-studies/greenweez.md
content/learn/case-studies/milestone.md
content/learn/case-studies/wego.md
content/learn/case-studies/wompmobile.md

Renaming references of "e-commerce" and "E-commerce" to "ecommerce" and "Ecommerce" per standards in style guide.

Rename e-commerce to ecommerce per standards

---

content/learn/who/ad-tech-platforms.yaml
content/learn/who/amp-ads.yaml

Fixes: https://github.com/ampproject/docs/issues/818, https://github.com/ampproject/docs/issues/817

Fix wording per rebrand of amp ads

---

views/partials/head.html

Opt in url-replacement-v2 experiment

---

content/docs/tutorials/interactivity/prereqs-setup.md
content/docs/tutorials/interactivity/prereqs-setup@es.md

Fixes https://github.com/googlecodelabs/advanced-interactivity-in-amp/issues/2.
/to @bpaduch

Fix wrong dir in interactivity tutorial

---

content/docs/tutorials/visual_story.md
content/docs/tutorials/visual_story/congratulations.md
content/docs/tutorials/visual_story/setting_up.md

Adding note about whitelist signup to tutorial per https://github.com/ampproject/amphtml/pull/13438#issuecomment-364876643.

Add notes about origin trial for amp-story

---

content/includes/stories.yaml

Fix SB Nation story link

---

assets/sass/pages/_about-overview.scss
content/learn/overview.yaml
views/about-overview.html

- Adding more info about "What is AMP"
- Reformatted page to accommodate info
- Added CTA to design principles

Add more info to What is page + reformat

---

content/includes/events.yaml

- Added roadshow events; removed past events.

Update events listing

---

content/learn/about/benefits.yaml
content/learn/overview.yaml
content/learn/who/ecommerce.yaml
views/about-benefits.html
views/about-overview.html
views/about-who-vertical.html

Links for resources were going to english version, revised so it goes to localized resource, if present.

Fixed resource links so hits localized if present

---

content/docs/guides/analytics_amp/analytics-vendors.md

follow up to ampproject/amphtml#13096

Add Treasure Data support

---

content/pages/404.html
translations/ar/LC_MESSAGES/messages.po
translations/de/LC_MESSAGES/messages.po
translations/es/LC_MESSAGES/messages.po
translations/fr/LC_MESSAGES/messages.po
translations/id/LC_MESSAGES/messages.po
translations/it/LC_MESSAGES/messages.po
translations/ja/LC_MESSAGES/messages.po
translations/ko/LC_MESSAGES/messages.po
translations/messages.pot
translations/pt_BR/LC_MESSAGES/messages.po
translations/ru/LC_MESSAGES/messages.po
translations/tr/LC_MESSAGES/messages.po
translations/zh_CN/LC_MESSAGES/messages.po

- Made strings on 404 page as translatable variables
- Re-extracted translations to pull new translation strings.

404 page text made loc variables

---

content/docs/design/responsive_amp/control_layout.md

Update doc for new `intrinsic` layout (perhttps://github.com/ampproject/amphtml/pull/12729).
Also update doc with latest updates to layout spec.

Add intrinsic to layout doc

---

.editorconfig
assets/sass/pages/amp-roadshow.scss
content/includes/amp-roadshow.yaml
content/pages/amp-roadshow.html

Update Roadshow 2018 map styles

---

scripts/update_platforms_page.js

Fixes https://github.com/ampproject/docs/issues/889

Add TownNews as CMS

---

content/docs/ads_analytics/analytics-vendors.md

This is the updated copy from the product manager of the Browser team, which is responsible for the AMP feature.
Thank you!

Update analytics vendor copy for New Relic.

---

assets/sass/pages/amp-roadshow.scss

add taipei pin position.
PTAL.

AMP Roadshow: Fix Taipei pin position

---

content/docs/design/responsive_amp/style_pages.md
content/docs/design/responsive_amp/style_pages@ar.md
content/docs/design/responsive_amp/style_pages@de.md
content/docs/design/responsive_amp/style_pages@es.md
content/docs/design/responsive_amp/style_pages@fr.md
content/docs/design/responsive_amp/style_pages@id.md
content/docs/design/responsive_amp/style_pages@it.md
content/docs/design/responsive_amp/style_pages@ja.md
content/docs/design/responsive_amp/style_pages@ko.md
content/docs/design/responsive_amp/style_pages@pt_BR.md
content/docs/design/responsive_amp/style_pages@ru.md
content/docs/design/responsive_amp/style_pages@tr.md
content/docs/design/responsive_amp/style_pages@zh_CN.md

Removed disallowed styles per https://github.com/ampproject/amphtml/issues/13701.

Update disallowed styles

---

content/docs/troubleshooting/validation_errors@es.md

Ref: https://github.com/ampproject/docs/commit/07f3d83f675f0e9297da5291b95e46733bb7d600

Add text about valueless attributes workaround

---

content/docs/ads_analytics/analytics_amp/deep_dive_analytics.md

Add cautious note about not using amp-analytics for click tracking for AMPHTML ads

Add exception case for click tracking

---

assets/sass/_content-post.scss
content/docs/ads_analytics/ads_on_amp.md
content/docs/ads_analytics/ads_on_amp/ads_getting_started.md
content/docs/ads_analytics/ads_on_amp/ads_tips.md
content/docs/ads_analytics/ads_vendors.md

- Extracted advertising vendors into separate doc, so it's visible and accessible in "Advertising docs"
- Cleaned up some existing ads docs

Create separate doc for ad vendors

---

.gitignore
scripts/import_docs.json

- Import Ad Technology Integration guide to ads docs
- clean up gitignore

Improve Ad Tech Integration guide to docs

---

content/docs/fundamentals/add_advanced/congratulations@ko.md

Please review the translation for KO.

Added translations for KO on May 8,2018

---

content/docs/build.md
content/docs/design/responsive_amp/responsive_design.md

Reference new Responsive Design in AMP YT video in docs.

Add references to new responsive vid

---

content/reference/experimental.md

Reflect what's in https://github.com/ampproject/amphtml/blob/master/tools/experiments/README.md

Update doc with latest info

---

assets/sass/pages/_design-principles.scss
content/learn/about/amp-design-principles.yaml
views/design-principles.html

Fixes https://github.com/ampproject/docs/issues/961

Add vid to design princ

---

content/reference/components.md
content/reference/components/_blueprint.yaml
scripts/component_categories.json

Import `amp-next-page` and `amp-3d-gltf` components to docs.

Import new components

---

build_scripts/build.sh
build_scripts/deploy.sh

Deploy staging from `master`, now that `parallel` has been merged to it

---

content/docs/design/visual_story.md
content/docs/design/visual_story/congratulations.md
content/docs/design/visual_story/validation.md

Remove developer log screen from tut

---

content/includes/menu.yaml
content/support/developer.md
content/support/developer/documentation-bug.md
content/support/developer/platform-bug.md
content/support/developer/slack.md
content/support/developer/stack-overflow.md

Cleaning up duplication in Dev Support menu.

Clean up menus for dev support

---

content/docs/fundamentals/add_advanced@zh_CN.md

Adding Chinese translation add_advanced@zh_CN.md

Adding Chinese translation add_advanced@zh_CN.md

---

content/docs/fundamentals/add_advanced/setting_up@zh_CN.md

Adding Chinese translation - setting_up@zh_CN.md

Adding Chinese translation - setting_up@zh_CN.md

---

content/docs/design/responsive_amp/custom_fonts.md
content/docs/design/responsive_amp/custom_fonts@es.md
content/docs/design/responsive_amp/custom_fonts@id.md
content/docs/design/responsive_amp/custom_fonts@ja.md
content/docs/design/responsive_amp/custom_fonts@ko.md
content/docs/design/responsive_amp/custom_fonts@pt_BR.md
content/docs/design/responsive_amp/custom_fonts@zh_CN.md

Add url into custom_fonts.md to update the url list.

---

content/docs/fundamentals/add_advanced/setting_up@id.md
content/docs/fundamentals/add_advanced/setting_up@ko.md
content/docs/fundamentals/add_advanced/setting_up@pt_BR.md
content/docs/fundamentals/add_advanced@id.md
content/docs/fundamentals/add_advanced@pt_BR.md
content/docs/fundamentals/how_cached@id.md

- content/docs/fundamentals/add_advanced/setting_up@id.md
- content/docs/fundamentals/add_advanced/setting_up@ko.md
- content/docs/fundamentals/add_advanced/setting_up@pt_BR.md
- content/docs/fundamentals/add_advanced@id.md
- content/docs/fundamentals/how_cached@id.md

Adding six (6) translations – id (3), pt_BR (2), ko (1)

---

content/docs/fundamentals/add_advanced/congratulations@id.md
content/docs/fundamentals/add_advanced/congratulations@pt_BR.md
content/docs/fundamentals/add_advanced/congratulations@zh_CN.md

- content/docs/fundamentals/add_advanced/congratulations@id.md
- content/docs/fundamentals/add_advanced/congratulations@pt_BR.md
- content/docs/fundamentals/add_advanced/congratulations@zh_CN.md

Added ID, pt_BR, and zh_CN translations for add_advanced > congratulations.

---

content/docs/fundamentals/add_advanced/navigating@id.md
content/docs/fundamentals/add_advanced/navigating@ko.md
content/docs/fundamentals/add_advanced/navigating@pt_BR.md
content/docs/fundamentals/add_advanced/navigating@zh_CN.md

Hi, 
Please process the translations for  KO, ID, pt_BR and zh_CN. 
Thanks!

Added translation for navigating KO, ID, pt_BR and zh_CN

---

content/reference/components.md
scripts/component_categories.json

Included new component in docs: amp-embedly-card

---

content/docs/getting_started/quickstart.md
content/docs/getting_started/quickstart@es.md
content/docs/getting_started/quickstart@id.md
content/docs/getting_started/quickstart@ja.md
content/docs/getting_started/quickstart@ko.md
content/docs/getting_started/quickstart@pt_BR.md
content/docs/getting_started/quickstart@zh_CN.md

Fix 404s identified via GA 404s report.

Fix 404s links

---

content/docs/design/visual_story@ko.md

Translation for the first page of the tutorial.

KO translation for AMP stories tutorial

---

content/docs/design/visual_story@ko.md

Fixes overlooked issues with PR #1083

fixed localization issues

---

translations/ko/LC_MESSAGES/messages.po

Translation for https://www.ampproject.org/ko/stories/ and the KO menu (only for "AMP stories" menu).
Sample screenshot of the translated:

KO translation for messages.po for stories.yaml.

---

content/docs/design/visual_story/add_more_pages@ko.md

KO translation for visual_story/add_more_pages@ko.md.

---

.travis.yml
build_scripts/deploy.sh

Debugging step for #1097
Addresses https://github.com/firebase/firebase-tools/issues/865#issuecomment-412885341

Make firebase logs available when deploy fails

---

content/docs/design/visual_story/start_story@ko.md

Add KO translation for content/docs/design/visual_story/start_story.md.

---

content/docs/design/visual_story/create_cover_page@ko.md

KO translation for visual_story/create_cover_page.md.

---

content/docs/design/visual_story/animating_elements@ko.md

KO translation for visual_story/animating_elements.md.

---

content/docs/design/visual_story/create_bookend@ko.md

 KO translation for visual_story/create_bookend.md.

---

content/docs/analytics/analytics-vendors.md

Add a description for Moat Analytics within analytics-vendors.md.

Add Moat to analytics vendors documentation.

---

content/includes/amp-roadshow.yaml
content/includes/events.yaml

Removed Recife roadshow and updated next event to Sao Paulo

---

assets/sass/pages/amp-roadshow.scss
content/includes/amp-roadshow.yaml
content/includes/events.yaml

I still think there is an error on t[his event page](https://events.withgoogle.com/amp-roadshow-gurgaon/). Gurgaon is pretty far from Mumbai...

Updated upcoming roadshows

---

content/includes/roadmap.json
scripts/import_roadmap.js

Fixed roadmap importer by ignoring cards that do not have associated issues

---

TRANSLATIONS.md
content/docs/contribute/contribute.md

Links didn't match what I predicted for files. Fixed it.

fixed github links

---

assets/sass/_cards.scss
assets/sass/_doc-nav.scss
assets/sass/_global.scss
assets/sass/_header.scss
assets/sass/_nav.scss
assets/sass/_promo.scss
assets/sass/_sidebar.scss
assets/sass/_toc.scss

I changed font-weight from 300 to 400.
PTAL :)

improve Korean legibility

---

content/learn/who-uses-amp@es.yaml
content/learn/who-uses-amp@id.yaml
content/learn/who-uses-amp@it.yaml
content/learn/who-uses-amp@ja.yaml
content/learn/who-uses-amp@ko.yaml
content/learn/who-uses-amp@pt_BR.yaml
content/learn/who-uses-amp@zh_CN.yaml

Hi, 
Please review the translations for who-uses-amp yaml files. 
Thanks,
Manju

Added translations for ES, ID, IT, JA, KO, BR and CN

---

content/learn/overview@ja.yaml
content/learn/overview@ko.yaml

Hi, 
Please review the translated files for overview@ja.yaml and overview@ko.yaml. 
Thanks,
Manju

Added translations for JA and KO

---

views/partials/promo_banner.html

Removes the AMP Contributor Summit promo.

Remove AMP Contributor Summit promo

---

content/docs/analytics/analytics-vendors.md
content/docs/analytics/analytics-vendors@es.md
content/docs/analytics/analytics-vendors@id.md
content/docs/analytics/analytics-vendors@ja.md
content/docs/analytics/analytics-vendors@ko.md
content/docs/analytics/analytics-vendors@pt_BR.md
content/docs/analytics/analytics-vendors@zh_CN.md

added Pressboard to analytics-vendors

added Pressboard to analytics-vendors

---

content/docs/analytics/analytics-vendors@es.md
content/docs/design/responsive_amp/control_layout@es.md
content/docs/design/responsive_amp/placeholders@es.md
content/docs/interaction_dynamic/live_blog@es.md

Hi, 
Please review translated files for ES. 
Thanks,
Manju

Added 4 ES translations

---

content/docs/analytics/analytics-vendors@id.md
content/docs/design/responsive_amp/control_layout@id.md
content/docs/design/responsive_amp/placeholders@id.md
content/docs/interaction_dynamic/live_blog@id.md

Hi, 
Please review 4 ID translated files. 
Thanks,
Manju

Added translations for ID

---

content/docs/analytics/analytics-vendors@ja.md
content/docs/design/responsive_amp/control_layout@ja.md
content/docs/design/responsive_amp/placeholders@ja.md
content/docs/interaction_dynamic/live_blog@ja.md

Hi,
Please review the translated files for JA. 
Thanks,
Manju

Added translation files for JA

---

content/docs/analytics/analytics-vendors@pt_BR.md
content/docs/design/responsive_amp/control_layout@pt_BR.md
content/docs/design/responsive_amp/placeholders@pt_BR.md
content/docs/interaction_dynamic/live_blog@pt_BR.md

Hi,
Please review the translated files for BR and let me know for changes. 
Thanks,
Manju

Added translated files for BR

---

scripts/component_categories.json

amp-recaptcha-input is not ready and has no documentation - should not be imported yet.

removed amp recaptcha

---

content/docs/ads/amphtml_ads@es.md
content/docs/getting_started/create/basic_markup@es.md

es-Translations for amphtml_ads and basic_markup.

es- Translations for amphtml_ads and basic_markup.

---

content/docs/ads/amphtml_ads@pt_BR.md
content/docs/getting_started/create/basic_markup@pt_BR.md
content/docs/troubleshooting/validation_errors@pt_BR.md

pt_br- Translations for amphtml_ads, basic_markup and validation_errors.

pt_br- Translations for amphtml_ads, basic_markup and validation_errors.

---

content/docs/ads/amphtml_ads@zh_CN.md
content/docs/getting_started/create/basic_markup@zh_CN.md
content/docs/troubleshooting/validation_errors@zh_CN.md

zh_CN- Translations for amphtml_ads, basic_markup and validation_errors.

zh_CN- Translations for amphtml_ads, basic_markup and validation_errors.

---

content/docs/ads/ads_vendors@es.md
content/docs/getting_started/visual_story/create_cover_page@es.md
content/reference/experimental@es.md

es- Translations for ads_vendors, create_cover_page and experimental.

es- Translations for ads_vendors, create_cover_page and experimental.

---

content/docs/ads/ads_vendors@id.md
content/docs/getting_started/visual_story/create_cover_page@id.md
content/reference/experimental@id.md

id- Translations for ads_vendors, create_cover_page and experimental.

id- Translations for ads_vendors, create_cover_page and experimental

---

content/docs/ads/advertise_amp_stories.md
content/docs/ads/story_ads_best_practices.md

Missed some links before the push. Fixed them.

fixed links

---

MAINTENANCE.md

Please note: `personalization` is new as a tag

Add more frontmatter vars

---

content/pages/amp-conf@ja.html

A draft for Japanese translation.
- Tried to express the event to be a community event (expressions like: 共有、一緒に、開発者のための）
CC: @pbakaus

Updating Ja translation

---

content/docs/analytics/analytics-vendors.md

Added Retargetly vendor description inside content/docs/analytics/analytics-vendors.md file.

Added Retargetly as a new analytics vendor

---

.gcloudignore
package.json

* filter non-needed folders for deploy
* build boilerplate and playground

Improve build & deploy

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@es.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@id.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@ja.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@ko.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@pt_BR.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@zh_CN.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@ar.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@es.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@fr.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@id.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@it.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@ja.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@ko.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@pt_BR.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@ru.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@tr.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@zh_CN.md
platform/lib/build/pageMinifier.js
platform/lib/pipeline/gitHubImporter.js
platform/lib/pipeline/grow.js
platform/lib/pipeline/roadmapImporter.js
platform/lib/routers/pages.js

There were indeed broken references in the docs I migrated last-minute, sorry.

🐛 Fix broken references.

---

pages/content/amp-dev/about/websites.html
pages/content/amp-dev/index.html

This updates the benefits for home and websites. They are still updated manually on both pages, the plan to have them share the same data source is still up, but I don't wan't to break anything today, soooo 😉

💬 Update benefits for home and Websites

---

frontend/scss/components/organisms/consent.scss

Cookie layer pops up from the right side now

💄 change cookie layer from left to right

---

frontend/scss/components/molecules/format-toggle.scss

Changed fontsize and padding on smaller viewsize

💄 Fix cut off for format toggle text elements

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@es.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@id.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@ja.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@ko.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@pt_BR.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/common_attributes@zh_CN.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@ar.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@es.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@fr.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@id.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@it.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@ja.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@ko.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@pt_BR.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@ru.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@tr.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental@zh_CN.md
pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/deep_dive_analytics@fr.md

Fixes reference and rendering issues introduced by #1402.

🐛 Fix Grow rendering issues in documents

---

examples/static/samples/standalone/amp-ad.html
examples/static/samples/standalone/amp-email.html
examples/static/samples/standalone/amp-story.html
examples/static/samples/standalone/amp-website.html
pages/content/amp-dev/index.html
platform/lib/platform.js
playground/backend/api.js

The format samples are still placeholders.

fix links in homepage sampler

---

content/includes/amp-conf.yaml

Changing the word "Signed Exchange" to "Signed HTTP Exchanges"
https://tools.ietf.org/id/draft-yasskin-http-origin-signed-responses-02.html

Fixing title

---

examples/static/samples/standalone/amp-story.html
examples/static/samples/standalone/amp-website.html
frontend/scss/components/organisms/sampler.scss
pages/content/amp-dev/index.html
playground/src/document/controller.js
playground/src/editor/editor.scss
playground/src/embed-mode/embed.critical.scss
playground/src/index.hbs
playground/src/preview/preview.js

improve playground embed preview

---

pages/content/amp-dev/about/how-amp-works.html

Updated link tags to reflect new folder structure

🐛 fixed broken links to component reference

---

frontend/scss/components/organisms/story-carousel.scss

Broken arrow icon in amp-carousel on what-is-amp/stories is now fixed

🐛 fix broken icons on story carousel buttons

---

frontend/scss/components/templates/success-story.scss

Text was aligned incorrectly on mobile devices. Fixes issue #1548

📱 fix text alignment for content with text layout

---

frontend/scss/components/molecules/banner.scss
frontend/scss/components/molecules/code-snippet.scss
frontend/scss/components/organisms/news.scss
frontend/templates/views/partials/burger-menu.j2
frontend/templates/views/partials/case-grid.j2
frontend/templates/views/partials/footer.j2
frontend/templates/views/partials/format-visuals/websites.j2
frontend/templates/views/partials/header.j2
pages/content/amp-dev/index.html

Fixes a lot of small accessibility issues and while doing so bumps our Lighthouse a11y score from 65 to 100.

Fixes a11y issues.

---

frontend/templates/views/partials/category-filter.j2
frontend/templates/views/partials/teaser.j2
platform/lib/common/filteredPage.js

This will take care of removing filter bubbles that don't have content on filtered pages.

✨ Remove empty filter bubbles.

---

platform/lib/common/filteredPage.js

This will enable filtered links with hashes.

♻️ Use URL over raw strings to construct filtered URLs

---

frontend/scss/components/atoms/sample-preview-title.scss
frontend/scss/components/molecules/device-toggle.scss
frontend/scss/components/organisms/preview-pane.scss
frontend/templates/views/examples/preview.j2

💄 Rearrange sample preview header.

---

.dockerignore
.gcloudignore
pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-email-format.md

This reverts commit fdcad673806ebb7d86f384c560966cdf2d9abf4b, reversing
changes made to 609471de9dea6de14a6774a2aca1148015c4cf40.

Revert "Merge branch 'future' of github.com:ampproject/docs into future"

---

package-lock.json
package.json

This will include changes from https://github.com/ampproject/amp-toolbox/pull/261 moving all @keyframe animations to a style tag at the bottom of the document.

upgrade optimizer

---

examples/source/1.components/amp-iframe.html

use new Google Maps API key

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-email-format.md
platform/lib/pipeline.js
platform/lib/pipeline/componentReferenceImporter.js
platform/lib/pipeline/gitHubImporter.js
platform/lib/pipeline/specImporter.js

* refactors github importer
* makes branch a parameter

Import specs from master

---

examples/source/0.introduction/AMPHTML_Email_Hello_World.html

Fix broken email hello world sample

---

pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/deep_dive_analytics.md

This PR addresses minor spelling errors in the English version of deep_dive_analytics

📖 Correct typographical errors in deep_dive_analytics.md

---

pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md

Duplicate for #1655 for `future`/amp.dev.

✨ Add Kenshoo analytics vendor.

---

examples/source/interactivity-dynamic-content/Poll.html

* no longer needs SSR
* clean up CSS
* use table
* simplify markup

Fix poll sample

---

frontend/scss/components/molecules/table.scss
frontend/scss/components/templates/docs-detail.scss
frontend/templates/views/partials/teaser.j2
platform/lib/pipeline/markdownDocument.js

- Fixes #1701 
- Reliably sets TOC for imported documents (components don't have one currently)
- Includes the image fix from Andrew (which I am not to sure about)

Small various fixes.

---

examples/source/0.introduction/AMPHTML_Ads_Hello_World.html
examples/source/1.components/amp-date-display.html
examples/source/advertising-analytics/AMPHTML_ads_vs_non_AMP_ads.html
examples/source/e-commerce/Shopping_Cart.html
examples/source/interactivity-dynamic-content/SeatMap_Multiple_Selection.html
platform/lib/build/samplesBuilder.js

- AMPHTML Ads Hello World
- amp-date-display
- AMPHTML Ads vs non-AMP ads
- Shopping Cart
- SeatMap Multiple Selection (requires SSR, therefore marked as `draft: true` temporarily)

🍱 Migrate missing samples.

---

platform/lib/utils/CachingStrategy.js

* 1d for pdf
* 1d for zip
* 1w for images

Improve caching

---

frontend/templates/layouts/default.j2
frontend/templates/views/examples/documentation.j2
frontend/templates/views/partials/service-worker.j2

Fix component imports

---

frontend/scss/components/organisms/banner.scss
frontend/scss/components/organisms/mini-card-list.scss

Remove important from CSS

---

pages/content/amp-dev/about/mission-and-vision.html

Fix duplicate tutorials

---

platform/lib/routers/pages.js

* show 404 if path is a dir instead of a file
* async filesystem access

Improve page serving

---

frontend/templates/views/partials/header.j2
pages/content/amp-dev/404.html
pages/content/amp-dev/500.html

Fix home links

---

pages/content/amp-dev/documentation/guides-and-tutorials/develop/amp_story_best_practices.md

Amp stories best practices tables still contined a couple of images whos sizes were not behaving responsively due to imporper sizes and missing figure wrappers

🐛 fixed image sizing in some tables

---

examples/source/1.components/amp-springboard-player.html
examples/source/1.components/amp-web-push.html
examples/source/e-commerce/AMP_for_E-Commerce_Getting_Started.html
examples/source/interactivity-dynamic-content/Favorite_Button.html
examples/source/interactivity-dynamic-content/Friend_Requests_Email.html
frontend/templates/views/partials/example-sidebar.j2

Fix drafted samples and e-commerce Get Started.

---

frontend/templates/layouts/default.j2
platform/lib/common/filteredPage.js
platform/lib/common/referrerNotification.js
platform/lib/routers/pages.js

I'm not proud of what I've done here...

show a referrer notification

---

examples/source/1.components/amp-addthis.html

migrate amp-addthis sample

---

frontend/templates/views/partials/structured-data.j2
platform/lib/build/samplesBuilder.js

- Fixes #1771.
- Uses the wide sharing image instead of the square for Facebook because their doing it differently than they've documented it 🤷‍♂️
- Fixes the differentiation in images for different paths

🐛 Fix structured data.

---

firebase.json

✨ Add specific rules for /latest/blog/.

---

pages/translations/messages.pot

Fixing a minor typo

---

frontend/templates/views/detail/component-detail.j2

Fixing minor typo pt2

---

frontend/scss/components/organisms/burger-menu.scss

🐛 Fix hidden burger menu on mobile iOS viewer

---

firebase.json

Fixes #1817 and the redirect for AMP4email spec.

 🐛Fix redirects for ampproject.org

---

platform/lib/routers/pages.js

Checks for shouldFilterFormat and addReferrerNotification were always
true as they were testing the existence of a promise.

Fix format handling

---

README.md

Remove "cd platform" from README

---

pages/content/amp-dev/community/governance.md
pages/content/amp-dev/documentation/guides-and-tutorials/contribute/ad-integration-guide.md
pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-analytics-tools.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/a4a_spec.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-managing-user-state.md
platform/lib/pipeline/componentReferenceImporter.js
platform/lib/pipeline/gitHubImporter.js
platform/lib/pipeline/markdownDocument.js
platform/lib/pipeline/specImporter.js

✨ Rewrite GitHub relative paths when importing docs.

---

frontend/scss/components/organisms/component-visual.scss

🐛  fix component visual link overlaping on hover

---

examples/source/1.components/amp-recaptcha-input.html

relates to #1414 
relates to https://github.com/ampproject/amphtml/pull/21664
Simple removes the experiment block from the example. 😄 
cc @sebastianbenz

Removes the experiment from amp-recaptcha-input

---

examples/static/samples/linker/demo-page.html

It fixes the issue #1854 ( When you click on "Please click to continue" on https://amp.dev/static/samples/linker/demo-page.html you hit a 404 )

Fix broken link on sample/link/demo-page.html

---

platform/lib/common/filteredPage.js
platform/lib/routers/pages.js

* avoid performing work in the constructur
* don't throw an error if no format is available

Refactor FilteredPages

---

frontend/scss/components/templates/home.scss
frontend/templates/views/partials/consent.j2
pages/content/amp-dev/index.html

As per Bibianas e-mail: 
>in Germany, Austria, Norway, Greece and Luxembourg must pass through the double opt-in process.
Fixes #1859.

✨ Use amp-geo to show different newsletter link

---

platform/config/environments/development.json

develop enviornment was broken do to missing packager config in develop.json #1834

🐛 develop.json was missing packager

---

pages/shared/data/amp-conf.yaml

- Updating Mitsuhiro Naganuma's profile
- s/Yahoo Japan/Yahoo! JAPAN/g

Updating bio, title, session title and description

---

examples/source/1.components/amp-call-tracking.html

Relative URLs are disallowed and currently it does not validate. Changing it to absolute URL

Update URL for attribute 'config'

---

frontend/templates/layouts/sitemap.xml
pages/content/amp-dev/404.html
pages/content/amp-dev/500.html
pages/content/amp-dev/offline.html
pages/content/shared/_blueprint.yaml
pages/content/shared/footer.html
pages/content/shared/header.html
platform/config/podspec.yaml

Fixes #1871 by discovering undocumented Grow features 😁

🐛Normalize sitemap paths

---

examples/source/1.components/amp-install-serviceworker.html

https://amp.dev/documentation/examples/components/amp-install-serviceworker/?format=websites#

remove duplicate tip

---

platform/config/go-links.yaml

@matthiasrohmer this has to go into the build

Add Shopify shortlink

---

frontend/scss/components/organisms/case-band.scss

Caseband animation is a bit heavy and some users may prefer to disable this animation. Media query is added to allow this.  #1902

♿️ added prefers reduced motion for caseband

---

playground/src/runtime/templates/email.template.html

Remove title from email template

---

frontend/scss/components/templates/courses-overview.scss
frontend/templates/views/partials/sidebar.j2
pages/content/amp-dev/documentation/courses/index.html
pages/content/amp-dev/documentation/courses/teachers.md

Include area to showcase our new coursework videos!
Change name and order of courses landing page in sidebar

Include videos in courses page, other minor changes

---

examples/source/1.components/amp-ad.html

Fix amp-ad's A9 parameter

---

frontend/scss/components/organisms/jumpto-list.scss
frontend/scss/components/templates/events.scss
pages/content/amp-dev/events/amp-conf-2019.html
pages/content/amp-dev/events/amp-conf-2019@ja.html

Still a little unbalanced but at least usable. I'll pass this on to one of my fellow devs on Tuesday for further improvement.

💄 Improve responsive behaviour for AMP Conf page.

---

platform/lib/platform.js

Renders the following for every path served to 
```
/index.html: 555.241535ms
/fonts/noto-sans-v7-latin-regular.woff2: 11.360644ms
/fonts/noto-sans-v7-latin-700.woff2: 9.499834ms
/fonts/poppins-v5-latin-700.woff2: 9.220892ms
...
```

✨ Add timer to express.

---

platform/lib/build/pageTransformer.js

🐛 Correctly build amphtml URL.

---

playground/src/formatter/index.js

Fix playground formatter

---

pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md
pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors@zh_CN.md

✨ Add [Vpon Analytics](https://cmp.vpadn.com/dmp/doc/amp_analytics.html) documentation to the supported Analytics Vendors docs.

Add Vpon Analytics service documentation

---

pages/content/amp-dev/events/amp-conf-2019.html
pages/content/amp-dev/events/amp-conf-2019@ja.html

Fix AMP Conf 2019 day 1 livestream YouTube link.

Fix AMP Conf 2019 day 1 livestream YouTube link.

---

platform/config/go-links.yaml

...would like to use this in I/O talk on 5/9!

Shortlink for code for e-commerce project

---

platform/config/go-links.yaml

related: https://github.com/ampproject/amphtml/pull/22011

Add new short link to pub checklist

---

examples/source/interactivity-dynamic-content/ComboBox.html

Update combobox example with amp-autocomplete usage

---

examples/source/1.components/amp-autocomplete.html
examples/source/interactivity-dynamic-content/ComboBox.html

@sebastianbenz for review and merge approval /cc @cvializ

Toggle ampExperiment for amp-autocomplete examples

---

platform/config/go-links.yaml

Shortlink for CORS documentation

---

platform/config/go-links.yaml

add optimize amp shortlink

---

frontend/scss/components/organisms/preview-pane.scss

🐛 Fix scroll issue on iOS

---

pages/content/amp-dev/about/stories.html

Add anchor link

---

pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/configure-analytics/analytics-vendors.md

Update to add Tealium Collect
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/0.1/vendors/tealiumcollect.js

adding Tealium

---

frontend/templates/views/partials/fragment-slider-texts.j2

Sorry I haven't had a chance to check for formatting errors... but I edited the text you so kindly wrote. If it looks ok, and if you have time to merge this before my talk tomorrow, that would be superwonderlicious 😄

Revised language for AMP Camp demo

---

frontend/scss/components/molecules/code-snippet.scss

scrollbar inside code snippets was too small to see and grab. Closes #1603

💄 update scrollbar in code snippets

---

package-lock.json
package.json

Update amp-by-example dependency

---

pages/content/amp-dev/documentation/guides-and-tutorials/contribute/index@ko.md

🐛 Remove invalid path from Korean document

---

pages/content/amp-dev/documentation/guides-and-tutorials/develop/advertise_amp_stories.md

@jasti and I thought it was a good idea to add a link here, since publishers are often uploading the ads on behalf of the advertiser.

🔗Add link to ad manager docs

---

boilerplate/build.js
boilerplate/data/formats.json
boilerplate/templates/index.html
boilerplate/templates/styles/code-snippet.scss
boilerplate/templates/styles/main.scss
frontend/scss/components/molecules/format-toggle.scss

💄Update boilerplate generator theme

---

frontend/templates/layouts/default.j2
frontend/templates/layouts/sitemap.xml
frontend/templates/views/examples/preview.j2
frontend/templates/views/partials/burger-menu.j2
frontend/templates/views/partials/header.j2
frontend/templates/views/partials/structured-data.j2
pages/extensions/inline_text_assets/inline_text_assets.py

In an attempt to get the CI branch clean: those are all changes that I've made to increase build performance: all disk-read operations of the inline-text-assets extension are now cached, unnecessary template logic is removed, template caching is used for building the navigation.

Perf various things around Grow.

---

examples/lib/SampleRenderer.js

🐛 Use url.resolve instead of path.join for protocol

---

examples/lib/SampleRenderer.js

🐛 Fix path handling in SampleRenderer.

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-email-format.md

https://en.wikipedia.org/wiki/MIME#Multipart_messages
> The last boundary must have two hyphens at the end.

It is the last multipart that needs to end with double dashes

---

platform/lib/build/samplesBuilder.js

🐛 Correctly read sample category metadata

---

examples/source/interactivity-dynamic-content/Paged_List.html

Fixes the sidebar navigation on https://amp.dev/documentation/examples/interactivity-dynamic-content/paged_list/

🐛 Fix sidebar navigation on paged_list page

---

frontend/templates/views/detail/docs-detail.j2
frontend/templates/views/examples/documentation.j2
frontend/templates/views/partials/author.j2
platform/lib/build/samplesBuilder.js

I think the author / contributor mechanism for articles is a good way to know whom to contact to flag issues - this PR gives us the ability to the same with samples, using the metadata section.

Allow samples to specify author like articles

---

frontend/scss/components/templates/roadmap.scss
pages/content/amp-dev/community/roadmap.html

✨ Render markdown in roadmap items.

---

examples/source/1.components/amp-iframe.html
examples/static/samples/files/resizable-iframe.html

🐛 Fix resizable iframe example

---

examples/source/interactivity-dynamic-content/Advanced_Server_Request.html
examples/source/interactivity-dynamic-content/Article_Bookmark_Email.html
playground/src/title-updater/base.js

Playground: extract title from URL

---

pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/style_pages.md

fixes issue [2125](https://github.com/ampproject/docs/issues/2125)

updated wording per issue 2125

---

pages/content/amp-dev/documentation/guides-and-tutorials/develop/animations/triggering_css_animations.md

fixed the t

---

examples/source/1.components/amp-iframe.html
examples/static/samples/files/amp-iframe.html
examples/static/samples/files/resizable-iframe.html

* use amp.dev color scheme
* simplify embed using box-sizing
* write message to console
* simplify JS
* fix sample formatting

Polish amp-iframe sample

---

boilerplate/build.js

👽 Adapt boilerplate generator build to new optimizer API

---

.travis.yml
examples/source/0.introduction/AMPHTML_Ads_Hello_World.html
gulpfile.js/build.js

Currently the ad is not shown, because the size is empty:
https://preview.amp.dev/documentation/examples/introduction/amphtml_ads_hello_world/embed

Add missing size for hello world ad

---

.travis.yml
gulpfile.js/test.js

In preparation of CI for prod. I know YAML is hard to break but a corrupt `go-links.yaml` for example would make application startup fail currently.

✨ Lint YAML files.

---

examples/source/1.components/amp-recaptcha-input.html

amp-mustache is a `custom-template` not a `custom-element`

Update amp-mustache import.

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md

Add Origin Trial details to experimental page.

Update with Origin Trial notes

---

examples/source/user-consent/Geolocation-based_Consent_Flow.html

🐛 Update broken amp-consent example URLs

---

frontend/templates/layouts/default.j2
gulpfile.js/develop.js
pages/content/amp-dev/documentation/guides-and-tutorials/contribute/translations.md

💬 Make translation hint more actionable

---

frontend/scss/components/organisms/component-sidebar.scss
frontend/scss/components/organisms/sidebar.scss

:bug: Decrease width of mobile sidebar

---

examples/source/1.components/amp-experiment.html
gulpfile.js/develop.js

🐛 Correct links to specific experiments

---

examples/source/1.components/amp-form.html

🐛 Fix broken amp-form sample

---

MAINTENANCE.md

How to include code samples in lists 

---

examples/api/amp-form.js

🐛 Fix amp-form verification example

---

pages/content/amp-dev/documentation/guides-and-tutorials/index.html

🐛 Update link to platform and vendors page

---

pages/content/amp-dev/community/platform-and-vendor-partners.html

💬 Add Distributed Media Lab to Platform & Vendor partners

---

pages/content/amp-dev/documentation/guides-and-tutorials/develop/amp_story_best_practices.md

fixes #2287 replaces new links and copy to working stories.

🐛Replace broken links to stories #2287

---

examples/api/amp-form.js

🐛 Fix error message response

---

examples/source/multimedia-animations/Supported_media_types_in_AMP_Stories.html

fix #2313 by adding /static/samples/ to src

🐛 Fix src of story image and video

---

frontend/scss/components/molecules/tip.scss
frontend/scss/components/organisms/help.scss
frontend/scss/components/templates/component-detail.scss

fix #2112 and #2308 add padding-top to the help-Section and on mobile remove side-padding from help section on component-detail sites

🐛 Add and edit padding to the help section

---

frontend/scss/_variables.scss
frontend/scss/components/atoms/sidebar-toggle.scss
frontend/scss/components/molecules/banner.scss
frontend/scss/components/organisms/burger-menu.scss
frontend/scss/components/organisms/footer.scss
frontend/scss/components/organisms/header.scss
frontend/templates/views/partials/banner.j2
frontend/templates/views/partials/header.j2

- Definitly fixes one bug where the footer overlays the dropdown navigation on pages with less content, see #2309 
- Also fixes/improves some issues that happens after temporally hiding the banner
- Furthermore starting with extracting specific values into variables, see #2272

Fix header and navigation styling issues

---

examples/source/1.components/amp-carousel.html

Fixes https://github.com/ampproject/amphtml/issues/22877

Fix broken link in carousel example

---

platform/lib/utils/credentials.js

Fixes promise rejection error.
Fixes case of credential keys.

🐛Fix credentials util

---

pages/content/amp-dev/community/governance.md
pages/content/amp-dev/documentation/components/reference/amp-accordion.md
pages/content/amp-dev/documentation/guides-and-tutorials/contribute/ad-integration-guide.md
pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-your-analytics-tools.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/a4a_spec.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cache-debugging.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-html-layout/index.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-components.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-css.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-format.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-html.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/email-spec/amp-email-structure.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md
pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/amp-managing-user-state.md
pages/content/amp-dev/support/index.md
pages/shared/data/blog.yaml
platform/lib/pipeline/componentReferenceImporter.js
platform/lib/pipeline/markdownDocument.js
platform/lib/pipeline/specImporter.js

Fixes #2277 importer now writes comments to imported files with a link to the original file

🌠 Add comments to imported files with link to source-file

---

pages/content/amp-dev/documentation/guides-and-tutorials/contribute/integrate-amphtml-email.md

-  Add explanation of target audience
-  Remove `Host AMP JavaScript` - this is a recommendation for AMP caches
-  Fix CORS section

Update Email Provider integration

---

package.json

`npm install` changes it every time I run it.

Update indent in package.json

---

pages/content/amp-dev/events/amp-cs-2019.html

Adds a link to apply to the AMP Contributor Summit.
/cc @pbakaus @vishaldodiya

Adds a link to apply to the AMP Contributor Summit

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/experimental.md

See https://github.com/ampproject/amphtml/pull/22796.

Update docs for cookie->localStorage experiments change

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/how_amp_pages_are_cached.md

snippet on amp4email docs being exempt from an amp cache

update cache doc for amp for email

---

frontend/templates/views/partials/format-toggle.j2

🐛 Do not show format toggle for courses

---

examples/api/amp-access.js

🐛 Fix deprecation warning

---

frontend/templates/views/partials/tools-teaser.j2
pages/content/amp-dev/documentation/tools.html

✨ Allow SSR for tools page

---

platform/lib/routers/pages.js

Not the best stylewise I guess, but we should have something like this 😉

✨ Make debugging SSR in pages router easier

---

frontend/templates/views/partials/tools-teaser.j2
pages/content/amp-dev/documentation/tools.html

Revert Allow SSR for tools page

---

platform/lib/build/samplesBuilder.js

Makes use of ampproject/amp-by-example#2039

Use new formats() in ABE instead of parseFormats()

---

pages/content/amp-dev/documentation/guides-and-tutorials/contribute/email-viewer.md

To avoid confusion about the nature of the Viewer.

Update title for AMP Viewer docs

---

pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md

Arbitrary quick fix to test contributing process

fixed title casing

---

contributing/documentation.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/advertise_amp_stories.md

* import missing component
* update contribution guide to explain how to import a component
Fixes #2522

Fix image not showing

---

package.json
platform/lib/build/pageTransformer.js
platform/lib/routers/pages.js

This moves optimizing out of the PageTransformer into the pages router.

♻️ Run amp-toolbox-optimizer on request

---

examples/source/interactivity-dynamic-content/Poll/api.js
examples/source/interactivity-dynamic-content/Poll/index.html
package-lock.json

Migrated the backend/poll.go from ampbyexample.com to amp.dev.
It updates the example [here](https://amp.dev/documentation/examples/interactivity-dynamic-content/poll/?format=websites).

♻️ Migrate poll backend

---

frontend/templates/views/partials/tools-teaser.j2
pages/content/amp-dev/documentation/tools.html

Reverts ampproject/amp.dev#2554

Revert ✨ Add SSR for tools page

---

examples/source/e-commerce/Checkout_Flow/index.html

🐛 Fix wrong api endpoint

---

gulpfile.js/develop.js

#2530 changed a path name which breaks template watching.

🐛 Reenable template watching for development

---

examples/source/interactivity-dynamic-content/SeatMap/api.js
examples/source/interactivity-dynamic-content/SeatMap/index.html
examples/source/interactivity-dynamic-content/SeatMap_Multiple_Selection/api.js
examples/source/interactivity-dynamic-content/SeatMap_Multiple_Selection/index.html

Add missing server-side rendering on both seat map examples located [here](https://amp.dev/documentation/examples/interactivity-dynamic-content/seatmap/?format=websites) and [here](https://amp.dev/documentation/examples/interactivity-dynamic-content/seatmap_multiple_selection/?format=websites).

🐛 Add missing SSR

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amp-boilerplate@ja.md

#2569
Hi.
I translated amp-boilerplate.md into japanese.

Add amp-boilerplate.md new japanese translation.

---

.github/ISSUE_TEMPLATE/--content-proposal-.md
.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/content.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/tool.md

Adding content proposal template

Update issue templates

---

examples/source/interactivity-dynamic-content/Advanced_Server_Request.html
examples/source/interactivity-dynamic-content/Article_Bookmark_Email/index.html
examples/source/interactivity-dynamic-content/Conference_Survey_Email.html

🐛 Switch relative to absolute paths

---

frontend/templates/views/partials/tools-teaser.j2
pages/content/amp-dev/documentation/tools.html

Reverts ampproject/amp.dev#2601

⏪ Allow SSR for tools page

---

gulpfile.js/build.js

🐛 Leave spaces intact when minifying pages

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml@ja.md

#2628
Hi.
I translated amphtml.md into japanese.

Translate amphtml.md into Japanese.

---

pages/extensions/amp_dependencies/auto_dependency_injector.py

Fix problems with build of merged PR https://github.com/ampproject/amp.dev/pull/2665
https://travis-ci.org/ampproject/amp.dev/jobs/565924391

Fix encoding problems with auto dependency importer

---

examples/source/interactivity-dynamic-content/Poll/index.html

This should fix https://github.com/ampproject/amp.dev/pull/2551#discussion_r309353242 / #2671.

🐛 Fix endpoint url

---

pages/content/amp-dev/support/faq/supported-browsers.md

sync with https://github.com/ampproject/amphtml/blob/master/contributing/DEVELOPING.md#supported-browsers

fix supported browsers

---

pages/content/amp-dev/message.html
platform/lib/runtime-log/LogProvider.js
platform/lib/runtime-log/LogProvider.test.js
smoke-tests/platform/Routes.test.js

* download messages from cdn.ampproject.org
* add smoke test for logging endpoint
* small UI tweaks to message page

Enable runtime log endpoint

---

gulpfile.js/build.js

Reverts ampproject/amp.dev#2685.

Revert "♻️ Use RCS string replace over DOM method"

---

pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@es.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@id.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@ja.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@ko.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@pt_BR.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/remote-data@zh_CN.md

Fixes #2502  Fix link in documentation files that was broken.

🐛 Fix broken link in documentation

---

frontend/scss/_mixins.scss
frontend/scss/components/molecules/format-visual-websites.scss
frontend/scss/components/molecules/format-visual.scss
frontend/scss/components/molecules/visual-image.scss
frontend/templates/views/partials/format-visuals/websites.j2

This PR removes one unused keyframe mixin and refactors the highlight-code animation of the format-visual for websites.
For further information please see related issue #2686 
Closes: #2686

🐛 Fix invalid keyframe properties

---

pages/extensions/markdown_in_html/__init__.py
pages/extensions/markdown_in_html/html_block_processor.py
pages/extensions/markdown_in_html/html_block_processor_test.py

Remove markdown=span attribute after markdown was rendered

---

frontend/templates/views/partials/structured-data.j2

Fix title handling for AMP components

---

examples/source/e-commerce/Hotel/api.js
examples/source/e-commerce/Hotel/index.html
examples/static/samples/json/rooms.json

Migrated the hotel example backend from [glitch.com](https://glitch.com/~amp-by-example-live) to amp.dev.
It updates the example [here](https://amp.dev/documentation/examples/e-commerce/hotel/?format=websites).
I added some dates in the ```rooms.json``` so that the backend will check if those are available on selected dates.

♻️ Migrate/hotel

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/spec/amphtml.md

Include canvas in html tags spec
Related: ampproject/amphtml#23658

Update AMP html tags spec

---

platform/lib/routers/packager.js

warning: 199 - "inner != outer; fallback url https://amp.dev/ != https://amp.dev"

Fix SXG warning

---

examples/source/interactivity-dynamic-content/ComboBox.html

fixes https://github.com/ampproject/amphtml/issues/19914

Fix combobox sample

---

gulpfile.js/build.js
package-lock.json

Reverts ampproject/amp.dev#2722. Thoroughly tested this on staging now. Works but still breaks for some pages. Will start implementing this as an optimizer transformer tomorrow to finally fix this.

Revert ♻️ Do not use DOM for selector rewriting

---

pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/secure-pages.md

Resolves [issue #1316](https://github.com/ampproject/amphtml/issues/1316)

added document on securing AMP docs with CSP

---

pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/responsive_design.md

resolves issue [#22430](https://github.com/ampproject/amphtml/issues/22430)

added performance information for fallback images

---

gulpfile.js/build.js
platform/lib/routers/growPages.js
platform/lib/utils/cssTransformer.js

Fingers crossed: this moves the selector rewriting which formerly happened during build time into a custom amp-toolbox-optimizer transformer.

♻️ Move selector rewriting into amp-optimizer transformer

---

examples/source/interactivity-dynamic-content/Poll/index.html

🐛 Fix poll submit endpoint in preview mode

---

gulpfile.js/deploy.js
gulpfile.js/packager.js
packager/README.md

Adds three new tasks for deploying the packager to GCE similar
to the platform ones.

Add gulp tasks for packager deployment

---

examples/source/1.components/amp-analytics/api.js
examples/source/1.components/amp-analytics/embed.html
examples/source/1.components/amp-analytics/index.html
package-lock.json
package.json

Migrated the amp-analytics example backend to amp.dev.
It updates the example [here](https://amp.dev/documentation/examples/components/amp-analytics/?format=websites).

♻️Migrate amp-analytics example backend to amp.dev

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp.md

update browser console validation doc to show support for other AMP formats.
Related: https://github.com/ampproject/amphtml/pull/23565
This will not be merged until the validator changes roll up and is released, as well the above PR.

Update browser console validation doc

---

examples/source/1.components/amp-bind.html

🐛 Fix amp-bind example api endpoint

---

pages/content/amp-dev/documentation/courses/advanced-course/_blueprint.yaml
pages/content/amp-dev/documentation/courses/beginning-course/_blueprint.yaml
pages/content/amp-dev/documentation/courses/intermediate-course/_blueprint.yaml

Addresses problem #2774 and finds a quick solution

🎨 Remove TOC from courses sites

---

pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-caches-and-cors/amp-cors-requests@zh_CN.md

#2707 
Hi, 
I have translated amp-cors-requests.md into Chinese!

Add amp-cors-requests.md Chinese translation.

---

README.md

This PR addresses the discussion taking place in issue #2790.

Update README to clarify that Windows is not currently supported

---

platform/lib/routers/packager.js

Set vary filter based on path and mimetype.

Better vary filter

---

examples/source/interactivity-dynamic-content/ComboBox.html

Fixes https://github.com/ampproject/amp.dev/issues/2788

re-enable preview

---

frontend/scss/components/atoms/format-backgrounds.scss

Fixes error with amp-optimizer css parser

🐛 Correctly encode inline svg backgrounds

---

pages/content/amp-dev/documentation/guides-and-tutorials/optimize-measure/signed-exchange.md

resolves issue [#2769](https://github.com/ampproject/amp.dev/issues/2769)

updated to include sxg provider

---

pages/shared/data/roadshow.yaml

Adding content for Middle East roadshows

---

pages/content/tests/examples/default_settings.md
pages/content/tests/examples/example_with_comments.md
pages/content/tests/examples/full_html.md
pages/content/tests/examples/head_style.md
pages/content/tests/examples/import.md
pages/content/tests/examples/multi_examples.md
pages/content/tests/examples/no_playground.md
pages/content/tests/examples/no_preview.md
pages/content/tests/examples/preview_inline.md
pages/content/tests/examples/preview_side_frame.md
pages/content/tests/examples/preview_side_frame_short.md
pages/content/tests/examples/preview_top_frame.md
pages/content/tests/examples/template.md
platform/lib/build/samplesBuilder.js

🔍 Do not list sample previews in sitemap

---

platform/lib/utils/cssTransformer.js

🎨 Do not minify CSS variable names

---

frontend/scss/components/organisms/_sidebar.scss
frontend/scss/components/organisms/burger-menu.scss

Fix borders around nav items

---

pages/content/amp-dev/documentation/examples/index.html

🎨 Consolidate navigation title for examples page

---

README.md

Resolved issue [2888](https://github.com/ampproject/amp.dev/issues/2888)

included pip installation instructions for MacOS

---

pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript.md

Removed experimental flags and specified type of example used.

cleaned up amp-script guide

---

pages/content/amp-dev/events/amp-cs-2019.html

This adds location details and updates the FAQ for the AMP Contributor Summit 2019.
/cc @vishaldodiya @pbakaus @ampproject/wg-outreach

Add AMPCS2019 location details and update FAQ

---

pages/content/amp-dev/documentation/courses/beginning-course/index@vi.md

#2717 Hello,
I have translated **index.md** from beginning-course into Vietnamese.
However, in the part that I read and found unclear, I wanted to confirm whether this piece of information was not finished or the content was just like that.
https://amp.dev/documentation/courses/beginning-course/?level=advanced
In this excerpt: _Otherwise, AMP has much in common with other front-end frameworks - so the skills you'll acquire while_
Kindly regards,
Duy Thanh Doan

Add index.md beginning-course (Vietnamese translation)

---

pages/content/amp-dev/documentation/examples/documentation/_blueprint.yaml
platform/lib/middleware/subdomain.js
platform/lib/platform.js
playground/src/template-dialog/template-dialog.scss

* explicitly set origin
* allow credentialed requests
See #2886 #2764

Fix CORS for playground

---

pages/content/amp-dev/community/roadmap.html
pages/content/amp-dev/documentation/components/reference/amp-auto-ads-v0.1@ja.md
pages/content/amp-dev/documentation/components/reference/amp-bind-v0.1@es.md
pages/content/amp-dev/documentation/components/reference/amp-lightbox-v0.1@es.md
pages/content/amp-dev/documentation/components/reference/amp-lightbox-v0.1@pt_BR.md
pages/content/amp-dev/documentation/components/reference/amp-lightbox-v0.1@tr.md
pages/content/amp-dev/documentation/components/reference/amp-lightbox-v0.1@zh_CN.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/custom-javascript-tutorial.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/advanced-interactivity@id.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/advanced-interactivity@ko.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/interactivity/advanced-interactivity@pt_BR.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/live_blog@ko.md
pages/content/amp-dev/documentation/guides-and-tutorials/develop/style_and_layout/placeholders@es.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validate_amp@pt_BR.md
pages/content/amp-dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors@ja.md
pages/content/amp-dev/documentation/guides-and-tutorials/start/visual_story/animating_elements@es.md
pages/content/amp-dev/documentation/index.html
pages/content/amp-dev/events/amp-conf-2019@ja.html

Fixes #2919, #2918, #2917 and #2916.

🚨 Fix various AMP validation errors

---

frontend/templates/views/partials/search.j2

🎨 Embed link icon in search with <use>

---

.dockerignore
.gcloudignore

Ignore infrastructure files

---

examples/source/1.components/amp-lightbox.html

Reset variable in amp-lightbox amp-bind sample

---

pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@es.md
pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@id.md
pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@it.md
pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@ja.md
pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@ko.md
pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@pt_BR.md
pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@ru.md
pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@tr.md
pages/content/amp-dev/documentation/components/reference/amp-access-v0.1@zh_CN.md

📝 Fix validation errors in translated amp-access docs

---

pages/content/amp-dev/about/success-stories/asahi.yaml
pages/content/amp-dev/about/success-stories/kompas.yaml
pages/content/amp-dev/about/success-stories/nobroker.yaml
pages/content/amp-dev/about/success-stories/renovation_brands.yaml

💬 Update case study teaser descriptions
